### ISSUE TITLE
My gold is gone

### ISSUE THREAD

**Issue by ripenoza** [EarthMC/Issue-Tracker#1012]
I was on towny and I took gold out of my ender chest to make a town when the server was restarting. When I came back my gold was out of my inventory and ender chest. I don't know whats happening, I only had 73 gold though but that took a while for me to get

**Comment by jkmartindale** [comment]
This issue tracker is for feature requests and reporting technical bugs that affect all players. You should file a ticket on the [EarthMC support Discord server](https://discord.gg/EZBYmpp), where you'll get a faster response.

The support server is for situations that fit any of these criteria:
- Involves refunding items/mobs that disappeared
- Should be looked at by moderators/admins instead of server developers
- Affects one or only a few people
- Needs a faster response

**Comment by docwhomc** [comment]
@jkmartindale while we will handle the refund via the support Discord, the recurring loss of items still needs to be investigated.  It would be one thing if items transferred between inventories seconds before a crash were lost every now and again, but this appears to effect items moved well in advance (minutes or more before) crashes.
