### ISSUE TITLE
Re-add the compass or promote EMC Factions

### ISSUE THREAD

**Issue by RoseBrugs** [EarthMC/Issue-Tracker#1013]
Recently the compass in the EMC Hub was removed, this is an issue because you are automatically queued for Towny and new players have no way of knowing the factions server even exists. On voting sites EMC is presented as a server including both Towny and Factions, however imagine you are a new player joining the server after seeing the Factions advertisement you connect to earthmc.net like the site says and are automatically queued for towny with 0 way of knowing the command /joinqueue factions or about the direct factions IP.

My suggestion is for the compass to be added back, or for there to be more promotion of the factions IP along with more attention towards the changes and suggestions the factions players make. Before this change factions has been more popular than I have ever seen it reaching player counts in the 80's and as a regular player I can say that the growth and development of newer factions has been good for the server. All of this will end without a change made at this time since the removal of the compass there are 14 players online, prior to the removal we would have had more than double that amount.
 
<img width="564" alt="Screen Shot 2020-03-20 at 12 13 20 PM" src="https://user-images.githubusercontent.com/61991201/77183657-0ee10f00-6aa5-11ea-9988-525a6ccd5148.png">
Here EMC is promoted as a server including factions, with the only IP listed being the one that queue's you automatically into towny. Please consider these changes for the future growth and continuation of this server.

**Comment by VakyaEMC** [comment]
I thinks is a good idea

**Comment by Zvlty** [comment]
Yes, a very good idea.

**Comment by lili502** [comment]
Let's readd compass and delete auto /joinqueue towny.

**Comment by lili502** [comment]
Factions server do some 70/100 player recetly. Plz, do not let it died, let us have some new players to.

**Comment by TacoSeller420** [comment]
Prior to the removal of the "compass" we were legit at ~80 players online at the same time on the factions server.
But now that it's gone since a few days there is LITTERALLY no ways to know about factions // join factions except by doing /joinqueue factions, because of this we are back to some low numbers of players like 10-30 players.

We need to be advertised, we need to be known too. Emc isnt just a towny server, it's also a factions server.
If things were still going well and if the spawn get rollbacked to something "cleaner" than just a griefed area, I'm sure we could even gain a queue for factions. But for this to be done we need new players to be aware of our existence: Bring back the compass, remove the autoqueue for towny and we just also need to advertise factions and everything will be back to normal.
Dont let us die, do not "kill" the faction server.

**Comment by xMarie** [comment]
Factions was recently getting a lot more players, now without the compass the player count is more dead than ever. pls add it back

**Comment by brezhart** [comment]
+1. Make factions great again!

**Comment by Highlander214** [comment]
i think advertising the new IP is a good start, im not aware of why the compass was removed.

**Comment by patukka05** [comment]
I have not seen any new players joining factions since the compass was removed....

**Comment by SvenPhillips** [comment]
We got 80 players at one time and about 60% of the players were new. I don’t see the reason that the mods would just kill off another game mode. Without new players, factions will start losing the interest old players had. I feel that its very unfair to hide factions while advertising yourself as a factions/towny server. 
Just a couple of months ago we got our own admin. All of us thought that we were going to get more attention. And we did get a boosted player count. It looked like we were actually going to become a large server. But, factions can not have any victories, because the mods only care about towny.

**Comment by theseductivemango** [comment]
Totally agree, they need to give factions a chance. It is such an amazing server.

**Comment by Mineturtle795** [comment]
Factions is literally meant to be a joke. It was made last summer to alleviate queue. That is its purpose. To say factions is the heart and core of emc is also a joke. Towny is the main attraction, having the 200 players, the nation's, the cities, etc. Factions is the neglected trash server that's all griefed, old, and boring. No wonder they removed the compass so new players can actually join towny and stay on the server rather than join factions and quit after seeing the hell hole of a Spawn.

**Comment by TacoSeller420** [comment]
Holy fuck Mineturtle can you just fuck off smh, factions wasnt even opened public in summer it was opened in May. Anyway you are known in the server as one of the most toxic and useless player of EarthMc so its not like your opinion really matters

**Comment by patukka05** [comment]
Mineturtle nobody cares about you. If emc factions die I will be sad.

la 21. maalisk. 2020 klo 1.24 TacoSeller420 <notifications@github.com>
kirjoitti:

**Comment by SvenPhillips** [comment]
Mineturtle, even if the factions server was originally made for alleviating queue times, it still has a history and it is a large chuck of the server. At most times (before the removal of the compass) we had a fourth of the players online. The admins kept classic around until it had 0-1 players on at a time, when it did not have an active player base. Why does factions not deserve this same treatment? Although we are not as large as the towny server, we were growing in numbers and in a couple weeks we would have over 100 players. He have a dedicated player base that we would like to see expand. We had about 80 players on at peak hours. You know for a fact that it is better than towny for many things you like to do, like killing people, and such. On factions you can be who you truly want to be. You can do what your heart desires. You know this to be true.
Fix, Eagle, Staff of EarthMC, do not choke an entire active player base because it gives players the freedom to do what they want.

**Comment by theseductivemango** [comment]
Ignore MineTurtle man's a troll.

**Comment by FutureLemon** [comment]
I approve, as a player who recently has been playing both Factions really seems to be getting less and less attention.

**Comment by Mineturtle795** [comment]
@FutureLemon yep sure wonder why nobody plays factions when you and your terrorist group go around spawnkilling new players.

**Comment by Snowyy4K** [comment]
GOOD IDEA

**Comment by Highlander214** [comment]
Factions rn is at a low point, with the number of players online at max like 13. We need a formal reasoning from the admins as to why the compass was removed and what their plans are for the future of the server. As 1 of the few mods who actually try to make the server better, its sad to see such a dedicated community just die off for no reason at all. 

Fix and Karl if you read this pls do something, dont let a part of the community just die.

**Comment by Cactusinapumpkin** [comment]
What if we just put a sign at spawn that says  /joinqueue factions for factions server?

**Comment by Cactusinapumpkin** [comment]
So then people aren’t confused how to join queue for towny and they are aware that factions and the command exsists

**Comment by RoseBrugs** [comment]
> So then people aren’t confused how to join queue for towny and they are aware that factions and the command exsists

That's a great Idea and ideas like that are what I meant when I mentioned promoting the factions server. This and a small broadcast message are the most common ideas for doing this, though we would still need Admin attention to add this sign in and have yet to receive any sort of response. Thank you for your suggestion thought I agree completely.

**Comment by Mineturtle795** [comment]
Kek @KarlOfDuty @fix you retards fucked up when even me, ggovi, has stopped playing emc factions. And I played for like a whole year, and with my alts I probably have the most playtime out of anyone. Even I quit emc facs, and as I have always said the day I quit emc facs will be the day it is truly dead. Bring more newfags so I can actually harass and spawnkill and inside some people, or else it's just fucking stale - ggovi

**Comment by Cactusinapumpkin** [comment]
Ha noob highest playtime my ass

**Comment by Krazy0002** [comment]
I have never really logged onto the factions server, I am more towny but I agree 100%. If a server offers a game mode it should be super easy to access that game mode for new players. The compass was good as it let you pick and even if I picked towny every time I'd much rather it be like that so factions was easier to access.

**Comment by lili502** [comment]
Admin are soooooo long to answer, the server is alredy died...

**Comment by SvenPhillips** [comment]
Im not sure why this is labeled as “new feature when we had it for like 6 months lmao
