### ISSUE TITLE
Ability to buy Premium in "bulk"

### ISSUE THREAD

**Issue by Oln123** [EarthMC/Issue-Tracker#1038]
**Is your feature request related to a problem? Please describe.**
The issue I have with Premium is the monthly payment. Idk what my financials will be in one month or the month after that.

**Describe the solution you'd like**
Add the ability to buy premium for a period of time with one payment. 
For Example - Buy premium for 6 months for $48
I know for a fact id like this more and I feel others would.

**Additional context**
N/A

**Comment by FutureLemon** [comment]
Yes, but auto subscription is also a thing.

**Comment by Oln123** [comment]
Yeah but my point is that while I currently have the money I may not, month to month.
TBC its not like im going to starve to death or anything but say my phone broke and I had to get a new one. I might not be able to afford it that month.

**Comment by jkmartindale** [comment]
> while I currently have the money I may not, month to month

So while you currently have the money for 6 months or however much you want to buy in bulk, set it aside for Premium and let automatic billing pull from that every month.

If month-to-month circumstances change and you have to take that money and use it for something else, that means you couldn't afford the bulk purchase in the first place.

The only way buying Premium in bulk becomes beneficial to someone with unpredictable finances is if  there are discounts for longer subscription periods, such as 6 months or a year.

I'm supporting this idea because it simplifies billing for minors who have to convince their parents to buy Premium for them, and I'm assuming it's easier to ask your mom for EarthMC Premium every 6 months than every month.

**Comment by Oln123** [comment]
I dont control the bank account ( I am 17 tbc).

**Comment by KarlOfDuty** [comment]
This isnt possible with the payment system atm.
