### ISSUE TITLE
Add craftable Elytras and craftable shulker boxes.

### ISSUE THREAD

**Issue by DuranGan** [EarthMC/Issue-Tracker#1053]
Shulker boxes are a better way to transport stackable things such as wood or bamboo.
And about the elytras.... They can be good for better traveling on countries, to get into 
Cities, and for making races.

Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website.

**Comment by FutureLemon** [comment]
I sitll don't think that shulker boxes are worth the risk essentially it gives someone who finds a dupe glitch the chance to dupe everything 27 times faster and that would mean staff are less likely to catch someone who dupes. Especially if you are going to hide your duped stuff in a shulker which is then hidden in a chest because I'm pretty sure coreprotect only shows what you put in chests and not what is in a shulker that you put in a chest. Given that staff also can't open chests in towns it will be hard near impossible to view what people hide in shulkers. Furthermore I would not trust staff with the ability to open and take stuff out of my chests.

**Comment by KarlOfDuty** [comment]
We will not be adding these for the reasons others have already stated above.

**Comment by DuranGan** [comment]
Elytra lag is caused by using hacks.
That's the reason why 2b2t had to banned them.
The admin Hausemaster patched it and unbanned the elytras in 2019.
