### ISSUE TITLE
[Suggestion] Add a minimal required playtime to become staff.

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#1060]
As time goes on EarthMC will always need more staff member and time and time again I can't help but notice there will be a couple of new staff members who only joined the server briefly before they got staff. I could represent you with some examples but that's not the point. 

Out of my own experience and feedback from the community there is a lot of concern regarding staff who haven't been on the server for very long. The main critiques are that these players do not know how the community reacts to certain things and don't know how the rules have to be enforced. There is a lack of feel and knowledge from these newer players who become staff. Something else I have noticed is that these staff members don't really seem to stick around for a long time since their connection with the community is little to nothing and that perhaps is the most important of all for a good staff member.

There can be a simple solution to this problem, if there is a minmal required playtime of lets say 10 days and first time joined of 4 months. These requirements lower the risk and liability new players can be as staff. They know how to act and react when put under a lot of pressure, not only that but other staff members can give a better input into this player since they know who they are. 

It's fairly easy to come on EarthMC play active for a single month while not gaining much attention and then flat out lying on your application. However while this is true for newer players who apply this is not for older players, you cannot simply lie on your application when the whole server already knows who you are and this is why I think it would be a great idea to add such requirements, not only for the server but also for the integrity of the playerbase.

Not only is it easy to lie for newer people since there's no way to actually check it, but older players are more connected to the community and somewhat know how the server is ran. Older players are usually more dedicated to solving problems of people because the server is closer to their heart and genuinely care more, their experience outranks the fancy words someone can put on an application.

**Comment by Cactusinapumpkin** [comment]
You think fix has 10 days playtime? We might have to get rid of him if we implement this rule:/

**Comment by jkmartindale** [comment]
> You think fix has 10 days playtime?

Fix isn't a moderator, he's an admin (and server owner too but that's not the point). Their primary job is to keep the server running, update plugins, and maintain game balance.

Moderation is a different role where you facilitate interactions in the community and are the primary bridge between players and staff. Because moderation is such a community-heavy role, being active and aware of the community is much more important for that role than it would be for a comparatively backstage admin role.

**Comment by FutureLemon** [comment]
> You think fix has 10 days playtime? We might have to get rid of him if we implement this rule:/

Fix has a playtime of 18 days if I am not mistaken, Karl on the other hand 👀

**Comment by Cactusinapumpkin** [comment]
Karl will always be remembered rip lol this is a factor in considering mods but unfortunately isn’t a determining factor of how helpful you can be. When looked into for being a mod, playtime is often overlooked. If playtime was the case I would’ve been offered mod 3 months ago when I started surpassing the mods in playtime. Usually it’s just how the person acts in game and how helpful they try to be and most of the common fixes to issues and bugs can be easily learned when you have the ability to ask someone that knows. There’s always a trial period before mods become actual mods so that issues like low playtime can be assessed and fixed or let go.

**Comment by Cactusinapumpkin** [comment]
My application was simply my name and the reason was I like to help people. Not really much was asked for and in game actions are usually the determining factor not something that could be a lie.

**Comment by jkmartindale** [comment]
> If playtime was the case I would’ve been offered mod 3 months ago

bruh nobody is saying use playtime as the only factor in making moderator staff decisions, just a minimum qualification for those who volunteer.

**Comment by Cactusinapumpkin** [comment]
Mods will not be removed simply for not having enough playtime though, as that is our mistake and not something that could be lied about. Once a trial period for a mod has concluded then we can remove or keep a mod depending on how well they performed under close supervision.

**Comment by KarlOfDuty** [comment]
Playtime isn't very easy to verify in any case, most long-time players have had theirs randomly cleared at some point. I think the moderators with the least amount of playtime have played about 50-100 hours on towny anyway which seems fair to me with how much time is also spent on the hub.

But yes, play time is something we always take into consideration and we will keep doing so.
