### ISSUE TITLE
[Feature] Bring back the 3 second teleport timer.

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1068]
**Is your feature request related to a problem? Please describe.**
Since yesterday the 3 second teleport timer got suddenly removed, but with a 30 second cooldown. Then today, that 30 second cooldown has been removed aswell, meaning you can teleport instantly from anywhere. If that wasn't broken enough, you can tp in pvp aswell, meaning that anyone can tp mid-combat when they're about to die.

**Describe the solution you'd like**
That the 3 second teleport timer gets added back, since it was a balanced way to stop people from teleporting in combat, or add a mechanic to stop people from teleporting while in combat.

**Additional context**
Video to show the problem, credit to Tyce for recording the footage. 
https://www.youtube.com/watch?v=SM3mDfKgfng

**Comment by EmattpoYou** [comment]
Honestly, it only works if you can type fast enough. Some players type so slow that they have a big chance of dying before teleporting away. Most of the things in the server require actual player skill, and if they can type `/t spawn`, `/n spawn`, or `/res spawn` fast enough, they have a skill in the server. Towny isnt 100% supposed to be PvP-centric. Towny is more for people who wanna build. Factions is where the PvP action should be, but people keep trying to act like Towny is the best place to PvP cause there is more people.

**Comment by MineHero43** [comment]
> Honestly, it only works if you can type fast enough. Some players type so slow that they have a big chance of dying before teleporting away. Most of the things in the server require actual player skill, and if they can type `/t spawn`, `/n spawn`, or `/res spawn` fast enough, they have a skill in the server. Towny isnt 100% supposed to be PvP-centric. Towny is more for people who wanna build. Factions is where the PvP action should be, but people keep trying to act like Towny is the best place to PvP cause there is more people.

Okay, no.

PvP has always been a core part of towny, especially considering that it’s a “Geopolitcal” server. Battles and war are part of that, stop trying to reduce it to a mere build server, that’s not what it was ever supposed to be and not what it should ever be.

Factions has nowhere near the same feel as towny, hence why many pvpers remained on towny even when factions was released. Towny is the best place to pvp because of the politics involved, that’s what makes this server special and always has.

It literally doesn’t require any skill whatsoever to type /t spawn mid battle, just get a few blocks away from your opponents and type it, really not hard, and no skill is needed whatsoever.

If you want a build server then go play creative, this is a geopolitical server and I’m sick and tired of people trying to reshape it and reduce it to something that it’s not. PvP and major battles were a core part of classic, early TN and mid 2019, no surprise that those were some of the funnest and most exciting times in the server.

Anyway, +1 Warriorr, bring back the 3 second timer

**Comment by EmattpoYou** [comment]
Everything has to change at some point. Nothing ever stays the same. 
Also you two being PvPers makes this worse. You guys have never actually done anything but PvP and complain for a reset. You also want new players to target and kill just for fun. What the new players want is most likely to build, because when you hear "Earth map server", you'd think people love to build in it. It actually turns them off and would stop people from actually recommending people to the server and cause more stupid drama, like you see here, and make the server have the same 50 people logging on, trying to find who to PvP next. Not everything you play has to be PvP centered. You can go back to playing Skywars on Hypixel if you want PvP to be the main focus of the server so badly.

**Comment by 10op10** [comment]
> Everything has to change at some point. Nothing ever stays the same.
> Also you two being PvPers makes this worse. You guys have never actually done anything but PvP and complain for a reset. You also want new players to target and kill just for fun. What the new players want is most likely to build, because when you hear "Earth map server", you'd think people love to build in it. It actually turns them off and would stop people from actually recommending people to the server and cause more stupid drama, like you see here, and make the server have the same 50 people logging on, trying to find who to PvP next. Not everything you play has to be PvP centered. You can go back to playing Skywars on Hypixel if you want PvP to be the main focus of the server so badly.

Its not that, the thing that turns them off is the fucking queue, also newfags get a pvp prot so they can't be killed by anyone so you are literally chatting out of your own ass

**Comment by MineHero43** [comment]
> Everything has to change at some point. Nothing ever stays the same.
> Also you two being PvPers makes this worse. You guys have never actually done anything but PvP and complain for a reset. You also want new players to target and kill just for fun. What the new players want is most likely to build, because when you hear "Earth map server", you'd think people love to build in it. It actually turns them off and would stop people from actually recommending people to the server and cause more stupid drama, like you see here, and make the server have the same 50 people logging on, trying to find who to PvP next. Not everything you play has to be PvP centered. You can go back to playing Skywars on Hypixel if you want PvP to be the main focus of the server so badly.

Excuse me but the implication that all I do is pvp and that only pvpers want a reset is not only insulting but it shows your lack of common knowledge about the server. I made the first nation on the server, Britain and I currently own the third largest town in terms of chunks, London. PvP is very much a core feature for not only my nation but other nations as it allows battles and wars to take place which spices up the game.

No, nothing has to change. It's only new people like you who can't handle basic pvp and therefor try to harm the entire server by reducing it to something that it was never supposed to be. I never said PvP is to be the main focus of the server, stop putting words in my mouth. I emphasised on the fact that pvp and warfare is essential on a geopolitical server, which it is.

Drama and politics is what makes the server fun and unique, if you can't handle even a little of that then this clearly isn't the place for you. A build server isn't what made emc explode in popularity, it never was a mere build server and should never be.

**Comment by KarlOfDuty** [comment]
I already readded it yesterday, the server just hasn't restarted yet

**Comment by Cactusinapumpkin** [comment]
I would say the relationship between nation and the space, resources, building of the nations is the main part of geopolitics. Territorial wars between nations are usually who ever can pull enough resources to claim the land faster or agree on a border. 

I would think minehero of all people would understand that individual pvp based on politics isn’t really what this server is about when you were confused by that judge Judy person attempted to kill you when you were collecting sand.

 Factions on the other hand was a simple solution to what I assume was a quick fix for the absence of warplugin in towny.

Factions is pvp oriented and has raids and junk, while most people join towny to build towns, nations, and run economies. 

The fact is that classic died.

Pvp isn’t a main part for most of Minecraft generally, usually that’s why people play this instead of combat/shooting games. 

Imagine playing halo3 and stating that building stuff in forge is the central part of anyone who plays in multiplayer and if you want to fight someone then go to campaign.

**Comment by Cactusinapumpkin** [comment]
Also I agree it should be added and wasn’t removed for a specific reason and will be added shortly back after restart

**Comment by FutureLemon** [comment]
> Factions on the other hand was a simple solution to what I assume was a quick fix for the absence of warplugin in towny.
>
People love factions and it wouldn't be a quick fix if the compass came back. Maybe then more people who like pvp will play it again, but right now new people who are interested in pvp don't know of it's existance.

**Comment by MineHero43** [comment]
> > Factions on the other hand was a simple solution to what I assume was a quick fix for the absence of warplugin in towny.
> 
> People love factions and it wouldn't be a quick fix if the compass came back. Maybe then more people who like pvp will play it again, but right now new people who are interested in pvp don't know of it's existance.

Even when the compass was around, many pvpers still played towny. Factions was nowhere near as popular as towny. Factions will never have the same feel to it that towny has since it's all about building square boxes and surrounding them in water. You can try forcing people to play factions as much as you want but it won't change anything.
