### ISSUE TITLE
[Suggestion] enable end and normal world difficulty

### ISSUE THREAD

**Issue by Fr0stieXD** [EarthMC/Issue-Tracker#1098]
**Is your feature request related to a problem? Please describe.**
World difficulty set to peaceful makes it hard to get items and the end makes it impossible to get elytras and shulker boxes which are both needed to travel and store stuff

**Describe the solution you'd like**
Enable end and make the difficulty anything but easy because hostile mobs don't spawn

**Additional context**
nope

**Comment by unbatedaura409** [comment]
The server isn't peaceful. A simple press of the ESC key would reveal that

**Comment by Fr0stieXD** [comment]
> The server isn't peaceful. A simple press of the ESC key would reveal that
You know what I mean its on easy and hostile mobs don't spawn

**Comment by unbatedaura409** [comment]
True, but Fix will never enable the end. He has stated this numerous times

**Comment by FutureLemon** [comment]
The staff purposfully decided not to enable the End because the chunks loaded would cause too much lag. They also opted to not add any Elytras due to the insane amount of lag it can cause while loading chunks in the overworld or nether. Also shulker boxes are too dangerous to exist because if someone has them and a duplication glitch is found you can completely ruin the whole server within minutes and it's easier to hide those duplicated items. 

As for the difficulty it is not set to peaceful, but mobs are disabled to prevent lag. Believe me when mobs were enabled the server was much much worse.

**Comment by nipdip** [comment]
The main problem is it makes it very hard to get certain items, like white dyed items and bone blocks from skeletons, string from spiders, ender pearls for endermen, wither roses for withers, and other items like renewable ores will be impossible without mobs.

**Comment by jkmartindale** [comment]
> The main problem is it makes it very hard to get certain items, like white dyed items and bone blocks from skeletons, string from spiders, ender pearls for endermen, wither roses for withers, and other items like renewable ores will be impossible without mobs.

**Bones:** Grind McMMO excavation to level 200, and bones have a 10% chance of dropping from gravel.
**String:** Grind McMMO excavation to level 250, and string has a 5% chance of dropping from clay. Don't have clay? Bows are a rare-class item in McMMO fishing, and you can use an McMMO salvage anvil (gold block) to convert the bow to string.
**Ender Pearl:** Rare-class item in McMMO fishing.
**Wither Rose:** ¯\\\_(ツ)\_/¯

**Comment by Fr0stieXD** [comment]
well this wont be going anywhere ty for the tips on how to get items though
