### ISSUE TITLE
[Feature Request] Remove Nation teleportation

### ISSUE THREAD

**Issue by Zardinio** [EarthMC/Issue-Tracker#1129]
Currently in EMC, there are a plenitude of nations, in some cases needlessly. In order to travel the map nowadays, you can simply teleport from one nation's capital to another. As a result, boating and especially horses, and other forms of transportation have been negated. In addition traveling to individual towns is rendered pointless because why bother going to any town for that matter if you can just teleport in-between nations.
And it's a shame too because there are good reasons to join a nation with your town, there is some reason to own a town, and there are sometimes plenty of good reasons or rather there can be good reasons of visiting towns, such as trading and relations with individual towns versus relations with nation capitals solely. 

Others would have suggested that we allow allied nations to teleport to allied towns, and allow commerce to transition with it. Making there be reason for individual towns to have trade stalls and markets but that solution doesn't fundamentally fix the broken problem caused because of teleportation itself.
Let me put it into perspective, in MMOs, the game wouldn't be fun if you could teleport all around the map with ease, then what's the point of actually going anywhere if you can just simply teleport?
The ease of teleportation ruins any reason for neighboring towns to actually engage in meaningful interaction, if they could simply just ally with a capital and teleport anywhere and get any good they wanted on the server. 

So why don't we disable allied nation teleportation and instead encourage players to focus more on regional affairs and districts within their continent?
If players wanted to sell a good to someone else in a market, they would have to go through territory they don't control versus teleporting past it.
That simple fundamental change would revive local towns caught in choke points or in between major nations. Which would encourage regional trade and trade routes in between major hubs/nations.
It would give reason for players to distribute goods they make in one area and transport it to another, making individual items worth more, given the additional cost of transporting those items.
So if we disable/limit teleportation in between and inside of nations, why don't we encourage the movement between these nations?

I think there are several ways to go about doing this: (each with their own challenges)
-Smaller EMC map (faster transportation)
-Elytras (faster transportation)
-Shulkerboxs (despite the duping, in theory it enables higher volume of items to be transported in-between nations along trade routes)
-Larger nation radius sizes (encourages pvp and sieges in between towns, over vital trade routes, more expansive peaceful territories for trading ex:Australia.)
-Expanded claim capability of towns and capitals.
-Smaller amount of embassies available. (Less land monopolization between a few rich merchants)

I think players will see the following benefits:
-Increased regional trade (good for towns, and strategically located nations)
-More infrastructure being built in-between towns to service the new demand for transportation. Think Canals we've seen during the industrialization of Europe in real life.
-More Realistic alliances between nations. (discouraging alliances across huge distances)
-More of an inward and regional perspective towards township and nation-ship for Kings and democracies.
-Value given to Egypt for controlling the Suez Canal, other strategic choke points for trade. 
-Embassies are more valuable. (To be able to control a shop or market in a local town is great and worthwhile.)

The suggestion:
-Disable Allied and Neutral Nation teleportation.
-Allow only residents of a nation to teleport to the Nation's Capital.

**Comment by suneettipirneni** [comment]
Correct me if I’m wrong but I think this a config option

**Comment by MineHero43** [comment]
I’ve been suggesting this for quite sometime now, you perfectly summarised all the reasons as to why this is such a necessary change.

Couldn’t agree more, 👍

**Comment by AmphireYT** [comment]
Very disagreed. No new player is going to waste 5 hours of there time to travel to make a town. (Not including the que time). Also, it is going to be very boring traveling across the map just to get like some snow or seeing a huge nation being build. Also, wars are going to be like 1-2 people because if they die, i bet there ever going to come back. I could keep going but theres no point if doing so because this idea just sucks in general. If you want to experience this, best of luck

**Comment by Goosius1** [comment]
I aggree with the analysis too.

Here is a suggestion for consideration:

* Let nations have spawns
* But also let there be a cooldown time for n spawn travel be like 1 hour
* This would still allow players to explore far off lands, send soldiers to assist far off allies, or execute any once-off activities like founding a new town in any preferred location.
* But at the same time the value of local relations would be greatly increased - local shops would see a big uptick in trading due to now-higher accessibility, and local allies would become essential due to the difficulty of bringing in far off allies for local wars.
* This could be seen as a trial of more limited transportation ideas. Player response could be tested more safely than with a more complete restriction. Then if more/less restriction is found to be suitable, adjustments can then be made.

**Comment by DeadGlamour** [comment]
I generally like that idea, but just a few notes:
1. The map's size cant be modified anymore, so that isnt really relevant to TN.
2. Lowering embassies count is kinda annoying because sometimes I want to build in other towns or help some1 but lowering the embassies cap severely hurts this option.
3. Shulkers are just too risky, they make every dupe way more dangerous, maybe if you couldnt store gold in it then it'd be fine.

**Comment by remcodd2** [comment]
I would agree except there are two issues

1. It would mean that people will clutter even more in EU and NA, so they dont have to travel far to get to others.

2. Iceroads barely work currently due to the lag.

If the lag would be fixed, i wouldnt mind seeing the nation spawn gone since then we can actually use iceroads

**Comment by alekb1** [comment]
I agree that it should be disabled, and I've also been encouraging this for over half a year

**Comment by 10op10** [comment]
I love this idea because it makes emc more realistic, the only issue I have it the elytras and shulker box's, elytras are too op and shulker just make dupes really easy to perform

**Comment by Zardinio** [comment]
> I love this idea because it makes emc more realistic, the only issue I have it the elytras and shulker box's, elytras are too op and shulker just make dupes really easy to perform

How are Elytras too op? It will be the fastest way to travel if we do not have teleportation.

**Comment by Zardinio** [comment]
> I would agree except there are two issues
> 
> 1. It would mean that people will clutter even more in EU and NA, so they dont have to travel far to get to others.
> 2. Iceroads barely work currently due to the lag.
> 
> If the lag would be fixed, i wouldnt mind seeing the nation spawn gone since then we can actually use iceroads

That's why I suggested a smaller map. We cannot even make use of our current map now as much as we want to. Of course, that would require a reset. Usually I am against a reset; however, if there were to be Elytras and limited spawning, among  nation teleportation restrictions.

**Comment by Zardinio** [comment]
> I generally like that idea, but just a few notes:
> 
> 1. The map's size cant be modified anymore, so that isnt really relevant to TN.
> 2. Lowering embassies count is kinda annoying because sometimes I want to build in other towns or help some1 but lowering the embassies cap severely hurts this option.
> 3. Shulkers are just too risky, they make every dupe way more dangerous, maybe if you couldnt store gold in it then it'd be fine.

I think the map size can still be modified, just not in a good way. Or rather efficient way.
What if, now here me out, we cut off parts of the map. Particularly Antarctica and the Artic. Now I probably shouldn't be suggesting this because I live in the Antarctic and I love my nation but if this means I can get elytras and limited teleportation, less lag as well, then I'd rather have that. I see as a huge improvement.

I thought the embassy idea as a shot in the dark. I thought artificially limiting it would force more shops to become local vendors over monopolistic merchants but overall I agree with your point.

**Comment by Zardinio** [comment]
> Very disagreed. No new player is going to waste 5 hours of there time to travel to make a town. (Not including the que time). Also, it is going to be very boring traveling across the map just to get like some snow or seeing a huge nation being build. Also, wars are going to be like 1-2 people because if they die, i bet there ever going to come back. I could keep going but theres no point if doing so because this idea just sucks in general. If you want to experience this, best of luck

New players already do this, and if you just joined the server and decide to join any nation, my feature suggest will still allow you teleport to that nation. So as a new player you still have the choice and ability to teleport around the world. Maybe there will be players who become nationless and roam the server joining nations whenever they want to go somewhere.

With the added note of queue time, I would case that as a different problem entirely that isn't really related to this topic. In another reply I suggested limiting the map size by cutting off parts of the map to help combat lag, why don't we do that and extend the overall server size to 200? or something even higher?

And here's thing about wars, if the battle is within a reasonable skip from the nation's capital. Everyone in that nation can teleport to the nation's capital. Allowing them to traverse to the front line whereever that may be within their nation. Even if that was far away, just use the infrastructure already built or use an elytra and fly there yourself. Both are expedient. 

Note: town members can still do /t spawn

**Comment by alekb1** [comment]
Honestly elytras and shulkers are just a pain, and not very realistic, so imo keep the server as is or make it harder. One of the things that could be done to make it harder could be no n spawn of other nations as suggested

**Comment by Zardinio** [comment]
> Honestly elytras and shulkers are just a pain, and not very realistic, so imo keep the server as is or make it harder. One of the things that could be done to make it harder could be no n spawn of other nations as suggested

I am no longer arguing for Skulkers, it was a hypothetical.

I am arguing for Elytras to be added to elevate the qualms of having to walk 5 hours in game to get anywhere. It's to balance out the teleportation being removed.
I still don't understand why you think Elytras are a pain. (I do understand shulkers though, because of duping).

Realism wasn't the goal, the goal was to make towns and regions associated under towns more influential and worthwhile. Giving power back to people who own towns versus clusters of nations and their respective teleports.

**Comment by AmphireYT** [comment]
Yall forgetting how much lag elytra cause.

**Comment by jkmartindale** [comment]
> I still don't understand why you think Elytras are a pain

One of EarthMC's biggest sources of lag is how often chunks get loaded. When people have asked for elytra in the past, admins like Karl have denied the requests because of the massive increase in chunk loading they would cause (see [#641](https://github.com/EarthMC/Issue-Tracker/issues/641#issuecomment-515779967) and [#829](https://github.com/EarthMC/Issue-Tracker/issues/829#issuecomment-559562639)).

Chunk loading isn't just an elytra issue, it's a ground transportation issue in general. I think one reason nation teleportation is still around is because people now have to load all the chunks between them and their destination, instead of just the destination chunk when they teleport.

**Comment by Zardinio** [comment]
> Yall forgetting how much lag elytra cause.

Actually, I suggested we decrease size of the world map in the original post.

But no, elytras don't themselves don't cause massive amounts of lag reason being: we're not loading any new chunks. Our map is already pre-loaded. 

If you think elytras shouldn't be added because of lag, then we might as well ban using ice rails and boats as well. While we're at. Ban horses too. Because given the limited render distance and limited chunk loading speed on this server, you could walk and lag the server.

**Comment by jkmartindale** [comment]
> we're not loading any new chunks. Our map is already pre-loaded.

Chunk generation isn't the same as chunk loading. Chunk generation you're familiar with, it uses the world seed to determine what blocks are in a chunk and then writes that to the world save. In this case the map was manually generated, so chunk generation doesn't happen on EarthMC.

But EarthMC has a massive map, and keeping all chunks in memory would be extremely expensive and slow. Something Minecraft does by default is limit the number of chunks loaded in server memory, which is why if you're too far away from a chunk mobs don't move and redstone and other tick-dependent stuff doesn't happen. It's enough of an issue as-is with normal Minecraft maps, but with the massive map size and concurrent player count of EarthMC, it becomes so much of an issue that they've added additional plugins to more aggressively limit how many chunks are loaded at a time.

Obviously decreasing map size and player count would help with that, but Fix and Karl have said numerous times that they're not interested in a world reset yet.

> we might as well ban using ice rails and boats as well

We have these and not elytra to allow players to move non-player mobs, and because it's a lot easier to just not let elytra be craftable (with phantom membranes not existing) than to prevent players from building structures.

There's also a massive difference between what we have right now, where you might have a handful of players using ground transportation at any given time, and *everybody* using ground transportation at the same time because teleportation is no longer an option.

I'm perhaps a little skeptical that introducing elytra would significantly impact chunk loading rates, because they're more fun than practical beyond medium distances. I think most players would still choose teleportation over elytra. But if teleportation was disabled, the chunk loading increase would be exacerbated by elytra.

**Comment by GitMocc** [comment]
Didn't feel like reading the literal essays above, my laziness. 
What about limiting /n spawning to allies nations and maybe have like an ally cap or somethin, idk

**Comment by Prismary** [comment]
I know this is old but think it should still be considered. Would change the gameplay a lot but in my opinion holds the chance to make gameplay much more interesting for everyone.

**Comment by alekb1** [comment]
100% agree that this should still be considered, as it would incentivize infrastructure development, and would move some traffic outside of the capitals
