### ISSUE TITLE
Villager Trading

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1157]
I have absolutely no clue what the thought process behind disabling villager trades was. It was a very stupid idea, as it has inflated the value of enchant books and armor and tools, which just isn't cool. Re-enable villager trading, it was a stupid idea that had literally only bad consequences.

**Comment by FutureLemon** [comment]
At least god sets have value again

**Comment by FutureLemon** [comment]
> Maybe if everyone drives up the prices and concludes a reason for the return of villager trades like mending they could re enable trading again

Some players come to EarthMC and dedicate their time and purpose to ruining the economy this is where a huge problem comes in when all they do is sell items for so cheap no-one with more than 10 braincells will actually drop that low but others still buy at those designated economy ruining shops because, why not.

**Comment by NS4530** [comment]
Why don’t the mods just make selling enchants/tools below a certain price a warnable offense, I would prefer that over just banning villagers outright.

**Comment by jkmartindale** [comment]
> Why don’t the mods just make selling enchants/tools below a certain price a warnable offense

ngl that sounds hella unenforceable, as mods would have to intimately track the "going rates" for each item

also rip gifting

**Comment by NS4530** [comment]
> > Why don’t the mods just make selling enchants/tools below a certain price a warnable offense
> 
> ngl that sounds hella unenforceable, as mods would have to intimately track the "going rates" for each item
> 
> also rip gifting

Well it was stupid of the mods to disable a base feature of Minecraft without having any alternatives available, I agree that the cost of stuff has gotten too low but to prevent people from making those all together was irresponsible. 

Villagers being disabled also removed multiple 1000s of gold from the economy due to emeralds becoming useless so I believe they hurt the economy more than they helped it.

**Comment by DeadGlamour** [comment]
I think Librarians should be disabled, the rest of the villagers are very much needed tho, leather and string is very hard to obtain now, leather horse armor is unobtainable, bells are unobtainable, saddles, golden carrots and melons jumped in prices, tipped arrows are unobtainable, and epearls ofc, so yeah villagers are very much needed and should be brought back, and as I said disabling librarians is good but killing all other villager trades and not giving an alternative way to get mending is pretty bad.

**Comment by silver-street** [comment]
> I think Librarians should be disabled, the rest of the villagers are very much needed tho, leather and string is very hard to obtain now, leather horse armor is unobtainable, bells are unobtainable, saddles, golden carrots and melons jumped in prices, tipped arrows are unobtainable, and epearls ofc, so yeah villagers are very much needed and should be brought back, and as I said disabling librarians is good but killing all other villager trades and not giving an alternative way to get mending is pretty bad.

I agree. I can understand where Fix was coming from when he said end-game items were becoming too cheap, however I dont think disabling ALL villagers was necessary. Items like quartz, bricks and epearls have become much more difficult to obtain, which are unrelated to the "end-game items" Fix was talking about. We've also been given little to no transparency from the admins, and we really don't know much about when and if the villagers will return.

**Comment by unbatedaura409** [comment]
Quartz isn't hard to get if you aren't lazy, and I've got like 1 1/2 dubs of brick blocks.

**Comment by imableeblob** [comment]
@FutureLemon  - God sets only jumped in prices because they are virtually impossible to make.  Thats price gouging and not a real price increase related to supply/demand. Secondly, players who come on EMC to "ruin" the economy is related to duping. Not villager trading. Its a VANILLA mechanic. There are numerous "infinite" villagers who can forever trade without limits. These are created by mods who rollback for their friends. Lets focus on those..
@Cactusinapumpkin - Shops undercutting eachother is the purpose of capitalism, if a shop can produce for cheaper and still profit, they can lower their prices.. Price inceases are happening because of gouging because players know its impossible to produce many of these items. Things will go back to normal once villagers are re-enabled. This "solution" will have done nothing. Keeping this dumb idea in place only limits many vanilla items. I see no purpose of it..

SOLUTION: Fix, if you're reading this. Removing trades will not help keep prices up. You need a pernament fix which will probably require a plugin. Either: Disable only librarians but add custom crafting for mending, Get a plugin that lets for custom trading price ranges. Or a plugin that disables certain trades.  Secondly, to help keep prices from crashing, a world wipe of majority of the villagers will keep villager farms low and not allow for quick mass producing.

**Comment by Cactusinapumpkin** [comment]
The solution needs to avoid people making tickets about their villagers being rendered useless or completely wiped. And I’m pretty sure the purpose of disabling the villages was to end capitalism on the server because people were exploiting the price gouging method and causing an Issue with some people holding large amounts of gold and spending as less as possible into the economy and making shops useful for the extreme poor using there gold making the economy poor. Disabling villagers make people spend gold boosting the economy.

**Comment by NS4530** [comment]
I genuinely don’t see how removing items from the economy will make them more valuable, all removing villagers did was make emeralds worthless, mending extremely expensive, and removed a ton of other items easily accessible through villagers expensive or unobtainable. Not to mention the fact that all the people who had large stockpiles of stuff like mending books were the same people who hoard money so they most likely won’t sell for reasonable prices due to them not being able to obtain more. So disabling villagers only hurt new players or other people with little gold who need to buy things like god armor or pickaxes to stay safe or work while making the money hoarders even more money.

Anyway I think villagers should be brought back as they were thanks.

**Comment by Cactusinapumpkin** [comment]
I genuinely don’t see how removing items from the economy will make them more valuable. Yes

**Comment by Cactusinapumpkin** [comment]
That’s why people agree to keep their prices the same or close to the same because they know they will just lose value until it’s not worth the value of what everyone believes is the value. Belief in the value of something is the only holding the economy together because it’s not backed by actual currency.

**Comment by NS4530** [comment]
Wouldn’t it be easier to make gold harder to obtain that to make tons of items impossible to get though, then the price of literally everything goes up.

**Comment by imableeblob** [comment]
@Cactusinapumpkin I am unfamiliar with how much you know about economics but I have taken numerous college classes on it. The price gouging is happening because of this decision. Yes prices go up when supply goes down but that is a very basic level of looking at an economy. Things are different when you make it impossible to obtain those items. These price increases are not genuine. The purpose was not to end capitalism. Fix wanted higher end-game item prices which is understandable. However limiting the economy and vanilla mechanics will not do this permanently. Disabling villagers will not make people spend more. Demand has not increased for these items. People are just trying to find the remaining that remain on the market. We can't just stall villager trades for forever.  He needs to make villagers scarcer, and prices higher on villager trades.

**Comment by NS4530** [comment]
This entire thing is really demoralizing because you could’ve spent months working to get the best villagers and payed 100s of gold in claim space to store them just to have them disabled. It really puts into question as to wether people should try to pursue any business when the mods can just disable it and render your shop defunct.

**Comment by Cactusinapumpkin** [comment]
Bleeblob I talking about shops price gouging lower prices than other peoples shops before villagers were disable not the increase in prices after.

**Comment by imableeblob** [comment]
@Cactusinapumpkin  Definition of Price Gouging: Price gouging occurs when a seller increases the prices of goods, services or commodities to a level much higher than is considered reasonable or fair. Usually, this event occurs after a **demand or supply shock**. Common examples include price increases of basic necessities after natural disasters.

I believe you are mis-using the term

**Comment by imableeblob** [comment]
Secondly, pricing items competitively is fine. There should be nothing wrong with that. The reason they got so low was because of dupes and broken villagers spawned in by mods

**Comment by Cactusinapumpkin** [comment]
no it’s not it’s just a common issue with mmos regardless of dupes and mod spawned villagers. Because the gold is exsist if from thin air and mined and people don’t have enough places to take gold out of the economy like buying plots or crafting with gold

**Comment by bluestonecarrot** [comment]
Yes. Completely agree. The mods themselves are such a large issue on this server. The fact that a mod can just pull an illegal item and give it to their friends who sell it for 1000s of gold shows that Fix needs to get the mods under control. **NO MOD SHOULD EVER BE GIVEN ANY PRIVILEGES ON THE SERVER BEYOND THE BANNING AND WARNING. THERE IS NO REASON FOR A MOD TO BE ABLE TO SPAWN IN ILLEGAL ITEMS OR BROKEN VILLAGERS**. 

Personally, I think villagers should come back, but let all purchases require a certain amount of gold _on top of the emeralds_. This way end game items will be more expensive but still obtainable. Hell, I'd be willing to make such a plugin if it would be used. (If anyone knows how I can join the dev team lmk)

It's absolutely ridiculous that villagers are completely gone because some items are literally impossible to get now, like ender pearls.

**Comment by jkmartindale** [comment]
> some items are literally impossible to get now, like ender pearls

Nah, you can fish for those.

If EarthMC enabled vanilla fishing drops in addition to McMMO drops, then other items like enchanted books would become obtainable as well.

**Comment by NS4530** [comment]
Villager trading shouldn’t have been disabled without there being alternate ways of obtaining useful items already set up to replace it. Stuff like mending is commonly found being bought for nearly 30x what it cost before villagers were disabled. If someone wants mending on their armor and tool it’ll set them back about a stack of gold. This takes more money away from people who work on things as they have to constantly pay to replace their tools while giving money to the people who make the tools and already have tons of now rare villager items saved. I do not see how this is helping the economy.

**Comment by KarlOfDuty** [comment]
As villagers lower server performance I think we will keep things the way they are at least for now.
