### ISSUE TITLE
New features (by moldemort)

### ISSUE THREAD

**Issue by Harvy-Oswald** [EarthMC/Issue-Tracker#1164]
1. Allow /n spawn only on limited distance
2. Add jail plugin
3. Add transport (like planes or cars)
I'de be grateful if you've added that.

_Sorry for English_

**Comment by glitchism** [comment]
> 1. Allow /n spawn only on limited distance
This affects many playerbase, they can't tp somewhere further, and they need to buy something from that nation that is far away
> 2. Add jail plugin
Idk, other opinions maybe.
> 3. Add transport (like planes or cars)
EMC is already "LagMC", no more plugins or mods, or the server will be lagger
 > _Sorry for English_
This line is already wrong lol

**Comment by glitchism** [comment]
Simply, no

**Comment by jkmartindale** [comment]
Congrats on making your first GitHub issue! Normally people like to separate multiple suggestions into individual issues to make it easier to manage, categorize, and discuss them. There's also a search box on the issue tracker homepage that you can use to find old issues. It's usually better to bump those discussions than to open new duplicates.

But anyway,

> 1. Allow /n spawn only on limited distance

Could you explain why this would be beneficial? There's already a lot of issues in this repository (too many to link) that ask to disable /n spawn entirely, and I'm not sure how adding a distance limit would be functionally different from that option. It would be helpful to mention how big you think the distance limit should be.

> 2. Add jail plugin

EarthMC disabled Towny jails because they are easily abused to trap players indefinitely, and even moderators can't intervene. Until Towny addresses this, Towny jails are disabled (see #430, #504, and #751). If you have a specific jail plugin you'd like to suggest, you could open a new issue asking for the admins to look into installing it. But given the current state of lag on EarthMC, they're probably not willing to add more plugins right now as @glitchism mentioned.

> 3. Add transport (like planes or cars)
> I'de be grateful if you've added that.

Requests for vehicle plugins have been denied in the past because of performance issues and entity glitches (see #295, #359, and #956).

**Comment by Harvy-Oswald** [comment]
Forgot to say , im not moldemort. Im Harvy_Oswald. Moldemort couldn't open issue and asked me to do it. If you have any questions ask it to moldemort, not to me.

**Comment by shirazmatas** [comment]
follow format
