### ISSUE TITLE
[Rules] Fix the moderation system

### ISSUE THREAD

**Issue by redrockruby** [EarthMC/Issue-Tracker#1169]
The current moderation system is fucked up, ok? We need *some* standard of punishment, and the rules page doesn't specify anything (except alts and illegal mods). We need changes, and that is changing the punishments of doing stupid shit, and enforcing it. I'm tired of getting 2 warns for the same thing when a person who did worse gets none. I am sick and tired of that shit. Do you want a decent community? Make sure that you have punishments for people who do bad things. Make it so that a simple racist comment or spam is a 15 minute mute. Fix the chat filter so that spam (#1054) and racial garbage like "Ching chong" cannot be said. Make griefing a definite warning, and trapping 2 warns. Do things so that they have a definite punishment AND POST IT ON THE FUCKING SITE! Also, make a shift schedule for your very inactive staff. Make each and every one of the mods know the rules and punishments before promoting them, and also demote them if they are inactive for too long. Run background checks on people submitting tickets to make sure that they aren't trying to be a fucking degenerate of a 2nd grader tattletale. Make sure your mods aren't biased depending on the person's amount of money spent on the server. 
### AND YES, THIS IS POINTED TO FIX AND THE ADMINS (mainly Karl)

**Comment by MineHero43** [comment]
There are literally mods who only log on once a month to vote and stop their towns from falling, we love our active staff : D

I agree though, especially on the point about punishments needing to be standardised.

We can’t have a system where mods make up the punishments as they go along, eg one mod warns for one thing whereas another mod doesn’t care or mutes. The rules page should specify the punishments for each rule, for example first offenders get a warning, second offence it’s a mute etc. This should be specified for each rule.

**Comment by Cactusinapumpkin** [comment]
Well the issue with enforcing the rules is that the community sees that and thinks that the staff is just out to warn and ban the community. There is a large toxic community because it’s a geopolitical server. We are trying to as mods help the community more than hurt it that’s probably why there has been some leniency with warns and bans lately. You have good points but another issue is that the more specific and less generalized we make the rules the more room for people to exploit a loophole in the rules.

**Comment by jkmartindale** [comment]
In the interest of something actionable, a public warn/banlog in Discord or something could be super useful.

Warns and bans are displayed in-game as they happen so they're technically public already, but since they're not logged publicly you can only see them if they apply to you or if you happen to be in the game at the right time.

Having a log all in one place means that players can get more insight into moderator action, and moderators can get a better feel for how to map violations to actions.

**Comment by Cactusinapumpkin** [comment]
Mods can see list of warnings and there’s a discord log for actions like this, muting, etc.. I don’t think the public needs this insight into how many warnings another player has unless you are unbiased.

**Comment by Oln123** [comment]
I think a system where punishments greatly vary creates a lot of confusion. A lot of new players work under the assumption that the mods are unified under 1 entity. In most other servers that seems to be how it works. While I like that mods aren't too professional, there are times where they need to be. Like it isn't uncommon for mods to meme in tickets. My point here is that mods in emc aren't like other servers (This is prob due to emc not being p2w).

**Comment by BamBamTheEggman** [comment]
My Number one issue with the staff team on this server is that there is an obvious and clear bias against server nations and players. More and more each day the moderator DCdylan continues to dig his grave deeper and deeper with the constant attempts to get players like Samisol and Tyce banned for what honestly seems like prejudice from what I can describe as past experiences with these players. It's honestly sickening that the owners of the server will let a bias mod run around and makeup rules and not remove him from the staff team because he is active. Along with video and photo proof of the moderator Highlander stating that he could ban everyone he dislikes and get away with it. Examples
1: https://media.discordapp.net/attachments/616086182736166933/692500634267811888/image1.png?width=380&height=677
2: https://media.discordapp.net/attachments/616086182736166933/692500634502430790/image2.png?width=380&height=677
3: https://media.discordapp.net/attachments/616086182736166933/692500634779516938/image3.png?width=380&height=677
4: https://media.discordapp.net/attachments/616086182736166933/692500635148353626/image4.png?width=380&height=677

It's honestly laughable that these things can happen with staff members and not even punishments can be handed them

What I think can be done to improve the staff team

1) Let people publicly see the warnings and bans a player has. Whether that be in-game or in the discord Both preferably
2) Mods should be eligible for a warning for their misguided antics whether that may be making up a rule or showing constant bias towards one player. I feel that there should be someone on the higher end of the staff team who should focus on this exactly
3) Fire moderators who have already shown a bias. These moderators are giving more resources attempting to removing players they don't like than actually trying to improve the server.
4) Staff who carry out a punishment shouldn't be the ones responding to appeal tickets this creates Bias.

Then again with these suggestions basically a near entire firing and rehiring of the staff team would have to take place. But maybe it is what is best to save the server from falling into a police state like mentality.

**Comment by unbatedaura409** [comment]
No need to swear on the github, it'll only turn admins away from dealing with it

**Comment by amazingmoe** [comment]
> Well the issue with enforcing the rules is that the community sees that and thinks that the staff is just out to warn and ban the community. There is a large toxic community because it’s a geopolitical server. We are trying to as mods help the community more than hurt it that’s probably why there has been some leniency with warns and bans lately. You have good points but another issue is that the more specific and less generalized we make the rules the more room for people to exploit a loophole in the rules.



> Mods can see list of warnings and there’s a discord log for actions like this, muting, etc.. I don’t think the public needs this insight into how many warnings another player has unless you are unbiased.

Let me go into depth with these two replies.

"Well the issue with enforcing the rules is that the community sees that and thinks that the staff is just out to warn and ban the community."

Okay @Cactusinapumpkin , there are good staff on the EMC moderation and admin team such as (in my experience) Pro, CorruptedGreed, Qorrin, Zackaree, etc. Moderators like these are able to separate themselves as EarthMC players and see the situation at hand and understand what is going on so a definite conclusion can be done about this. The problem is, there are some moderators who don't know how to separate themselves from being an EarthMC player to being an EarthMC moderator, and when the community have, multiple times (such as the Highlander incident) exposed moderators for literally abusing their power and literally banning or warning people they don't like and see that the administration gives them a free pass and they continue to move on UNSCATHED, this is why the community lashes out on the staff team because the bad apples still are part of that staff team. Because there are NO CONSEQUENCES for delinquent moderators. If you cannot hold your own group accountable, then why do you not support having consequences for delinquent moderators who can't do their job properly? I feel like discussions like these help when it comes to rule changes, as this can be as open as it can be possible. There are my points for your first quote. Let me go into detail with your second quote.

"Mods can see list of warnings and there’s a discord log for actions like this, muting, etc.. I don’t think the public needs this insight into how many warnings another player has unless you are unbiased."

If a person is in jail in America, the charges that they get locked up on are available as public information within the jail they are being held at. What's the problem with making warnings public for other people? You are merely hiding information from others because people are biased? Of course everyone is biased! We don't live in a perfect world! However, the ideal solution for this is, if moderators aren't going to hold their own group accountable based on bad actions, is to either do one of the two things: One, which is ban moderators from playing the server, or Two, allowing players to ask for a different moderator to be in charge of their ticket. Of course, the first solution will be great, as moderators won't have any attachment to any other player or group of players because they are not a part of the geopolitical mess known as EarthMC, but the only con I can see from this is that detached moderators won't understand how to interpret the rules as if they play the game. The second solution would allow players that have been warned by someone to ask for someone else who has no relation to the situation at hand. That is pretty simple to ask. All you have to do is observe moderators and see who they hang out with on a daily basis. DCDylan hangs out with the America people and chills in their voice calls every single day. CorruptedGreed is the leader of the GRE. Qorrin is the leader of Shimazu, Cactusinapumpkin is the leader of France, so on and so forth. If you truly want to remain unbiased, then asking for a moderator who is not either allied with a set of people/nation(s) or enemied with them or allied with their enemies should be a rational thing to ask for. However, the response then becomes, "the person who warned you knows what you did to get warned". Then the solution to that is simple: Have that unbiased moderator who is detached from both parties listen, so one person can defend themselves while another can explain why. My friend Samisol was about to get wrongly permed by DCDylan because he moved his ticket to "waiting to be closed" because a "moderator vote" happened that made him keep his warns. Had it not been for Karl to see the situation at hand, then my friend would have been wrongly permed. What I'm trying to say is, throughout this long piece, is to hold your moderator friends accountable for their positions and don't provide lip service to the piece of the community that is wanting to be peaceful and bring positive change to the moderator position. Don't respond to events just because a lot of people have proof of a moderator clearly breaking the rules, because that makes you guys look like lazy people who can't hold yourselves to the same rules and are only appeasing the public. You guys applied to be a moderator, so if you can't do your job or are unfairly throwing people under the bus just so admins have to be involved to overturning your judgement, then step down as a moderator. If you can't do your job then quit. You are only being the problem, and not being a part of the solution.

**Comment by laidang08** [comment]
Also the "only 1 appeal" limit is absolutely retarded. However, that's probably just my bias from past experience.

**Comment by JaVolimKatarinu** [comment]
>What's the problem with making warnings public for other people? You are merely hiding information from others because people are biased?

Mods mostly don't make punishments public because the whole server starts spamming F after it. The staff doesn't want to create any unneeded spam. 

> and when the community have, multiple times (such as the Highlander incident) exposed moderators for literally abusing their power and literally banning or warning people they don't like

Fix takes these accusations really serious so, as stated on the rules page, if there is any mod abuse you should try to contact either Fix or Karl about it. Believe me, I experienced that. ;)

>The second solution would allow players that have been warned by someone to ask for someone else who has no relation to the situation at hand. That is pretty simple to ask. All you have to do is observe moderators and see who they hang out with on a daily basis. DCDylan hangs out with the America people and chills in their voice calls every single day. CorruptedGreed is the leader of the GRE. Qorrin is the leader of Shimazu, Cactusinapumpkin is the leader of France, so on and so forth. If you truly want to remain unbiased, then asking for a moderator who is not either allied with a set of people/nation(s) or enemied with them or allied with their enemies should be a rational thing to ask for.

If members of Staff were some kids, then I might believe in this. Otherwise, this ain't holding any water. But yes, players are allowed to ask for a second opinion, ask for another moderator to do their ticket. Its kinda encouraged if the moderator that is assigned has gone away for a bit of time or just isn't available and won't be in the near future.

**Comment by MineHero43** [comment]
> > What's the problem with making warnings public for other people? You are merely hiding information from others because people are biased?
> 
> Mods mostly don't make punishments public because the whole server starts spamming F after it. The staff doesn't want to create any unneeded spam.
> 

You could just make a live website which logs and shows all punishments handed out by staff and to whom. 
Eg: Player: xdog124 Mod: JaVolimKatarinu Punishment: Tempban 2 days Reason Mass Grief Date: 6/24/2020
Essentially it would just be a long list of that.
I've seen other servers do this, it creates transparency between the community and staff team. This wouldn't require you to enable punishments in the in game chat either.

**Comment by jkmartindale** [comment]
> Mods mostly don't make punishments public because the whole server starts spamming F after it. The staff doesn't want to create any unneeded spam.

Just remove F from the anti-spam exception list ¯\\\_(ツ)_/¯

Then you'll reduce even more spam than before by partially addressing #1054

**Comment by jkmartindale** [comment]
As suggested by @MineHero43, a public website is more useful (searchable, referenceable) than an in-game list, and since it is disconnected from the in-game chat I doubt it would coerce as much spam.

**Comment by Oln123** [comment]
@JaVolimKatarinu the this Is tho that fix doesn't respond to messages, I sent him some pics which suggest staff abuse a few days ago and he hasn't responded

**Comment by unbatedaura409** [comment]
lmao yea, and karl just straight up turned off his dms

**Comment by bluestonecarrot** [comment]
Seriously though. The mods need to be controlled. I have been permed by dylan unjustly. I provided evidence that I did nothing wrong but guess who's on my ticket? Dylan. And he's just ignoring the proof.

What happened is I purchased a very rare mapart from someone and apparently it was stolen. Then Dylan banned me for 1.2 knowingly benefiting from hacks WHEN THERE WAS NO EVIDENCE THAT I KNEW AND PLENTY OF EVIDENCE TO THE CONTRARY, AND NO OPPURTINITY TO GIVE IT BACK. And he probably banned me because he wanted the mapart (original owner confirmed I held the only one) because when he banned me, HE GOT PERMS TO MY PLOT AND TOOK THE COPY, KEPT IT FOR HIMSELF, AND INVITED A BUNCH OF PLAYERS TO FLEX ON THEM WITH IT. I literally have screenshots of him admitting to all of this, yet I'm still permbanned because of him. And if we're talking about rules, HE BROKE 1.2 WHEN HE TOOK THE MAPART THAT HE KNEW WAS STOLEN, yet he hasn't banned himself. Such justice on this server

**Comment by Prismary** [comment]
I know this is old, but we have standardzied punishments for most offenses now and try to handle comparable issues the same way by utilizing flowcharts and similar moderation guides. As this thread mostly contains very old controversies, I'll close it for now. Message me incase any of this isn't resolved yet.
