### ISSUE TITLE
Abolish the 3000 block town limit for nations [Feature]

### ISSUE THREAD

**Issue by Joel-02** [EarthMC/Issue-Tracker#1172]
**Sorry for the essay**

I think we can all agree there are too many nations. Whilst the war plugin (if released) will help dramatically reduce the number of nations, I believe allowing towns to be infinitely far away from the capital could be beneficial if the war plugin is released, and **in general** as a whole.

If this were to take place, I believe it could breathe new life into EarthMC; first of all areas of the map that are less claimed could be colonized and taken over by other nations, possibly even Antarctica (eg. British Atlantic territory, et cetera). This would definitely make the game much more enjoyable for those nations who have pretty much-taken everything around them (like Britain).  Terra Nova is far bigger than classic, I cant see one nation dominating a whole large region: eg. Japan in classic. If it were to, it would certainly be met with fierce competition. 

There are more possible benefits; nations, like Russia or the US, would be able to in theory unite properly to their real-life claims. Whilst its highly unlikely they would ever be fully united, it would for sure create some fantastic battles and overall make the game fun and enjoyable for the community. Nations would finally be able to fight for/claim their real-life overseas territories instead of being restricted as well.

Back to my introduction, there is an absurd amount of nations and even the war plugin may not (if released) reduce this to a substantial extent. If the 3000 block limit was abolished, we could see some more interesting wars take place globally and some proper alliances, especially if the war plugin is eventually released. Due to this, no nation would be immune from battle and we would potentially see a dramatic decrease in the number of nations to a more appropriate level. 

Some people will quite rightly say that this will just lead to a couple of massive nations dominating. I personally do not think this would really occur with such a large player base. However, you could put restrictions on the number of towns a nation can have so no nation dominates too much. I do not personally want this, however it may be an appropriate counterbalance if my request were to be implemented (no idea what it would be set at).

I really do hope you (admins/fix) consider this in some form, I think it could certainly make EarthMC more fun for not only old players, but all players as a whole.
Many thanks, 
Joel

**Describe the solution you'd like**
-**Remove** the 3000 block town limit for nations completely
-After this, I suggest making **clear** capitals must still be within the real-life mainland or they are simply named incorrectly and subjected to rule 4.1

**Comment by MineHero43** [comment]
#1113

**Comment by MineHero43** [comment]
#1113 

Personally I'm not a huge fan of North American nations owning territory in Europe or Asia or vice versa etc. I think conflicts should be kept regionally as it divides power on the server instead of creating big globalist alliances/nations who are able to absolutely dominate everyone.

Colonies can still be created, just get someone to make a nation in the area you want to be colonized and align it to your nation. The 3000 limit exists for a reason, regionalism is far better for the server than globalism. This is why I also support removing /n spawns but that's a different debate.

You do have a valid point in terms of Russia and the US being able to unite but that's about the only benefit I can see (I highly doubt they'd be able to unite either way) We'll end up with bordergore galore on steroids, the way the server works now is perfect. Leave Europe to European nations, leave Asia to Asian nations etc.

**Comment by Oln123** [comment]
hmm couldn't you have a rule that says nations must not expand into lands where they have had no historical presence or claim on ? that's broad but it would mean no American towns in Europe

**Comment by MineHero43** [comment]
> hmm couldn't you have a rule that says nations must not expand into lands where they have had no historical presence or claim on ? that's broad but it would mean no American towns in Europe

Sounds good, doesn’t work. For arguments sake, an American would then cite the US occupation of western Germany as a “historical presence”

Might as well keep the limit then

**Comment by Oln123** [comment]
yeah good point actually
