### ISSUE TITLE
[Feature] Shulker Box Recipe

### ISSUE THREAD

**Issue by T0rn4do** [EarthMC/Issue-Tracker#1186]
I guess I can take it as a problem because it's kinda annoying when I want to move nor store big quantities of stuff without having the hability to use shulker boxes. They would clearly help many players in multiple tasks.

I would like getting a custom recipe for them, it must be expensive tho, because it can easily be overabused 
The craft can be composed of an ender chest in the center, 1 gold ingot in each corner and maybe a diamond block in the middle slots (idk).

I think it can be a game changer to add an actual recipe for shulker boxes because they are clearly a good feature in minecraft that I missed on Emc
and that mat help many players.

**Comment by Cactusinapumpkin** [comment]
This has been recommended multiple times. I will let Karl respond to this because he is an admin. But more than likely it is still considered overpowered and disrupt the balance and could possibly aid in duping significantly still. It has more adverse effects that outweigh the problems that it would solve unfortunately.

**Comment by Krazy5225** [comment]
As much as I'd love to see them in the server too I see why they haven't been added. They would change the game completely, and would bring their own wave of problems and patches that would need to be addressed.

**Comment by unbatedaura409** [comment]
The admins have stated numerous times that shulker boxes will never come to EMC and it's for a very obvious reason: duping. We haven't had a really major dupe involving gold since SalC1, and when we did it was because of an outdated shitty plugin. If you know anything about hacked clients or even just basic knowledge about Minecraft, you'll know shulker boxes can easily be used to dupe in MASSIVE quantities. I could send you a video of me proving this on 2b2t if you want

**Comment by T0rn4do** [comment]
I understand that adding shulker boxes would also add it's problems like duping and that they're clearly very overpowered, and i guess just not adding them is simpler than getting a decent anticheat. However I think it would still be a good feature..

**Comment by Krazy5225** [comment]
My thoughts are the same as Tornado's. They would be a really nice edition to the server but I get why they haven't been/won't be added.

**Comment by shirazmatas** [comment]
follow format and repost
