### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by PinkCheetahh** [EarthMC/Issue-Tracker#1192]
Hey, sorry for this but rn we need villagers ,i have some reasons:
-The economy:Now the price is too much ,mending worth 20g ,so when you start earthmc ,you just can’t get a good stuff, and i think many new players go out of earthmc because of that
-War: There will be the war plugin, so if during a fight we break, we just have to pay to get another stuff, so we need to « pay gold » to declare war, that’s not really good.
-The game.Mending is literally everything when you are doing stuff ,we need it, earthmc was fun with villagers, and now, without them (me and many players i think) are bored, before we were thinking about : -Mine (to get gold and emeralds)
-Buy emeralds 
-Trade
-Sell
It was pretty fun but know what can we do?Build?mmh yes but my town is full of builds ,mine?boring, recruit?no boring, we can do nothing we have 0 goals now ,so please Karl, Eagle
and Fix put villagers back for earthmc, many players are leaving, don’t let earthmc die under our eyes.

**Comment by PinkCheetahh** [comment]
also i want to add something to "-War"
How can we make heal pots without golden melons? No one gonna pay 1gold for 3 heal pots lmao. We want villagers back.

**Comment by jkmartindale** [comment]
See also #1157

**Comment by Pengun78** [comment]
Open

Feature#1192

PinkCheetahh opened this issue 13 days ago · 2 comments

Comments

 PinkCheetahh commented 13 days ago

Hey, sorry for this but rn we need villagers ,i have some reasons:
-The economy:Now the price is too much ,mending worth 20g ,so when you start earthmc ,you just can’t get a good stuff, and i think many new players go out of earthmc because of that
-War: There will be the war plugin, so if during a fight we break, we just have to pay to get another stuff, so we need to « pay gold » to declare war, that’s not really good.
-The game.Mending is literally everything when you are doing stuff ,we need it, earthmc was fun with villagers, and now, without them (me and many players i think) are bored, before we were thinking about : -Mine (to get gold and emeralds)
-Buy emeralds
-Trade
-Sell
It was pretty fun but know what can we do?Build?mmh yes but my town is full of builds ,mine?boring, recruit?no boring, we can do nothing we have 0 goals now ,so please Karl, Eagle
and Fix put villagers back for earthmc, many players are leaving, don’t let earthmc die under our eyes.

👍 1

 PinkCheetahh commented 12 days ago

also i want to add something to "-War"
How can we make heal pots without golden melons? No one gonna pay 1gold for 3 heal pots lmao. We want villagers back.

**Comment by BunbunToast** [comment]
Gotta say, mending isn't that good tbh. And it's honestly stupid to use too. You don't really need it, other than on tools like pickaxes/shovels/fishing rod

**Comment by DeadGlamour** [comment]
Villagers were great for other uses too, heres some items we cant get anymore:
Mending
Frost walker
Curse of binding
Curse of vanishing
Bells
Leather horse armor
Arrows with potions effects
Globe banner pattern
Ender pearls
And items we can get but very hard now:
Emeralds
Golden melons
Clocks
Golden carrots
Bricks (most clay deposits are dry)
Strings (most clay deposits are dry)

I dont think villagers will return, and for some valid reasons, but I do think we should get new ways to get these items.

**Comment by jkmartindale** [comment]
> Ender pearls

time2fish

**Comment by shirazmatas** [comment]
repost with format
