### ISSUE TITLE
[Feature] Multi-thread support via forge or other plugin providers?

### ISSUE THREAD

**Issue by nl1213** [EarthMC/Issue-Tracker#1194]
Disclaimer: I know very little about this and have no more research will need to be done if a solution is to be implemented. 

I've been looking at some videos online recently and came across one talking about optimization in minecraft when they started talking about how its only a single thread. For those who dont know what this means, this means that as every command enters the server it does it one by one as fast as it can. Multi threads are better in the fact you have the same setup but more than 1 running doing everything at the same time.
It seems a few projects are taking multi-threading into account. Particularly a project called torch (https://github.com/xiaonian233/Torch-1) is talking about a multi-threading feature and compatibility with spigot plugins.  If this is to be believed this plugin can be used to increase the servers performance drastically. 

While i doubt the server will have the hardware to handle such players using this might solve the issues of player lag issues and potentially even reduce to queue based on server performance improvements and max out active players on the server. 

Again i will restate I dont know much about this myself and there is likely some issues that will need to be worked out before this can even be thought of implemented but i suspect the boost in performance assuming all cores and all threads are running will be enough to outweigh the costs of adding this in.

As a side note It seems torch runs off paper which itself is a pull from bukkit or spigot so the install should be relatively clean and we should get async chunk loading.)

**Comment by suneettipirneni** [comment]
Firstly, while multi-threading is in many cases faster than synchronous operations, it actually can easily become a lot less safe. This is because of desynchronization between threads. It requires a _lot_ of time an effort to implement code running properly on multiple threads. Which is why I'm speculative on forks such as torch. One of the main things paper already does to address this issue is multi-thread expensive tasks such as chunk loading, and worldgen. Also it seems that torch hasn't been updated in 2 years. In conclusion multithreaded is very hard and requires a lot of time and dedication to implement, to make matters worse the vanilla server code that mojang releases is sparsely multithreaded. And yes, I would imagine even for _mojang_ this would be a daunting task.

**Comment by KarlOfDuty** [comment]
The server has already had async chunk loading for years.
