### ISSUE TITLE
EarthMC News API

### ISSUE THREAD

**Issue by ogxn** [EarthMC/Issue-Tracker#1196]
### Is your feature request related to a problem? Please describe.
i don't think there's really a *problem* here

### Describe the solution you'd like
earthmc.net/news GHOST INSTANCE REST API similar to the broken normal API but JSON and actually working (and ofc, it serves articles, not town/nation/player info)

### Additional context

no

**Comment by jkmartindale** [comment]
What's your use case? If you just want to subscribe to new posts, RSS should work fine.

**Comment by ogxn** [comment]
Search, actually. I want to keep a copy of everything in a database, updating daily, so you can search articles with OneSearch

**Comment by jkmartindale** [comment]
tbh it shouldn't be that hard to make something that checks an RSS feed and uses an XML library to transform the interesting bits to JSON.

If you're lazy, you can use an [IFTTT](https://ifttt.com/) applet to trigger on new EarthMC RSS feed entries and make a web request to a script with the Webhooks action. Here's a sample request body for IFTTT:

```
{
    "title": "{{EntryTitle}}",
    "url": "{{EntryUrl}}",
    "author": "{{EntryAuthor}}",
    "content: "<<<{{EntryContent}}>>>",
    "image": "{{EntryImageUrl}}",
    "published_at": "{{EntryPublished}}"
}
```

The `{{{}}}` are variables provided by IFTTT parsed from the RSS feed. The `<<<>>>` tell IFTTT to escape line breaks etc. in the input instead of straight concatenating it. Neither of these formatting marks appear in the actual web request, it's just IFTTT's templating language.
