### ISSUE TITLE
42 Day Inactivity 

### ISSUE THREAD

**Issue by BamBamTheEggman** [EarthMC/Issue-Tracker#1229]
**The Issue**
Players Working around 42 Day inactivity

**Summary**
I think I speak for everyone in the community (Except for those that do this) that the 42 day inactivity timer needs to be turned way down and rules need to be put into place that goes around this. You might be wondering as to what exactly I am talking about so let me explain

For far too long have good nation names/Space for claims have been taken by those who don't want to lose the title or just don't want others to have it. Many of these players have mostly quit the server and if not to rejoin their player data would be wiped and the land would be unclaimed. But these players rejoin at the last possible second so that their towns don't fall and they can hold onto the land for a little longer when it could be put to good use by others. This is especially annoying to European towns because of how little land there is now. There needs to be a rule that stops these acts. Below are nations that are currently under the control of people who log on once every 42 days to keep their nations/towns

**Nations**
Ireland
Denmark
North Sea Empire
German Empire
Poland
Pomerania
Monaco
Avalon
Rio Grande
Texas
Highlands
And more that I cant think of

**How to fix this**
In all honesty, a rule should be made against this and staff should take action against those who are not willing to play on the server unless it means they can keep a title they no longer care for. A player should be allowed to report a town and or nation leader if they log on once every 42 days and see action taken against them. The timer should also be reduced to 32 days. To increase activity

Just my two cents

**Comment by Lagann311** [comment]
I agree this has always been emc‘s biggest issue.
But I‘d rather support the idea of adding nation and towns taxes. This way it would decrease the amount of 1-man nations (currently 440 nations in total I think).
Something like 1-2 gold ingots per day for nations and maybe 3 gold nuggets for towns.

**Comment by unbatedaura409** [comment]
Literally the most based thing ever, keep winning

**Comment by BamBamTheEggman** [comment]
> 
> 
> I agree this has always been emc‘s biggest issue.
> But I‘d rather support the idea of adding nation and towns taxes. This way it would also decrease the amount of 1-man nations (currently 440 nations in total I think).
> And people can still decide to be inactive / keeping their nation / town alive for the cost of gold.
> Something like 1-2 gold ingots per day for nations and maybe 3 gold nuggets for towns.

A tax would indeed be a great thing as well but in my opinion, it would need to be high because vote gold is a thing that could be used as another work around for that and if its to high some players might be up in arms

**Comment by coblobster2** [comment]
How will this fix the issue? What is stopping someone from doing it every 32 days?

**Comment by unbatedaura409** [comment]
It would give a smaller window to remember you are inactive, basically 42 days gives you a lot of time to remember to log on but if you lowered it it'd be far easier to forget

**Comment by Mikeyreza** [comment]
Yea I agree with this, though your nation examples are a little off (Poland and Monaco aren't log on once every 42 day nations afaik)

**Comment by MineHero43** [comment]
Or staff could finally add the war plugin which would solve all of this ¥.¥

Honestly I don’t see a huge difference between 32 days and 42 days, it won’t solve the problem, just shorten it by 10 days. It would be very hard for staff to enforce something against this because people (mostly) work hard for their towns/nations and want to hold onto them, even if it’s at the expense of someone else.

Someone mentioned adding a nation tax, I think that’s probably the best way to go about this. I don’t agree with town taxes because disbanding entire towns simply because someone forgets to deposit some gold doesn’t really sit well with me but if an entire nation can’t pay to remain alive then they should fall imo.

Then again though, just adding the war plugin would be the easy solution to this :/

**Comment by SgtCartoon** [comment]
I think we should reduce that from at least 50%, 20 days of inactivity should be the maximum.

**Comment by FutureLemon** [comment]
Why have a timer for how long you have to be offline before you get your player data removed but instead just make it a monthly quota of activity you have to reach like 5 hours per month, still much more than these inactives play but really easy to achieve. And it also becomes a sport to catch your enemies bypassing afk timers. Just throwing in the idea but an activity quota seems fun to me 😳

**Comment by coblobster2** [comment]
So I'm a bit confused. Are people unhappy a out the towns or the nation's? Why are people seeming to care about the nation aspect? The towns are what is taking space.

**Comment by Lagann311** [comment]
Because there‘s way too many. Emc has more nations than other towny servers I know have towns. It takes away the fun when there‘s so many irrelevant nations, at least for me.

**Comment by DeadGlamour** [comment]
1 thing which people overlook is hte fact it will be way harder to recruit as you will need to recruit more people per day since u lose more people.

**Comment by 3meraldK** [comment]
The biggest issue with EarthMC server is actually many towns/nations are trying to ruin other active nations' games, thus complicating situation and making those new ambitious entities inactive. WE NEED TO STOP THAT, by submitting new rules, which would change that. We would finally play more politics, not inactive-politics. It's not InactiveMC, it's EarthMC, and we really need to change that. BamBam is right, there are many nations which aren't active and ruining others' games. For example, Poland being aggressive to Germany, now, when Germany declares war to Poland they stopped being active and what to do now with Poland? Nothing, because they aren't playing anymore? Please Fix and Karl if you read this - we, also Austrians are requesting those rules to be added.

**Comment by IAmUnStTV** [comment]
> Why have a timer for how long you have to be offline before you get your player data removed but instead just make it a monthly quota of activity you have to reach like 5 hours per month, still much more than these inactives play but really easy to achieve. And it also becomes a sport to catch your enemies bypassing afk timers. Just throwing in the idea but an activity quota seems fun to me 😳 

Yes, this _is_ a good idea. And the Anti-AFK would actually stop players from AFK-ing just to reach the quota.

**Comment by KarlOfDuty** [comment]
We will keep it as it is for now.
