### ISSUE TITLE
[Feature] Rule Notifications

### ISSUE THREAD

**Issue by Bigious** [EarthMC/Issue-Tracker#1239]
### Is your feature request related to a problem? Please describe.
My issue is that the rules of the server are being changed every once and a while and I feel like there is a group of people who don't keep track of discord to know when a rule updates. Also for new players, they don't understand the rules because there is no requirement for them to know, many new players make afk pools and get warned cuz they didn't know.

### Describe the solution you'd like
I would like a prompt when a new player joins the server for the first time, which in it asks for them to type something like accept or yes, with them not being able to see any chats or move until they accept. Also for old players returning to the server when they join back after a rule change, there should be a message in chat, similar to the one when you receive a warning when offline, it should say what the new rule is in green or a deleted rule in red. I don think a prompt is necessary for older players because the possibility there log-off spot was in a dangerous place is enough to not require a prompt. If a prompt were to be added for returners it shouldn't restrict movement, but restrict Chat messages and log them off if they don't accept after 5 or 10 minutes giving them ample time to escape a dangerous log off point.

**Comment by FutureLemon** [comment]
Pretty sure rule updates are posted in the announcements in the Discord, if that's not enough u can subscribe to one of the github pages and will get a notification by email everytime Karl updates the rules.

**Comment by Basically-Andrew** [comment]
First, I don't believe rule changes appear on Github ever since earthmc moved to WordPress; however, a new player should expect each server they join to have their own set of rules they must read and understand. Secondly, all players are already greeted by the day's message, which links the map, guide, rules, wiki, and Discord. This gives players much opportunity to join the Discord and read the rules. Lastly, I believe new players who create an afk pool are kicked first, then warned on their second/third offense.

**Comment by CorruptedGreed** [comment]
Our rules are always updated on our website, it is player's responsibility to keep track along with our changelog showcasing updates
