### ISSUE TITLE
The new crates

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/Issue-Tracker#1246]
So I love the new crates but it is killing the economy and making the server a bit possible pay2win. Now I think taking them away from perks of a premium and replacing the bruh chest is better idea maybe or putting the crates in the bruh chest. Now obviously you dont want to lose the money making factor so bring in effects or other stuff that does not kill the economy. How does it kill the economy? Well each head is selling for gold. Same thing with the old pink heads. Reason why people care now is cause the price of the heads are going up and down and becoming a bigger part of the economy.

**Comment by Camdropz** [comment]
This is so true. I also think that fix needs to rollback to when mystery crates weren't purchasable because people are making a paying for mystery crates and selling them for insane amounts of gold, you can literally make like 1.5k for $40 worth of crates and so many people are abusing it. It's so unfair to everyone who actually gets gold legit and these people are just getting rich without actually playing.

**Comment by Taffffy** [comment]
You took the words out of my mouth

**Comment by coblobster2** [comment]
And no disabling them in shops and /trade will not fix the issue as you can still trade them like when shops and /trade were not a thing. even if you soul bind it you can place it

**Comment by DeadGlamour** [comment]
Tbh, I dont understand why people make such a big deal out of it, its a cosmetic which value is decided by the playerbase, I do think its far from perfect and the fact its a gamble with no way to control what you get kinda destroyed me wanting to get any (I may wouldve actually gotten premium if it was not such a gamble).
But its far from p2w, its a frikin cosmetic and I think its overral a good thing, it supports the server without hurting it.

**Comment by coblobster2** [comment]
The issue is that you are now able to pay money for an object that you can sell for gold. That is pay 2 win. Sure is it directly pay 2 win no. Is it against Eula? Not sure, but it should not be on emc. Emc should not have an option where you can buy gold.

**Comment by unbatedaura409** [comment]
if fix has any sense in his body he will realize that this breaks eula

**Comment by coblobster2** [comment]
It may not actually break the EULA cause you are allowed to sell stuff like this. An example mojang gives is hats. Now that you would be able to sell ingame like this. Now, by no mean does this mean it should be a thing on emc or any server. I see this as a great way to kill a server as it becomes possible to pay2win.

**Comment by americanfrog** [comment]
If ppl are willing to pay for them that’s fine

**Comment by sprite919** [comment]
Why not make trading them in-game against the rules the same way trading in-game items for real money is against the rules, keeping the cosmetic aspect and removing the P2W, economy-breaking aspect? If Fix means for the Mystery Crates to be cosmetic and not P2W, doing this surely wouldn't be an issue.

**Comment by gabeeebaby** [comment]
They are already blacklisted from sign shops, so it shouldn't allow you to make a new shop with a head. They could blacklist them from the /trade plugin, if that is even possible. However, this would make it so people couldn't trade heads for other heads, which should be fine since all heads are the same in terms of function. Also, players would then just resort to trading by dropping the item, and there is no real way to stop that. If it was simply made against the rules, it wouldn't really change it, as most mods wouldn't really enforce it, and it would be hard to catch if the sale is done through pms or on discord. 
The only solution is to remove the ability to buy more mystery crates. I think they can still be included with premium though, as you only get a max of three per month, and that isn't worth enough gold to make it really p2w. 
If Fix needs more money for the server to operate and grow, there are better options than items that easily can be sold for gold. An idea that could be purchasable but not p2w would be trails (like blue donators had before), in which a there could be a bunch of options for different ones and each one could be purchasable for $5 or so. There are plenty of other cosmetics that players could buy, that wouldn't be able to be sold to other players in game.

**Comment by shirazmatas** [comment]
Please follow format and repost
