### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gfhfdjdfgj** [EarthMC/Issue-Tracker#1256]
earth mc

### Describe the bug

i was dropping items in lava then it kicked me for dropping too fast

### To Reproduce

i just was holding q

**Comment by pesetz** [comment]
its not even a bug

**Comment by bwilso1** [comment]
the QA side of me, says "not a bug"
but the end user side of me says "wtf"
an end user with no prio-queue would be pissed for doing a normal in-game action that is not allowed by this server.  No hacks, just plain vanilla minecraft.

I would love the website to mention this somewhere.  Really sucks to have to wait 1hr to play again, because you were taking out the trash

==workaround==
use Shift+E to drop entire stacks, or whatever you end up mapping the crouch button to.

**Comment by jkmartindale** [comment]
From previous issues covering this, 522 and #1182:

Dropping individual items sends more packets to the server than dropping a whole stack. Vanilla Minecraft limits how many packets it accepts per unit of time as an anti-cheat measure. During lag spikes packets from multiple time intervals might be processed all at once when the server catches up, making it easier to trip the packet limit.

**Comment by bwilso1** [comment]
oof, the QA side of me should have known better and should have searched past "bugs" or tickets. (don't tell my boss!)
the player side of me should be temp muted for a bit. 

didn't realize this was a vanilla feature (albeit on laggy servers)
vote to close, mark as duplicate.
