### ISSUE TITLE
[BUG] PvPing allied players

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1275]
### Server

Towny.

### Describe the bug

You can no longer hit players from allied nations in the wilderness or in pvp plots.

### To Reproduce

1. Hit a player from an allied nation.
2. Fail.

### Expected behavior

You hit the player.

### Screenshots

![image](https://user-images.githubusercontent.com/50800980/101350927-1e50f400-3890-11eb-9ad9-182c11274954.png)

**Comment by Fruitloopins** [comment]
I really, really hope this is not intentional. I barely even PvP nowadays but to not only implement this but also force players to ally nations to get anywhere is not good design.

**Comment by Bigious** [comment]
Turn this bitch back on, you're alienating a whole damn subsection of the server just gonna make more people quit shitmc. If yalls really want pvp to be less of a thing then make /party a non premium feature.

**Comment by Takii-Takii** [comment]
Ayo snowy and casper were right tho, ever since the update to 1.15 this server became trash. Things just keep going downhill and even when we thought it couldn't possibly go worse.... well shaking got disabled, n spawns got basically nerfed and the PvP aspect was basically killed. 
If nothing is done in the next week or so I'm pretty sure a lot of players are gonna quit/go inactive.

All of those issues really have to be somewhat fixed asap

**Comment by Warriorrrr** [comment]
@KarlOfDuty Could you look at this issue? It can be easily fixed using the command `/tw toggle friendlyfire`.

**Comment by Warriorrrr** [comment]
Fixed now
