### ISSUE TITLE
[BUG] My amour stand is giving me infinite boots.

### ISSUE THREAD

**Issue by RedstoneFox441** [EarthMC/Issue-Tracker#1306]
### Server

EarthMc Towny

### Describe the bug

When I go to take my boots off my armor stand it will give the boot and put it in my inventory but the boots will still be on the stand. Meaning the boots were duped. I now have 2 boots from the 1 pair of boots I put on the stand origonaly.

### To Reproduce

1. Take boots and put them on the amour stand.
2. click to take the boots off the stand.
3. the boots will be in your inventory and on the stand.

### Expected behavior

I expected the boots to come off the amour stand and go into my inventory.

### Screenshots

![image](https://user-images.githubusercontent.com/50430268/105850808-3865a380-5fb0-11eb-8080-3ff6b1cd628b.png)

### Additional context

I am in a very old, kind of glitchy chunk.

**Comment by jkmartindale** [comment]
This is a client/server sync issue, but you don't actually have duped boots. If you go far away for a bit and come back so that you get the chunk unloaded and reloaded in your client, your boots should show up either only on the armor stand or your inventory.

I tried something similar where I quickly swapped armor out between my main inventory and armor slots and seemingly got infinite armor, but when I opened a chest or other inventory block it would immediately re-sync to just one.
