### ISSUE TITLE
Wither Skeletons

### ISSUE THREAD

**Issue by yankees88888g** [EarthMC/Issue-Tracker#1338]
Make wither skeletons obtain able to allow people to make beacons and not have to use the few players who do already have them.

**Comment by gabeeebaby** [comment]
Allowing wither skeletons to be obtainable again would just crash the beacon market, and make an end game item easily obtainable for almost nothing. Recently, just two or three players were able to get ahold of wither skeletons, and ruined the market completely for a couple weeks. It would be even worse if they started spawning again, and would probably be a repeat of the mending crash, with it being sold for basically nothing. That is the entire reason Fix disabled villagers, because he felt that end game items should not be so cheap. I know that many feel that it is unfair that they can't get one. The only other solution I see is disabling mobs completely, but that would make the prices of beacons and such rise even more.

**Comment by yankees88888g** [comment]
Fix allowed mending obtainable by vote crate maybe a wither skeleton egg should be added there?
Also nothings worng with crashing the beacon market we need to keep prices low.

**Comment by Taffffy** [comment]
Absolutely not, beacon price dropped 150g when mob spawns were on for 2 days so this would make an endgame item worthless, as Gabeee stated. We don't need more items in the vote crates, unless the chance for an egg was 1 in 500 or 1 in 1000. Enough so that it would still be possible to obtain wither skeletons, but not crash the market necessarily.

**Comment by yankees88888g** [comment]
Bruh you want us to just bow down to you guys who already have. Wtf. Your right we dont need more items in vote crates we need wither skeletons to spawn.

**Comment by Taffffy** [comment]
I said add them as a 1/500 or 1/1000 drop, where it's possible to get them but won't break the economy. But you don't want the economy to be stable, you just want to get rich yourself while everyone else stays poor right?

Wither skeletons spawning would deal a huge blow to the server performance, there's a reason it was disabled. I'm sure Fix would enable all mob spawns if he could.

**Comment by yankees88888g** [comment]
You want to get rich while everyone stays poor I'm 99% sure you already have a wither skeleton and are unaffected except your profit margin.

**Comment by 10op10** [comment]
That is possibly the worst idea I’ve heard of, beacons are stupidly cheap because of 2 players crashing the beacon market, this will just make beacons worthless. Maybe add a beacon to the vote crates would be a better idea but still pointless as beacons are worth barely anything now. Stop bitching

**Comment by yankees88888g** [comment]
you benefit from keeping it as is though. quid pro quo.

**Comment by Takii-Takii** [comment]
That is just a horrible idea, beacons are supposed to be endgame item, not something that a new player could easily get with less than a week of voting.

**Comment by Cactusinapumpkin** [comment]
If you havnt noticed some people are at the level of endgame of the server. And some people really want beacons ofc beacons don’t just go away unless you burn them or a player data gets deleted. The supply and demand of the beacons is very messed up. People complain that beacons are endgame and still sell them at 150 if it was endgame then sell them for 500 or more, but people want to wait until the demand is much higher and supply is much lower to justify these prices. If you even sell a beacon the price goes down. So really it’s really a matter of getting rid of the surplus of beacons that already exist because of nether farms when they were operational at that time beacon prices were about 90.

**Comment by Cactusinapumpkin** [comment]
If you really want to fuck things up make adsorption pots not work for withers

**Comment by yankees88888g** [comment]
Funny everyone who's against this idea, already has wither skeletons, and benefits from keeping it this way. I like the idea of adding to bote crates if all current wither skeletons are removed.

**Comment by sage-blue** [comment]
> Funny everyone who's against this idea, already has wither skeletons, and benefits from keeping it this way. I like the idea of adding to bote crates if all current wither skeletons are removed.

so not only do you want to destroy the market, you also want to take wither skeletons away from players who already have them? you are utterly and completely retarded. cope seethe cope

**Comment by yankees88888g** [comment]
you have a monopoly and I think that wrong simple.

**Comment by yankees88888g** [comment]
This whole idea of an end game expensive. Is stupid because netherite sells for 8 gold.

**Comment by Chotobits** [comment]
> you benefit from keeping it as is though. quid pro quo.

Mate the problem is these guys want cheap beacons and so dose everyone else but if they get to low fix will just remove our ability to get beacons. Oh wait he did that yesterday.

**Comment by americanfrog** [comment]
The idea of a good economy means that people have very little and some people have tons. It keeps the market in a healthy state. Allowing major moneymakers open to everyone then the beacons will be worthless. If everyone can do that then the prices will drop and the people that wanted to make money from them never had a chance to make gold. **This is only going to help short term**. A long-term would be actually giving all the power to the top and making the market smaller.

**Comment by yankees88888g** [comment]
No, without it we are getting hurt long term.

**Comment by Takii-Takii** [comment]
@americanfrog ur absolutely right.
And also, @yankees88888g if you really want to have a wither skeleton, you better work hard for it, dont be lazy like you are right now.
On EarthMC you're not gonna get everything you want just by complaining and whining and being like: " but its so unfair, new players cant get as rich as players who have 50d playtime in such a short amount of time"

**Comment by yankees88888g** [comment]
A i'm not a new player.
b. im leveling fishing.
c. everyone who works like hell should be able to get a wither skeleton, right now that is not the case.

**Comment by Takii-Takii** [comment]
A: you joined in february 2021, you are a new player.
B: i dont understand why you're levelling fishing when you arent profiting from it in anyway.. its like if you expected to be rewarded a wither skeleton with that issue here.
C: You HAVE to work hard to gain a wither skeleton, the difference tho is that there is a certain way to obtain them which you clearly dont know of. 


Stop whining about some non-existent injustice because we, players that've been playing for months/years own more stuff than you and new players.


And to end this here, shaking chance was reduced to 2.00%, we dont know yet if it was intentional, but this makes farming mob loot with shaking almost unbearable/impossible.

**Comment by yankees88888g** [comment]
A I joined in February 2019.
B because I can.
C Yes I should work HARD to get one right now I cant no matter how hard I work.

**Comment by yankees88888g** [comment]
![Screenshot_20210416-195215_Discord](https://user-images.githubusercontent.com/47262788/115099843-75756e00-9eed-11eb-896b-6aaf707632cd.jpg)

**Comment by Takii-Takii** [comment]
![unknown-99](https://user-images.githubusercontent.com/74749146/115106784-9f9e4e80-9f34-11eb-910f-07458ff6ec64.png)

You litterally joined for not even a day and got player data wiped, you later logged on a day before august and didnt even lasted a week before you left again. You joined afterward only once in mid jan. 2020 before getting wiped again until february of this year.


You're litterally a new player.



Also you're barely lvl 170 fishing, i dont understand at all why ur farming it when its a waste of your time.


And finally, " you cant get one", then deal with it. I wont help you nor give you advices on how to get one.

**Comment by shirazmatas** [comment]
Please follow format and reopen a ticket following format

**Comment by yankees88888g** [comment]
I'm not a new player. Cope.
