### ISSUE TITLE
Remove Merchants

### ISSUE THREAD

**Issue by Conmqn** [EarthMC/Issue-Tracker#1355]
Okay the past few days I've noticed emc has added merchants in place of villagers which I was happy to hear but I now think it is probably down right the worst addition to emc EVER. Merchants don't sell mending 100% of the time only like 50%. So they choose some nations to "Test" them on which why wouldn't you add back beta to do the test before trying a new idea on the main server where it can fuck the player economy which has already with nations that don't have merchants there is less of a reason to go to said n spawn because they have no merchant which hinders nations that worked days on days for their trading centers just to be gone with a quick rash plan to bring mending back. Tell me why they choose these certain nations get an advertisement with merchants when others are left in the dust due to lack of planning and thought. I think Merchants should be removed due to the inconvenient  it brings to the player base but if i have a suggestion if you have merchants make it were you pay monthly for them so you can earn them and not just get a admin advantage with a single merchant.

**Comment by gabeeebaby** [comment]
The merchants are suppose to move around to crowded places, but there is no definition given on what that means, and it doesn't seem that any have moved around so far. Even then, they are located at the most traveled to n spawns (n list one nations). It doesn't seem to give an advantage to those nations in terms of trade, as people will go to an n spawn, check to see if the merchant has stock in whatever they want, then leave or go check a different one. As someone who has a shop located right next to a merchant, I haven't noticed any increase in 'sales'. 
   The economy is not destroyed, mending was never worth seventy gold because it was rare, it was just because people could. Anyone who bought at that price expecting to be able to sell it for more is just plain stupid. It's almost guaranteed that changes be made to it soon, but I don't see any major problems right now. Shiraz is also gonna close this ticket if you don't follow the format :trollface:

**Comment by Conmqn** [comment]
> The merchants are suppose to move around to crowded places, but there is no definition given on what that means, and it doesn't seem that any have moved around so far. Even then, they are located at the most traveled to n spawns (n list one nations). It doesn't seem to give an advantage to those nations in terms of trade, as people will go to an n spawn, check to see if the merchant has stock in whatever they want, then leave or go check a different one. As someone who has a shop located right next to a merchant, I haven't noticed any increase in 'sales'.
> The economy is not destroyed, mending was never worth seventy gold because it was rare, it was just because people could. Anyone who bought at that price expecting to be able to sell it for more is just plain stupid. It's almost guaranteed that changes be made to it soon, but I don't see any major problems right now. Shiraz is also gonna close this ticket if you don't follow the format :trollface:

lmao that is just a lie it never moves

**Comment by sage-blue** [comment]
sounds like coping
