### ISSUE TITLE
Queue small PVP arena

### ISSUE THREAD

**Issue by Tomekirys** [EarthMC/Issue-Tracker#1378]
So basically waiting in queue is very boring, but if staff add small arena (When you enter, some plugin gives you diamond armour and stone sword). It will make queue less boring and maybe attract new ppl to waiting in queue.

**Comment by Basically-Andrew** [comment]
**Here are a few suggestions to improve this and any future feature request:**

1. Follow the issues template format for feature requests.
2. Share the intended plugin and any important information regarding the plugin you've suggested.
3. Could you possibly estimate the support from players on this feature request?

**Here are my thoughts and issues on your feature request:**

Many aspects of the old hub, such as parkour, weren't included in the server's new hub world. While parkour and other fun aspects of the old hub made waiting less boring, many issues arose. Many players, instead of playing Towny, left the queue to attempt the parkour. I believe this took away from Fix's original intentions for the server. 

PvP is a much more popular game mode and would attract new players to the server, but they may, instead of queuing for Towny, play only ever in the hub. When the queue for Towny was created, players used to be able to player hunger games. I'm not exactly sure why it was removed, but I believe the issue was it took away from Fix's original intentions for the server. Issues may have also included the upkeep of an older plugin, server optimization issues, and other server structure issues.

A PvP plugin would be hard to maintain and take away from EarthMC's Towny.

**Comment by sage-blue** [comment]
your mother

**Comment by DasCodes** [comment]
The hub is already laggy as it is. We don't have any plan to add anything new to the hub currently.
