### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fwishys** [EarthMC/Issue-Tracker#1384]
### Server
Towny

### Describe the bug

The fireworks of the BRUH Crate damage you.

### To Reproduce

1. Get a BRUH Crate 
2. Open It
3. Firework Damage You

### Expected behavior

You take damage from fireworks

**Comment by Cactusinapumpkin** [comment]
This was removed on purpose

**Comment by Fwishys** [comment]
> This was removed on purpose

What do you mean? It's still there? Unless you mean it's supposed to damage you?

**Comment by jkmartindale** [comment]
Fireworks were removed from the regular gold crates but not the giant gold crates (and should've been removed from both).

Cactus got a bit confused because the **Expected behavior** section in the OP says taking damage from fireworks, when the expected behavior (what should ideally happen, not the bugged behavior) is that no fireworks show up.

**Comment by Warriorrrr** [comment]
Towny cancels firework damage in non-pvp areas, not taking damage from fireworks is not a major issue.
