### ISSUE TITLE
suggest to rule

### ISSUE THREAD

**Issue by sat0510** [EarthMC/Issue-Tracker#1399]
### Is your feature request related to a problem? Please describe.

Yes, it's relating.

### Describe the solution you'd like

My sugestation is to write rules in other languages.
Rule says that in global chat, we must use English, but now, many languages are existing in chat, especially many Japanese using Japanese in queue world. I am guessing a reason. That is that Japanese English education level is lower than other countries, as a result, many Japanese cannot understand rules. I think that to write rules in other languages, recruit multiple native people, and they write rules and check. This technique is also used by other famous Minecraft servers.
And, this text is about adding rules, I suggest to add rule. That is "If you talking for same country's people, please use English". Because, In global chat, same country's people using their language (for example, Japanese, Russian).
That's why, I suggest to write rules in other languages and add rule.

### Additional context

Nothing in particular.

**Comment by DasCodes** [comment]
We always welcome people who wants to translate for us.

**Comment by Toshimichi0915** [comment]
He/she obviously can't translate English to Japanese

**Comment by Toshimichi0915** [comment]
Here's my translation.
Note: I got tired in halfway

1. チート、バグの使用、そしてサブアカウントに関して

1. 1. チートクライアントと他の改造に関して
ゲームプレイに影響を与えるチートクライアント、マクロ及びその他の改造は禁止されています。このルールを破ったプレイヤーは永久にBANされ、決して解除されることはありません。

ただしいくつかの例外があります: 
* Optifineなどの、パフォーマンスに影響を与えるmod
* アーマーとポーションエフェクトを表示するmod
* Dynmapが提供する以上の情報をもたらさないミニマップmod
* 見た目だけのmod
* プリンター機能のないLitematica（Schematicaは許可されます）

1. 2. 故意にサーバーのルールを破ったプレイヤーから利益を得たり、ルールを破ったプレイヤーを手助けすることに対して
このページ上で書かれているいかなるルールを破ったプレイヤーから利益を得たり、ルール破りに参加したり、ルール破りを手助けすることはルールを破ったプレイヤーと同様の処罰を受けます。

1. 3. 技術的な問題やサーバーのバグについて
プレイヤーは明らかなサーバーのバグや、技術的な問題点から利益を得てはなりません。スタッフにバグや技術的な問題点を知らせずに利益を得た場合は永久にBANされます。

1. 4. サブアカウントに関して
サブアカウントは許可されません。一つだけアカウントを使えます。もしこのルールを故意に破った場合はサブアカウントはBANされ、メインアカウントは警告を受けます。もしメインアカウントを変更する場合にはスタッフにお知らせください。

1. 5. 故意にサーバーにラグを発生させたり、EarthMCのサービスに問題を起こすことに関して
私達が提供するサービスに対して問題を発生させたプレイヤーは永久にBANされます。

2. 振る舞いとチャットに関して

2. 1. テレポートトラップに関して
プレイヤーを特定の場所にテレポートさせるよう誘導して、そのプレイヤーを殺害したり閉じ込めることは許可されません。テレポートトラップは以前許可されていましたが、たくさんのプレイヤーがテレポートトラップを使用した結果、かなりのプレイヤーがテレポートプレイヤーを禁止することに賛成しました。

プレイヤーをむやみにテレポートさせないような通常のトラップや、戦争地帯に作成されたトラップに関しては、長時間（10分 - 15分かそれ以上）閉じ込められないようなものに関してのみ許可されます。

2. 2. プレイヤー/町/国からアイテムを盗んだり略奪することに関して
他者から盗んだり略奪する行為は許可されます。資産を保護するのは各プレイヤーの責任です。

2. 3. スパムに関して
3. スパムやチャットの流れを阻害するメッセージを送ること、すなわち似たようなメッセージを繰り返して送るようなことは禁止されています。

2. 4. 望まれない振る舞いに関して
以下の行動は許可は許可されません。
* おおっぴらに他者をいじめること
* 侮蔑的な単語を繰り返して使うこと
* 自傷行為を促すこと
* 少数民族や社会的マイノリティに対して暴力や明らかなヘイトスピーチを扇動すること
* 性別に対しておおっぴらに話すこと
振る舞いの有害性は個々に判断され、何が有害な振る舞いと認められるかに関してはスタッフが最終的な決定権を持ちます。このような振る舞いを繰り返すと警告、ミュート、最終的には永久BANに繋がります。

2. 5. 他者、町、そして国をなりすます行為に関して
他者、他者のニックネーム、町や国になりすまして利益を得ることは禁止されています。ルール違反者はなりすましをやめて元の適切な状態に戻るよう指導されます。もし被害が発生した場合は、スタッフはルール違反者をBANする場合があります。

2. 6. 放置時間に関して
15分以上放置することは禁止されています。もし自動キックを回避するような方法を使用した場合には、スタッフは行動を起こします。

2. 7. 個人情報を暴露することに関して
他者の個人情報や身元を明らかな許可を得ずに暴露することは固く禁止されています。個人情報は現実におけるプレイヤーの写真、電話番号、自宅の住所、ソーシャルネットワーク、学校/勤務場所、親族関係やIPアドレスが含まれますが、これらに限定されません。

2. 8. リンクを共有することに関して
3. 悪意のあるリンクは許可されません。これは例えばウイルスやIP Loggerが含まれます。このページに書かれているルールを破ることにつながるようなリンクに関しても同様に許可されません。これは例えばDiscordで他者にリンクを送ることも含まれます。

性的、非常に暴力的/刺激的なコンテンツへのリンクも禁止されています。他のリンクは許可されますが、スパムフィルターによって削除される可能性があります。

2. 9. 宣伝に関して
サーバーと直接の繋がりが無い限り、宣伝は禁止されています。

2. 10. アイテムやサービスを現実の通貨で売ることに関して
ゲーム内のアイテムやサービスを現実の通貨で売ることは禁止されています。買うことも同様です。

2. 11. グローバルチャットにおける言語に関して
グローバルチャットもしくは寄付者専用チャットで話す場合には、英語のみで話すようにしてください。タウンチャットやプレイベートメッセージといったプライベートチャットにおいては他の言語を使っても構いません。もしあなたの言語を話すオンラインのプレイヤーがほとんどいない場合には、グローバルチャットで英語以外を話しても構いません。

3. 荒らしに関して

3. 1. 領地と領地の周りを破壊することに関して
領地もしくはその周辺を荒らすことは許可されません。ルール違反者は警告を受け、被害はロールバックされます。このルールを複数回破った場合は永久BANされます。攻城戦イベント中に必要に応じてブロックを設置、破壊することは、紛争で必要な範囲で許可されます。

荒らしの例（ただしこれらに限定されない）：
* ラバキャスト - 溶岩と水を使って作られた山のような構造物
* 溶岩/水のカーテン - 空に溶岩/水を一列に並べて設置することで溶岩の壁を作ること
* TNTのクレーター
* 鶏やボートといったエンティティを領地の中もしくは周辺に大量にスポーンさせること

3. 2. 荒野の土地を破壊することに関して
荒野は誰にも保護されていない土地とTownyで定義されています。荒野を荒らす行為は、保護された土地の内部もしくはその周辺でない限り許可されます。しかしながら、大規模な地形の荒らし行為に関しては荒野においてもロールバックを申請することができます。

線路・氷の道路を破壊することは、それが２つの町をつないでいる場合は荒野においても禁止されています。これは線路だけに含まれず、その道を構成する全てのブロックが含まれます。

**Comment by Toshimichi0915** [comment]
guys i made full translation of the rule

**Comment by Chiko0120** [comment]
As for the Japanese chatting, as a Japanese myself, I feel bad.
However, please don't think that all Japanese people are like that.
Also, those who intentionally use Japanese in global chat are players who came in just out of curiosity, such as not wanting to read the rules.
In Japan, we call them "kids".
With the increase of such people, we understand that Japanese is frequently seen in the global chat.
However, please understand that there are some people who send it to the wrong place.
Therefore, I would like to see people who send more than one message in a row to be put under quarantine.
I would also like to see a request to return to the general chat, and to be able to send again after a certain period of time.
I don't want people who are following the rules, or who have tried to follow the rules and failed to do so, to be seen as generally bad.

Translated with www.DeepL.com/Translator (free version)

**Comment by AshleyLilyLawe** [comment]
I just came here because I wanted to translate the rules from English to Japanese, but it seems to have already been done.
But there are some things that could be improved.

# A. "に対して" "に関して" "について"
I think that it is preferable not to use the word "関して" or "対して" in the text of any rule.
If you look at the Japanese rules of Google, Microsoft and others, they don't write "関して", "対して" or "について".

**Examples** 
Microsoft: https://www.microsoft.com/ja-jp/servicesagreement/
Google: https://policies.google.com/terms?hl=ja

I feel that it is better to remove them. It seems redundant. 

# B. Missing words, translation errors and errors in Japanese
## 1.5
"""私達が提供するサービスに対して問題を発生させたプレイヤーは永久にBANされます。"""

””" Players intentionally causing harm to the services we provide may be permanently banned. ”””

The word "intentionally" is missing. The word "意図的に" or something like this should be added. This makes a big difference.

## 2.1
""" プレイヤーを特定の場所にテレポートさせるよう誘導して、そのプレイヤーを殺害したり閉じ込めることは許可されません。 ​"""

""" The act of tricking players into teleporting to a specific location or person just to kill or trap them is not allowed. """

"tricking" is translated as "誘導する". This Japanese word does not imply that what is not true should be made to seem true. It's better to simply say "騙す".  This makes it difficult to see why the exception in the following sentence could be an exception.

If you use ”殺害したり”, "閉じ込めること" should be changed to "閉じ込めたりすること".
”たり” should not be one in official texts.

## 3.1
""" 被害はロールバックされます。 """

""" and damage will be rolled back. """

"ロールバック" is IT jargon, at least in Japan; "ロールバック" should be rephrased as "復旧" or a word similar to it.

## 3.3
""" このような枝はよく他の町が拡張するのを阻害したり、全ての領域を保護することなく町の支配を拡大するために使われます。 """

""" These are protrusions which are often used to block the expansion of other towns or just artificially expand the area a town controls without the need to claim all of it. ​"""

If you use "阻害したり". "拡大する" should be changed to "拡大したりする".
”たり” should not be one in official texts. You could say "阻害することや......拡大することのために使われます".

## 4.1
""" もしこのルールが破られた場合は国名が変えられたり、ルールが連続して破られたりした場合には国が放棄される可能性があります。 """

""" Nation names may be changed by a staff member if the rule is not followed and may be disbanded if the rule is repeatedly broken. ​"""

This translated sentence is difficult to understand and contains the grammatical error of "たり". It should be rephrased as follows: 

”このルールに違反した場合には国名が運営により変更されることがあります。また、違反が繰り返される場合には国が解体させられることがあります。"

## 4.3
""" アカウントに関する以下の要素は、表現がきつかったり、性的であったり、差別的もしくは不適切なものであってはなりません。 """

""" The following account characteristics may not be explicit, sexual, racist or otherwise inappropriate: ​"""

There is a grammatical error of "たり". It may look like a small thing, but this error should always be corrected in official texts. It's better to rephrase it like this:

""" アカウントに関する以下の要素に、露骨な表現や性的な表現、差別的な表現、 その他の不適切な表現を含むことは禁止しています"""

## Comment
This is just one opinion, so I am open to further revision.
Please let me know if there is anything I can do to help with the translation.
