### ISSUE TITLE
Pvp arena in queue 

### ISSUE THREAD

**Issue by Tai00000** [EarthMC/Issue-Tracker#1417]
### Is your feature request related to a problem? Please describe.

the arena while queuing and how it needs a little spice to it

### Describe the solution you'd like

I have been thinking that the pvp in the arena is quite boring ad there should be more kits for example - like the witch / has potions as weapons and wooden sword and leather armour died purple to make it look it cooler or what ever colour! next kit could be like - enchanter half iron and half leather but it has prot 2 or 3 and a sharp 2 iron sword these are just some ideas and i would to see the arena get some more added like buildings/structures to entertain people  like a lava moat around where you can knock people in i am a premuim myself and normally leave queue to have fun with the normal queues for like some hours and one last thing a active helper/admin in queue i have noticed many people wanting mods on today i experienced 4 hackers within a hour and the people always want mods on!

### Additional context

thanks for reading :) tai000 (IGN) - tai#3654 (discord)

**Comment by Prismary** [comment]
I think more kits would generally be a good idea, it's just some effort to try and balance everything a bit to make sure no kit is overpowered. More structures may also be cool.   
As for people wanting mods on more often - unfortunately the lobby is a waste of time to efficiently moderate since we'd have to spend our time chilling there hours on end doing nothing except watching people fight when we could use that time to do tickets on the towny server or help users otherwise. If you'd like the players you encounter cheating to be punished, you could get into the habit of recording while you're fighting in the arena, if there's a hacker you can get them banned afterwards by reporting them and providing the evidence.

**Comment by CorruptedGreed** [comment]
This exists now
