### ISSUE TITLE
Standardize or remove Merchants

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#1423]
### Is your feature request related to a problem? Please describe.
Currently, Merchants locations are not only arbitrary but also completely senseless, Merchants are often put into nations with staff members which only increase the apparent bias, Nations like Argentina with like 10 res and 1k chunks get a Merchant yet nations in n list 1 in both townblocks and resident list don't? Ye this whole Merchant thing is I believe 1 of the worst ways to implement missing items and cool Merchants, esspecially when you consider nations with Merchants can enemy you and prevent access to such items, which gives them a monopoly for no reason which they didn't even earn.

### Describe the solution you'd like
Well I got a few ideas for the Merchants to be if not a cool fair thing at least better than the current state.

- Make a standard of sort for the traders, say a nation needs to be in n list 1 in res for a month, Pass a certain resident number, townblocks or have a high traffic (high use of /n spawn [Nation], prob the hardest to find, also gotta makes sure it's by unique people to prevent abuse).
- Make Merchants a "craftable" item, what do I mean by that? Make some sort of a mystery crate which is craftable and when opened similarly to vote crates or head crates and gives a random Merchant egg, which would all sell certain items, with legendaries giving custom items such as the Ark thingy. This could also be used as a chance to add in the new items from 1.17 to the server.
- Remove Merchants, I don't think the admins will listen but hey, it's still an option I guess?

### Additional context
As much as I dislike the current form of Merchants, I do think they have great potential, add a bit more style and liveliness to the nations they reside in and EMC as a whole, adding cool custom items and helping the economy by putting items into it and regulating it, but the current way just screams how bad it is, I think getting a Merchant is something every nation should inspire to get by work and dedication, setting it as a great goal and achievement for a nation, rather than just giving it to random nations, disregarding hundreds of players work.

**Comment by Fruitloopins** [comment]
I just wish unobtainable items were resigned to crafting recipes

**Comment by Prismary** [comment]
I also think merchants hold some potential, but have to agree that the way they're obtained or generally function needs to be revised. However, some currently unobtainable items that aren't too nieche should definetly be moved to custom crafting recipes anyway.

**Comment by Punkypal** [comment]
Can merchants at least be updated to offer a few more things? Everyday they selling bells and saddles for 64 gold and other useless and crazy priced trades, but when they offer string, they will literally only give 2 items and that's it, and yet never sponge, or slime balls, or clay, or spider eyes, or ghast tears, or rabbit's foot, or beacons, or end crystals, or any number of hard to get items. Or even sell monster heads sometimes too! A little more variety sure seems appropriate, 

And any way to make their price vary? They always have exactly the same offers at the same prices. That's pretty boring. Merchants need a LOT of improving I'd say. As they are now is seems pretty half-assed. Like they were introduced with intent to make them do more, and they the staff just forgot to ever follow up or didn't care.

There also should be made public a set of criteria for a nation spawn with a shop to meet to be able to get a merchant. Right now there are nations that have merchants and they don't even have a leader that's been online for days. Requests to ally get ignored. If nations can't even get their residents to these merchants, it seems bad that they have them when much more active and large shops (such as Saskatchewan) dont have a merchant and are being denied one.

**Comment by Basically-Andrew** [comment]
With mob spawns, turned back on it isn't difficult to get the mob drops you mentioned including Beacons with wither skelton spawning. Many drops can also easily be harvested with mcmmo excavation.

**Comment by AndrewCheedle** [comment]
I agree with you on dead nations having merchants. There seems to be a bit favourism since some of the nations dont even have shops. The craftable egg solution seems to be the best option to me, since it's a luxury to get merchants people should work for it. Maybe it can be crafted by gold since it guarantees your nation to get visited by players and promote your shops.

I agree with Punkypal with the problem of useless trades and variety. The saddle trade for 64g is extremely overpriced and useless. The useless trades should be removed and replaced by new ones. Since mobs are disabled and shaking is gone now they can also trade for mob items as well.

**Comment by QJWIN** [comment]
`Currently, Merchants locations are not only arbitrary but also completely senseless, Merchants are often put into nations with staff members which only increase the apparent bias, Nations like Argentina with like 10 res and 1k chunks get a Merchant yet nations in n list 1 in both townblocks and resident list don't? `

Well that not because you are new player you have to juge  so badly ...  since you  ignoring  why ...
And more when you talk about dead nation ...

First of all fix helped by poppykai if im correct have implement this merchant to let ppl get non obteinable item and share more 
items like the mystery crate you can get for gold and a player head, totem or item like that ...

They are implemented in madagascar ONLY with 4 merchant for testing during week after that and in order  to  wait the  implementation  in the towny plugin cuz its suppose  to be placable by the nation king ... they have add merchant ABSOLULY NOT in  MOD town witch is totaly wrong but placed in the most visited shop ATM , and in order to let everyone get access to it
 they placed in like 7 or 8 town to prevent enemy problem ...

Time  have  past and you right in one point that should be done or at least in DEV but no one seems to care of merchant
but since they change the network and make test to get more player we have to wait a DEV who wanna wrote some ligne of code specialy when the  1.17 item was here like spore blossom, dripleaf, ...

**Comment by CorruptedGreed** [comment]
Reference #1386
