### ISSUE TITLE
[Bug] Shaking mob's not working

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#1468]
### Server

Towny

### Describe the bug

The bug apear when you wanna shake a mob with a fishing rod

### To Reproduce

Try to shake the mob don't works

### Expected behavior

I expect you to put shaking mob back because, put mob on have no sens if we cannot shake them ...

**Comment by AndrewCheedle** [comment]
This is not a big, shaking was disabled on purpose so people actually get out of their underground caves and dont trap mobs instead of fighting them. With mobs spawning you now have to fight them instead of shaking them.

**Comment by QJWIN** [comment]
when you trigger a button attached to a piston
the normal execution is a contraption of the piston
who get in and out in 1 sec or a bit less

ok  and what shaking mob give to you as loot ?
creeper head 
skeletons head

so who care about you comment who have no sens since you ignoring what is the reward of that skill ...
who gonna shake a spider for a spider eyes when kill 20 of them is more faster ?
no  one kill mob like you say ... 
shaking mob is the ONLY way to get  head from creeper and skeleton so the reson you invoke for disabling shaking have no sens

cuz its faster to kill them since they spawn ...

**Comment by keijodputt** [comment]
Disabling shaking has been a very controversial idea. Just because mobs do spawn you've killed players that grinded fishing/alchemy for a year or more. Grinding these skills takes a lot of time online from players that usually don't go out of claims much, so maps don't get overloaded, some mob heads can't be obtained in any other way (no rain/thunderstorm, creepers don't get 'charged'), and this is simply forcing people to do things 'your way'.

With that mindset, you should also disable excavation, because all the loot it provides can be obtained in the Nether (glowstone dust, quartz crystals, netherrack), killing mobs (bones/gunpowder), or harvesting (mushrooms).
Why have McMMo if it's crippled to the point that mostly every skill is disabled/useless?
Just my 2c.
-keijo

**Comment by AndrewCheedle** [comment]
> Disabling shaking has been a very controversial idea. Just because mobs do spawn you've killed players that grinded fishing/alchemy for a year or more. Grinding these skills takes a lot of time online from players that usually don't go out of claims much, so maps don't get overloaded, some mob heads can't be obtained in any other way (no rain/thunderstorm, creepers don't get 'charged'), and this is simply forcing people to do things 'your way'.
> 
> With that mindset, you should also disable excavation, because all the loot it provides can be obtained in the Nether (glowstone dust, quartz crystals, netherrack), killing mobs (bones/gunpowder), or harvesting (mushrooms). Why have McMMo if it's crippled to the point that mostly every skill is disabled/useless? Just my 2c. -keijo

Your point is good. I do understand grinding is being heavily nerfed everytime an update happens. The best solution I think would be enabling shaking, and making it easier to get items with shaking. Right now shaking requires you to have a mob, have a mending God fishing rod, xp bottles and at least 250 fishing level. This is a high bar and something most emc players cant even have access to. If fix does see this I dont think neither the mobs nor shaking should be nerfed. My previous statement was about players who luckily got a mob and was using it underground, with no risk. Now I remember that a lot of grinding happens before you can shake so I guess it's alright.

**Comment by Warriorrrr** [comment]
Shaking was disabled shortly after mob spawns were enabled
