### ISSUE TITLE
[Bug] Can't Toggle PvP while Outsider is in Plot

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1498]
### Server

Towny

### Describe the bug

PvP can't be toggled in a plot if an outsider is in the plot.

### To Reproduce

Toggle PvP in a plot with an outsider in it.

### Expected behavior

PvP is enabled with or without outsiders in the plot.

### Screenshots

![image](https://user-images.githubusercontent.com/59465284/166852225-4fc010a5-2e77-47ce-aa2e-70aa0eaebd37.png)

**Comment by Nexus9594** [comment]
I believe it's to prevent trapping someone on your plot and killing them as that goes against server rule 2.1 found here: https://earthmc.net/rules

**Comment by Basically-Andrew** [comment]
That's not actually true, Nexus9694, Rule 2.1 protects against TELEPORT traps and killing. Furthermore, the server already has a keep inventory on in a 3x3 chunk area of any teleport locations. I should be able to toggle pvp anywhere in my plots no matter if there is an outsider or not.

**Comment by Nexus9594** [comment]
> 
Yes, is a way. It is still against the rules to bring people into a plot that is claimed and then turn pvp on, they wouldn't have a escape. Some months ago lots of people on EMC got killed including myself by going into a shop, they wait for you to take your gold out then they kill you and you have no escape, or it wasn't a shop, that is there so that cant happen. The only reason i could see them letting you turn pvp on if outsiders are in your plot is if there is an outlaw in your plots. And yes, you could just be trying to enable but someone is in your plot, you don't want to hurt them but that element of the game is there to protect something like luring and plot killing from happening.

**Comment by Basically-Andrew** [comment]
It's not in the rules, but I understand your stance. But this heavily restricts legal trapping and killing. I like the suggestion of allowing pvp to be toggled in plots with outlaws.

**Comment by Nexus9594** [comment]
Same, I do I see where you are coming from on this. In the end its up to the staff but I stick with the suggestion of being able to toggle pvp if outlaws in there as  they have a warning so its partly their fault if they decide to stay in the town.

**Comment by Basically-Andrew** [comment]
I really like the suggestion, but if we're going to make outlaw an actual thing to use on EarthMC, then outlaws shouldn't be able to teleport in outlawed towns.

**Comment by Nexus9594** [comment]
That's a fair point. Like enemy nations you cant teleport there.  Maybe an option to toggle outlaw teleporting in your town/nation?

**Comment by RAWRyoutube** [comment]
>That's not actually true, Nexus9694, Rule 2.1 protects against TELEPORT traps and killing.

Before the rule was modified on the 13th, 2.1 protected against both teleport and luring traps within a certain radius, which has varied over time (I have had tickets denied being 1 block away from the trap and accepted 2 chunks away in different times). Both instances were luring traps. I cannot find a staff consensus on what the rule means since the withdrawal, there are conflicting definitions within the staff team.

> I should be able to toggle pvp anywhere in my plots no matter if there is an outsider or not.

This point is only for toggling pvp when outsiders are inside of said plot, which implies intent to kill by using the anti-claimhide plugin. Why this method?

>I like the suggestion of allowing pvp to be toggled in plots with outlaws.

If the town owner has the ability to add outlaws to the town and toggle pvp on said outlaw while in one of the town's plots, it is pointless. The town owner would be able to obtain the same result (the murder of the outlaw) by a delay of a few seconds (typing in the /t outlaw add command). There would only be validity to this suggestion if adding outlaws to a town were severely reduced.
This suggestion also appears to wish to increase the powers of trapping and nothing else. There are no other reasons for this suggestion other than trapping (for example, if one wanted to make an arena, they can make one without having outsiders inside it). **It would be a much greater favor for the server if players did not have to worry about other mayors scamming them in a moment's notice than otherwise.**

**Comment by docwhomc** [comment]
The purpose is to prevent mayors from changing plot perms in order to kill people. There doesn't need to be a rule against changing plot perms to kill an outsider in the plot if it can't be done in the first place.

**Comment by CorruptedGreed** [comment]
This is intentionally disabled, similar to how you cannot enable pvp overall in towns when outsiders are present.
