### ISSUE TITLE
Larger Nation Bonus

### ISSUE THREAD

**Issue by da-Nek** [EarthMC/Issue-Tracker#1507]
### Is your feature request related to a problem? Please describe.

Inviting people is not easy, especially when everybody wants their own town. Hence claiming areas around 200 chunks is quite difficult and requires a lot of time which not everybody has. 
Changing the nation bonus would definetly stimulate the growth of towns and make the server more casual.
Of course inviting people is a part of the game. However, with the queue being so long and not many new players wanting to join
a town and instead opting for creating their own. I think it's only rational to increase the nation bonus.

### Describe the solution you'd like

Make the nationbonus:
10 players - 10
20 players - 15
25 players - 30
50 players - 60
60 players - 70
100 players - 80

(Anything more than 30 would be nice)

**Comment by Basically-Andrew** [comment]
Fix has already stated the max nation bonus will never be changing on Aurora.

**Comment by Warriorrrr** [comment]
An upper limit of 80 sounds fair, though for the resident requirements we could probably use the default ones but doubled.

**Comment by Warriorrrr** [comment]
Going to use the following values for now:
```
Resident Count | Nation Bonus
0 | 0
20 | 10
40 | 30
60 | 50
80 | 60
120 | 80
```
I'm open to any feedback regarding this, should hopefully not be too high or low for most.

**Comment by Basically-Andrew** [comment]
Nation Bonus is not something to quickly change and test with. Any increase will have to stay the same to keep it fair for future towns on Aurora. I do not support this.

**Comment by Basically-Andrew** [comment]
I would love to see a gradual increase in nation bonus after the summer, but it is currently pretty easy to recruit new players when there are around 20 townless players when I'm on. Some do only want to make a town, but the same amount want to join a nation and build houses before settling in that nation with their own town. The time is not now.

**Comment by FixTheAdmin** [comment]
We absolutely can and will balance things like nation bonus. Instantly getting a 140 claims bonus was not sustainable, it allowed single player towns to squat large parts of land with next to nothing built on it. Land squatting is a huge issue for a server with limited space. It favors inactive towns at the expense of gameplay experience for new players. We should be awarding claim bonus for number of residents in a town and nation since they have valid need for more land and expansion. The new system awards larger nation larger bonus for their hard work recruiting players. It also rewards large towns for the same reasons.
