### ISSUE TITLE
[Bug] Councilors can Kick Other Councilors

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1523]
### Server

Aurora

### Describe the bug

Councilors don't have permission levels to demote other councilors, however, have the perms to kick other councilors from the town. 

### To Reproduce

1. /t rank remove otherCouncilor Councillor

2. /t kick otherCouncilor

### Expected behavior

Councilors shouldn't be able to remove other councilors.

### Screenshots

![image](https://user-images.githubusercontent.com/59465284/171079377-a8265dbb-8df7-40eb-a67e-4f7c8d4a4095.png)

**Comment by docwhomc** [comment]
It a Towny bug, not an EarthMC bug.

Various routines in Towny were written under the fundamentally flawed assumption that the default configuration for roles will be used (which kinda defeats the purpose of making them configurable). Specifically, Towny assumes that the only "configurable" role that shouldn't be kickable is "assistant". Since Towny is hard coded based on the name of the role and EarthMC renamed this role to "councilor", a bunch of stuff breaks. This used to be worce: when a mayor was removed due to inactivity, the town would be passed to a random player, rather than to the highest ranking player still in the town.
