### ISSUE TITLE
[Feature] Enable outposts

### ISSUE THREAD

**Issue by Potoole99** [EarthMC/Issue-Tracker#153]
I think that nations should be allowed 1-2 outposts. It allows reasonable travel times for across the world, making trade possible for isolated nations. It also connects the world.

**Comment by sharkfynn1012** [comment]
If outposts are kept disabled for the sake of realism, could we at least get outposts in the nether/end? as to get to certain locations in those places can be challenging. If we want realism then that would be a no, but if we want to be that realistic why don't we just remove then end and the nether all together? :syn:

**Comment by MSatrokrm** [comment]
I'd agree on outposts being enabled on the end, since it'd be hard to keep going back and forth by having to constantly travel to the overworld portal to the end. The end is also infinite, no harm to outposts being enabled there.

**Comment by MSatrokrm** [comment]
"The concern with outposts in other dimensions is that players may use those locations as vaults to store all of their valuable items, which would essentially be un-raidable. Raids aren't a particularly large part of this server or towny in general, however."

Players can simply put all of their valuables inside end chests, which no one else has access to. 

"The secondary concern is that we don't want players making builds/living in the End or Nether, and if they can claim they will make builds. We want the bulk of the action of the map to take place on the Earth Map, as is our theme." 

Why would anyone build in the nether if Karl has said that the nether will reset every now and then? I get wanting to have all players build on the Earth Map, however, most players just outpost on the end just to get around much quicker and to save spots where end cities are. Building on the end, or anywhere else that's not on the Earth Map would be pointless since no one else would be able to teleport to it, except you and your town citizens. 

And even if outposts aren't enabled on the end, you won't be able to stop players from building structures. But, lets' be honest, they aren't going to build proper houses and skyscrapers.

Everyone is already building on the Earth Map, there's no reason to worry about not being able to see cobble-stone structures on the end.

**Comment by Arganog** [comment]
Regular resets of the Nether (and End if it is added) would be a good idea

I do not know if towny gives us the option to only allow outposts in other dimensions, but if so allowing towns to have 2 outposts (presumably one for the nether and one for the end) would be convenient

**Comment by KarlOfDuty** [comment]
As I said in the other issue, we will not re-enable outposts at this time.
