### ISSUE TITLE
[Feature] Add virtual currency which may be gained by claiming gold

### ISSUE THREAD

**Issue by Tema0** [EarthMC/Issue-Tracker#1535]
### Is your feature request related to a problem? Please describe.

Its impossible to sell stuff through chestshops for fractional amounts of gold like 0.1. Which makes it pretty hard and sometimes impossible to sell some kinds of stuff through chestshops. Also its uncomfortable that player has to bring gold in their inventory, so it makes every shop filled by ender chests and trade killing so profitable.

### Describe the solution you'd like

Solution is make virtual currency which will be related to gold 1:1, player will just has to get gold type something like /gold claim and after that gold from their hand will despawn and their virtual account recieve similar amount of coins. This is not a new idea, this is not even a just imagination, ltrly this plugin was released in another towny earth minecraft server - new earth (this is not advertising, that server is almost dead)

**Comment by RAWRyoutube** [comment]
golden nuggets

**Comment by Warriorrrr** [comment]
Instead of allowing players to sell stuff for fractions it would probably be easier to allow players to sell more than a stack at once in a shop chest.

**Comment by AndrewCheedle** [comment]
Fix said several times he is against bulk amounts in chest shops because it lowers prices significantly . Players need to use trade command or workarounds in chest shops to buy bulk amounts. I know that some players already have chest shops you can sell bulk amounts to with some smart ways to get around the system. It doesnt need a new feature right now
