### ISSUE TITLE
[Mechanic] Enable Firespread in our own Towns

### ISSUE THREAD

**Issue by Seranil** [EarthMC/Issue-Tracker#156]
Hey, the trees are really annoying to cut down, could you let us enable firespread in our towns? As far as I'm aware we cannot right now but correct me if I'm wrong.

**Comment by MSatrokrm** [comment]
Ye, fire spreads in town claims but not in the wilderness is reasonable.

I believe that fire spread was turned off in order to save the trees from ending up like the ones on California; burned to smithereens. 

The trees are annoying, and being able to burn down the ones inside town claims would be awesome.

**Comment by Arganog** [comment]
Cue players accidentally burning down their towns


The ability to burn down these trees would be more helpful than not, however
It would also be helpful if it was possible to fix mcmmo tree-feller so we could more easily remove them

**Comment by FurdenFuhrer** [comment]
I want to be able to turn on fire spread within my town
Towns already have it auto disabled so the player would need to enable it

**Comment by xCptSpiffyx** [comment]
If people burn down their towns then that's their own mistake. If there are concerns about internal greif by residents then it can be easy to do a rollback can't it? Also would be good for adding history to the server The Great Fire of London 1966 anyone?

**Comment by BowShot118** [comment]
Any update on this?

**Comment by KarlOfDuty** [comment]
It is not possible, you can always put it on the towny repo though.
