### ISSUE TITLE
We need /t jail enabled.

### ISSUE THREAD

**Issue by ThatRagingKid7** [EarthMC/Issue-Tracker#1569]
### Is your feature request related to a problem? Please describe.

I'm trying to make a labor camp, but I can't find a way to trap residents inside the camp, and make them unable to escape by tping out.

### Describe the solution you'd like

We should enable /t jail to jail players.

**Comment by docwhomc** [comment]
This isn't going to happen. Towny jails are disabled because they violated Rule 2.1. The reason rule 2.1 was removed is that the server has safeguards in place to prevent players from trapping other players.

**Comment by docwhomc** [comment]
Serting asside the ethical issues for a moment, even if towny jail were enabled, I don't see what labor your prisoners would be able to do since they wouldn't have perms to do much of anything.

**Comment by docwhomc** [comment]
Even if you were allowed to trap players in your labor camp and had some form of labor for them to do, what reason would the players have to perform labor for you instead of just logging out and not coming back?

I point this out because the issue if players logging out and never coming back is why trapping them in such a manner isn't allowed.

**Comment by ThatRagingKid7** [comment]
They can choose if they will be kicked out from the town/nation or spend some time in the labor camp.

**Comment by docwhomc** [comment]
Why would they want to remain members of a town/nation that puts them in a labor camp?
What's wrong with you that you even want to do this or would even suggest this as a joke?

**Comment by ThatRagingKid7** [comment]
just thought it would be fun, closing issue
