### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Zgrift123** [EarthMC/Issue-Tracker#1572]
### Server

Aurora

### Describe the bug

I was building in the nether a highway, and i fell bc the server removed the block under me, i lost all the stuff, my full protection IV in all armor, unbreaking III in pants, Depth Strider III in the boots, my god sword.
You don't have to return my stuff back by force, but pls fix this fk bug.

### To Reproduce

Building a bridge with Shift+A+W, the classic style of a bridge.

### Expected behavior

That i finish the bridge.

**Comment by docwhomc** [comment]
This doesn't seem like enough information to trouble shoot the bug, assuming ther is in fact a bug to blame in this scenario. Do you have any additional information about this? Have you encountered it any other time?

**Comment by Warriorrrr** [comment]
This isn't a bug that can be fixed by us, since it's a client sided issue. In order to make the game feel more responsive, the client often "predicts" block placements instead of waiting on the server to send the block update. The issue here was likely that, plus some latency that caused you to fall.
