### ISSUE TITLE
[Feature] Player Warps

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1627]
### Is your feature request related to a problem? Please describe.

If you want a successful shop, players should be able to teleport to it. The only practical way are nation spawns, which cost 1,024 gold.

### Describe the solution you'd like

Add player warps which allow people to go to your shops without having to make a new nation.

### Additional context

There are a few plugins for this.

**Comment by Aylywyn** [comment]
https://earthmc.net/docs/how-to-teleport
"EarthMC does not support player-to-player teleportation.

This system ensures that the nation's capital becomes a center point in the nation just the way capitals are in real life. The capital will turn into a trade hub since nation residents and residents of allied nations have direct access. This system also allows nation kings to engage in trade wars as they're able to restrict their nation residents from accessing enemy nations' markets."

The server probably already has MORE teleportation then Fix would like.  He'd reduce it further but players would push back too hard.

**Comment by PlaceReporter99** [comment]
> https://earthmc.net/docs/how-to-teleport "EarthMC does not support player-to-player teleportation.
> 
> This system ensures that the nation's capital becomes a center point in the nation just the way capitals are in real life. The capital will turn into a trade hub since nation residents and residents of allied nations have direct access. This system also allows nation kings to engage in trade wars as they're able to restrict their nation residents from accessing enemy nations' markets."
> 
> The server probably already has MORE teleportation then Fix would like. He'd reduce it further but players would push back too hard.

This is not player to player teleportation.

**Comment by RAWRyoutube** [comment]
> This is not player to player teleportation.
Successful shops are supposed to be at nation spawns. That’s intentional.

**Comment by Aylywyn** [comment]
Read the second paragraph...  

ANY additional teleportation will NOT be added.  Like I said, fix would likely REMOVE more tp'ing if he thought he could.

**Comment by CorruptedGreed** [comment]
We are looking to address this soon in a way which would incorporate purchasing a spawn/gold sink related feature.
