### ISSUE TITLE
About /seen

### ISSUE THREAD

**Issue by LinJw970** [EarthMC/Issue-Tracker#1637]
### Is your feature request related to a problem? Please describe.

I'm wondering if /seen database are broken, sometimes I can't find exist player. Also, I recommend /seen can see if this player got banned info.

### Describe the solution you'd like

Make sure the database is fine and maybe add ban info into /seen.

**Comment by Warriorrrr** [comment]
The command isn't able to find players sometimes because it only works for players who are online or whose data is loaded by the plugin, I took a look at it earlier and couldn't figure out whether it's designed to be like that or accidental.
I can probably create an issue on essentials' issue tracker so that one of them can take a look at it.

As for adding banned status, even if we wanted to add it we wouldn't be able to do so, since we use a different plugin for bans.
