### ISSUE TITLE
Local Chat

### ISSUE THREAD

**Issue by MonarchTai** [EarthMC/Issue-Tracker#1643]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when if you have multiple people around you, and it's difficult to use what chat to talk to them in the game. (If you're not using Discord). New players don't understand different things, and a local chat would help out as nearby players can them communicate with them with them seeing its someone nearby talking to them. This would also help with events.

### Describe the solution you'd like

Add /L and /Local. Local chats used to talk to players within a 0- 250 block radius from you. When you send a message in this chat, only the people in that radius of you can see the messages. 

### Additional context

Lots of towny servers use this, so far from mod responses, seems like most people would like this implemented.

**Comment by Colt44Magnum** [comment]
I love this idea and will share it around to Discord so people can come here and comment or add a reaction to show their support!

**Comment by Aylywyn** [comment]
Just a copy and paste of a #general chat from just after New Year's.  My side only kind of for privacy.  I'll expand if needed later.
-----
Hmm, if ways to pay to _potentially_ be annoying aren't out, give Premium a, say,  128 block /localchat .  The ability to shout at strangers and rant to crowds would convince a few to spend money.  And likely has legit uses, too :-) .  Enough that I'd support this actually. 
-----
I don't think it should be for everyone.  Either you'd have the option to mute the channel and most would so it would be pointless.  Or you couldn't mute it and it would be annoying spam.  At least limiting it to Premium (like I'm sure the theory behind Discord to in-game chat is...) gives you the ability to threaten someone's Premium status (or to hope that Premium users are naturally inclined to be more respectful because of that status...) to prevent misuse. 
-----
On top of that, like Nation colours being Premium for Kings, it gives event runners a huge incentive to get Premium.
-----
