### ISSUE TITLE
Overclaim Mechanic Discussion

### ISSUE THREAD

**Issue by CorruptedGreed** [EarthMC/Issue-Tracker#1662]
Use this forum to discuss the proposed overclaim feature, for all EarthMC-related purposes/implementation.

For context, the Towny GitHub issue: https://github.com/TownyAdvanced/Towny/issues/6564 (anything EMC-related here will be muted due to being irrelevant to the broader Towny plugin, please use this issue to discuss for our server)

**Comment by Haptror** [comment]
what is even an overclaim broski

**Comment by Haptror** [comment]
> > what is even an overclaim broski
> 
> imagine if you just read the text

this idea is trashy because u can just overclaim the entire country and start a monopoly

**Comment by 32Vache** [comment]
Maybe consider people have things to do other than playing 20 hours a day to get enough residents to maintain a large town.

**Comment by Haptror** [comment]
> Maybe consider people have things to do other than playing 20 hours a day to get enough residents to maintain a large town.

*most* people

**Comment by Thanamossss** [comment]
Prehaps balance the daily / weekly overclaiming capacity. I suggest that instead of having a daily overclaiming capacity, it should be a weekly capacity to let the town who's getting overclaim enough time to counter attack and make it more balanced

**Comment by LlmDl** [comment]
Remember you only get overclaimed until you're not overclaimed anymore. 

If you were in a situation where you can be overclaimed into next-to-nothing, your town was egregiously overclaimed anyways.

**Comment by 32Vache** [comment]
Maybe chunk limit per resident could be increased to 10 instead of 8, if everyone starts recruiting against overclaiming there will be simply not enough townless for everybody, especially since nation bonus has been nerfed.

**Comment by Haptror** [comment]
> Prehaps balance the daily / weekly overclaiming capacity. I suggest that instead of having a daily overclaiming capacity, it should be a weekly capacity to let the town who's getting overclaim enough time to counter attack and make it more balanced

some towns cant counter attack because nobody funds them

**Comment by 1T3Y** [comment]
While I think that there is an issue regarding inactive yet territorially-large towns, I believe an overclaiming feature requires something else to complement it else the feature becomes terrible.

I propose that towns can be divided into districts which each have sub-mayors; all towns start as a single district but a new district could be created with a command like "/t district new [name of district]" and land could be moved from one district to another with a command like "/plot set district [name of district]." The sub-mayor of a district could receive permissions within that district alone.

The reason I suggest adding town districts is because the town mayor could then release a district by spending gold and typing a command like "/t district release [name of district]," turning that district into a town of its own with the sub-mayor of the released district becoming the mayor of the new town. I think this complements an overclaiming feature well because large towns that could never sustainably keep sufficient populations, especially when competing against dozens of other large towns, and dozens of smaller towns as well, for the same small pool of new players, could instead fragment into many smaller towns which are individually small enough to avoid losing land while still collectively working together. It's an interesting idea that I don't think would be too difficult to implement (although I know little about coding).

**Comment by LlmDl** [comment]
Who's going to code town sub-districts? Explain why you wouldn't just use multiple towns, or why your town wouldn't own less land to being with, or how you would make sure that the developer of Towny is actually making a living wage to support your idea.

**Comment by 1T3Y** [comment]
I don't think adding districts would be astronomically difficult unlike what you seem to be suggesting. We already have different plot types such as inns, shops, arenas, and more, so much of the functionality of a district could easily be borrowed from those (it could be the same "/plot set" command, for example). Again, I don't code much, but districts seem much easier to implement than the overclaiming feature that this whole discussion is about.

**Comment by LlmDl** [comment]
Overclaiming has already been written, in just over 200 lines: https://github.com/TownyAdvanced/Towny/pull/6565

**Comment by Ultraokasan** [comment]
I have a proposal for before overclaiming is implemented. It is a solution so that new players have enought land to create their towns. I propose tightening the rules for players who cheat and to track the gold earned with hacks and alts,  because one way to end huge towns would be to delete the chunks that have been obtained by cheating.

With overclaiming players who cheat will continue to do so, since they know how to avoid being discovered and we will have the same problem of lack of space for new players.

**Comment by Craig1224** [comment]
Here are some suggestions that I thought of that may make this update better:
1. An age on towns that want to overclaim, which essentially means that a town must be X amount of days old (let's say 14) to start to overclaim. This will prevent towns from being destroyed overnight and will allow mayors to have X amount of days to recruit players to prevent this. However, it can also discourage players who make these towns purely to overclaim another for reasons that are of war and not for just the land.
2. Adding an overclaim limit per day, let's say that a town could only overclaim 8 chunks per day. This will limit a town from being ramsacked in minutes because someone just went through and claimed everything in a matter of minutes. If a town really wants some land, they can have it gradually instead of all at once.
3. A cap on the cost of overclaimed chunks. Currently, the proposed cost is 1g/8 chunks. After you get to 800 chunks, the price per day is 100g and that's just way too much for many people. I think a good cap could be 100 gold so that any town above this amount of overclaimed chunks would only have to pay 100 gold.

**Comment by Haptror** [comment]
wouldn't need to do that if you actually played the game normally

**Comment by LlmDl** [comment]
People keep assuming that overclaiming will wipe a town off the map, that would only happen if the town had 0 residents, and the  homeblock-claiming-protection-radius wasn't used.

You only get your claims taken from you, up until you're no longer overclaimed.

**Comment by Player9880** [comment]
Don’t add overclaiming, it does not reflect real life and will completely destroy 940 chunk towns
