### ISSUE TITLE
[Bug] No Gold Crates After Voting Offline

### ISSUE THREAD

**Issue by OzzyKP1** [EarthMC/Issue-Tracker#1708]
### Server

Aurora

### Describe the bug

I've been voting offline for weeks, but when I logged in to the game today and used /cr claim I didn't have any gold crates.  I see that this issue has been reported before and they were told that this was intentional and you can only get the gold crates from voting while logged in.  

The guide, however, says this:

> You can vote right now by visiting the voting sites [here](https://minecraftservers.org/server/383495) and [here](https://servers-minecraft.net/server-earthmc.1042/vote). You will receive a gold crate with a random award of up to 64 gold ingots after successfully voting for the server. Keep in mind that you are able to vote without being online. Your award will be given to you next time you sign in and can be claimed with /cr claim.

If this isn't a bug that can be fixed (or it has been decided not to fix it) then please, please update the guide so more people aren't misled like I was.

### To Reproduce

Vote while offline, try to claim your gold crates later.

### Expected behavior

Should get a gold crate for each time I vote.

**Comment by Aylywyn** [comment]
Vote Crates expire after 24 hours of voting offline.  If you want to AFK stockpile them,  you have to vote twice, then log in for at least a couple seconds (listen for the happy noise...).   They will stack up to a point but the ID changes randomly.  So make sure you have Inventory space because (unlike your quote) small Vote Crates do NOT go to /cr claim (or didn't, I haven't tested it since the new plugin but I still 80% they don't).

**Comment by OzzyKP1** [comment]
That needs to be added to [this page](https://earthmc.net/docs/economy), and perhaps elsewhere where voting is mentioned.

**Comment by CorruptedGreed** [comment]
Addressed in replies
