### ISSUE TITLE
[Feature] Mob eggs

### ISSUE THREAD

**Issue by Colt44Magnum** [EarthMC/Issue-Tracker#1711]
### Is your feature request related to a problem? Please describe.

The issue is I have to make mob farms in order to get mobs for players to fight. I'm not looking to make a grinder but have Zombies and Skeletons walking around and area. 

### Describe the solution you'd like

I would like Traveling Merchants to have a chance to trade mob eggs for emeralds. This would allow more freedom and creativity on the server in using mobs.

**Comment by Veyronity** [comment]
I dont see how having a mob farm allows more freedom and creativity, only thing that will do is drop mob drop prices and those who built manual farms will be fucked cuz noone will buy their expensive mob drops anymore, thats not fair. Also that will just increase demand for wandering traders, and make a black market for them as mob farms need at least 30 eggs to function.
Zombies may not be such a bad idea, but skeletons give arrows and bones, spiders give eyes and string, creepers give gunpowder, and enderman give pearls. All of which are expensive currently, since current farms without spawners  have bad rates.

**Comment by Colt44Magnum** [comment]
It's not about having a mob farm, its more about not needing to make a mob farm. I'd honestly be fine with just zombie eggs being added. I was just thinking with allowing mob eggs we as mayors could create PvE areas for our residents. 

Honestly just thought I would throw the idea into the feature list in the slight chance it would be accepted making my life easier, but also this adds new ways for new residents to be engaged on the server

**Comment by Veyronity** [comment]
Hmm I see
However the wandering trader trade is not a good idea, but yes i agree, zombie eggs wont hurt that much and might be beneficial, who uses rottenflesh anyways? but again its mostly gonna be used for xp purposes, since mcmmo disables xp from spawner spawned mobs

**Comment by keijodputt** [comment]
Problem with the spawners is that, in order to reduce lag, the AI from spawned mobs is completely disabled, thus, the mobs will stay where they fall after spawning and won't fight the player, so the PvE experience will be empty at best.
Mob platforms, OTOH, produce mobs with basic AI, able to track, attack, evade, and they also give McMMO XP. Yes, the spawn rate is way slower, but they give a better PvE.

**Comment by CorruptedGreed** [comment]
While this is interesting, unfortunately it would not be possible given you can put these eggs into a spawner. Unless we get some proprietary plugin to prevent that interaction, and whitelist blaze/magma cube eggs, it would be difficult to implement. An alternative method of invoking mobs could be considered though

**Comment by Veyronity** [comment]
> While this is interesting, unfortunately it would not be possible given you can put these eggs into a spawner. Unless we get some proprietary plugin to prevent that interaction, and whitelist blaze/magma cube eggs, it would be difficult to implement. An alternative method of invoking mobs could be considered though

The whole point of this suggestion is to use them in spawners lol; it's not any use to spawn in **one** skeleton from an egg you buy from a merchant. Whole point is to spawn in an infinite amount for efficient farms.

Just had to clarify that.
