### ISSUE TITLE
[Mechanic] Increase nation range

### ISSUE THREAD

**Issue by Proserrr** [EarthMC/Issue-Tracker#1746]
### Is your feature request related to a problem? Please describe.

There are 3 primary reasons why ‘meganations’ exist on EMC:
1. Everyone wants a tp in their town. (public /t spawn added)
2. Everyone wants a K beside their name etc for their ego
3. Someone’s town is too far away to join a nation. So they make their own and join to form a ‘meganation’

### Describe the solution you'd like

Increase the nation range. Don’t remove it, something like an increase to 5000 blocks rather than 3500. Even 4000-4500 would be nice

### Additional context

You might argue ‘just make your town closer to the nation you want to join’. For places like Europe this likely is far from easy. You could also argue it makes the map inaccurate. Does it? Some large nations irl (canada, brazil, china, usa etc) are currently impossible to replicate border-wise on emc. Not even considering past nations or empires with large extents. This change would allow more people to consolidate into larger nations and groups. This is merely a suggestion but wanted to see any thoughts on this.

**Comment by Fruitloopins** [comment]
something is happening in relation to this already but I will write it later

**Comment by Fruitloopins** [comment]
i was writing a plugin to make nation range extend based off of towns, so if you had a town on the edge of your nation it would extend the range x amount of townblocks around that town, but as i was almost done i talked to llamadeal about changing something in towny for it and he just ended up adding it to towny itself so we will probably use that feature https://github.com/TownyAdvanced/Towny/pull/7116

**Comment by Proserrr** [comment]
we should do that

**Comment by anixrazr** [comment]
agree

**Comment by Aylywyn** [comment]
How does their system work (I know I could maybe look it up... later, maybe.)?

If you wanted Nations to go organically you could make it so in order to join a Nation you have to be within 512 blocks of the Capitol or 256 from another Town in the Nation.  Cap it at 8192 blocks (16 Regions).  For IRL, Canada is around 16384 blocks across.

This would make Nations spawl out from the centre.  And add some fun if you got a critical town in the middle to switch and have half the Towns fall out of range until a new bridge town is made.  A bit of War.

**Comment by Fruitloopins** [comment]
ain't readin allat

**Comment by LlmDl** [comment]
![image](https://github.com/EarthMC/Issue-Tracker/assets/879756/1dcf7246-241e-4b15-ab92-6b9115181738)

**Comment by Fruitloopins** [comment]
added dynamic nation ranges in latest update
