### ISSUE TITLE
[Bug] Unstackable items are now stackable because of the new shop plugin

### ISSUE THREAD

**Issue by 12bowl** [EarthMC/Issue-Tracker#1754]
### Server

Aurora

### Describe the bug

With the changes to the shop plugin, it is now possible to change the item quantity sold in shops to obtain stacks of previously unstackable items. 

### To Reproduce

Step 1- make a shop selling an unstackable item (ie: potions/ender pearls/tools)
Step 2- change the quantity from 1 item sold per to any other number
Step 3- buy the item from your shop, and watch as a stack of unstackable items appears in your inventory

### Expected behavior

Unstackable items/ items with a stack amount that is lower than 64 should not be allowed to stack. Shops returning an error message when trying to change the quantity sold would be a nice thing to implement...

### Additional context

Now I know it sounds a lot like cope and whine on my part, but this brings a massive change to pvp. You are now virtually immortal, as you can stack a massive amount of potions in your inventory, making fights even more long and drawn out than before. Combined with infinite durability circa the /bottle commands, EarthMC pvp

**Comment by asyi0** [comment]
I think this feature is partially useful, e.g. when dealing with potions in a shop, but the problem is that pvp can be very prolonged.
The feature that allows shop can sell multiple quantity of unstackable items is fine as it is.
I think it would be reasonable expected behavior to make Illegally stacked items will be unstacked when it is used with a right click, just as they are when picked with a left click.

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
