### ISSUE TITLE
[Bug] EMC Bulk API doesn't work

### ISSUE THREAD

**Issue by Startive** [EarthMC/Issue-Tracker#1770]
### Server

Aurora

### Describe the bug

it returns error 504

### To Reproduce

Request any of the earth mc bulk APIs

### Expected behavior

it is supposed to return the data of every nation/town/resident, depending on which one you chose

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/140018802/cc4f385a-31a0-405a-9f52-9927319e1c50)

**Comment by deafkite42** [comment]
Its been a bug ever since bulk endpoints were added months ago. Iirc it has something to do with Cloudflare and the large size of the payloads on bulk endpoints. You could just send concurrent requests and individually query each entry but that takes a long time for the resident endpoint due to rate limiting.

**Comment by Fruitloopins** [comment]
@Startive there is now a v3 in beta that allows you to search for many things at a time by separating them through commas, pre-release docs are at https://github.com/EarthMC/EMCAPI/tree/master/docs

you can request up to 100 things but keep in mind requesting a lot of things can still cause timeouts, but i'm working on multithreading and increasing that timeout time if possible
