### ISSUE TITLE
[Feature] Re-enable mcMMO double smelt ability

### ISSUE THREAD

**Issue by MSatrokrm** [EarthMC/Issue-Tracker#178]
Why exactly was double smelt taken away?

Mining is tedious, even with haste. 16g to claim a chunk, that's a whole mining trip right there for most people. Most people don't want to go keep constantly going on mining trips to just claim 1 chunk of land.  

You can't just outright remove double smelt.
Bring it back, por favor.

**Comment by BowShot118** [comment]
#BringBackDoubleSmelt

**Comment by TypicalFernie** [comment]
#BringBackDoubleSmelt

**Comment by Ultil0l** [comment]
#BringBackDoubleSmelt

**Comment by 32Gold** [comment]
#BringBackDoubleSmelt

**Comment by MineHero43** [comment]
#BringBackDoubleSmelt

**Comment by shirazmatas** [comment]
Double smelt should just be replaced with a set 1.5x modifier so not to punish noobs :syn:

**Comment by Coffeetom** [comment]
#BringBackDoubleSmelt

**Comment by BowShot118** [comment]
Keep it as double. Makes ore trades, which are useful for new players, a decent idea.

**Comment by IanNotEN** [comment]
#BringBackDoubleSmelt.

Both double drop and double smelt need to stay within the game. You see, many of us have ambitions to build cities that will require a decent plot of land, but a lot of us also don't want to spend 100% of our time on the server mining. It is almost essential to have the double drop and smelt around

**Comment by L4certa** [comment]
#BringBackDoubleSmelt.

We only play the server because it has the mcmmo benefits, other wise whats the point?
If you want realism your going to need to remove mcmmo completely along with the Nether and the End and Endermen and Phantoms and Skeletons and Zombies and so much more. NO ONE is joining EMC because they want to play in a realer than real roleplay Minecraft server  theny just want to have fun. This is ridiculous and is/will negatively affect this servers player base.

**Comment by RoJoGuapo** [comment]
#BringBackDoubleSmelt

**Comment by ChewyRedstone** [comment]
Leveling mining and repair takes time and resources. Double smelt is an incentive for players to spend time on the server and develop their stats. The dynamic that occurs when high stat players smelt the ores of low stat players creates a healthy environmemt by promoting trade and establishing a nation's industrial sector. If anything, enabling double smelt is actually MORE realistic than not enabling it because it symbolizes the investment made when real world countries pour time/resources into improving their manufacturing technology.

**Comment by BowShot118** [comment]
> Leveling mining and repair takes time and resources. Double smelt is an incentive for players to spend time on the server and develop their stats. The dynamic that occurs when high stat players smelt the ores of low stat players creates a healthy environmemt by promoting trade and establishing a nation's industrial sector. If anything, enabling double smelt is actually MORE realistic than not enabling it because it symbolizes the investment made when real world countries pour time/resources into improving their manufacturing technology.
I agree

**Comment by Arganog** [comment]
Personally, I like double smelt and think it should be re-enabled, I think it gives an incentive to grind mining and repair and for gives more committed/long term players an advantage without being completely broken so that new players cannot catch up.

I do agree with the mining double/triple drops of gold ore being permanently disabled, because being used in conjunction with double smelt that was too much of an advantage

**Comment by Ultil0l** [comment]
I would put back double drops, but with a very slower progression curve, like every level 0.01% or something

**Comment by MineHero43** [comment]
I personally think double drops is a little too OP, if it is re added then disable for gold imo. However double smelt is something which should be re enabled and in my opinion shouldn’t have been something which was even considered to be removed in the first place.

**Comment by MSatrokrm** [comment]
>Nobody has ever said that double smelt was turned off "for realism" - that has not entered the equation at all.

I know, no admin has said it. Some players were saying it and I really didn't have anything to write, so I wrote it.

>As I understand, the Admins feel that the mcmmo abilities that increase gold were too OP/unbalanced for use on this server
Examples: Mcmmo salvage of gold items
Mcmmo mining double-triple drops of gold ore
and now Mcmmo double smelt

Double-triple drops of gold ore have already been disabled, I'm sure you can get away with disabling salvage as well - since not that many people use it. The thing admins cant get away with removing is double smelt, as the others have said; it gives an incentive to lvl up their mining and repair skills.

**Comment by TypicalFernie** [comment]
Double drops should be re added but not for gold. Its useful for other ores especially for quartz. I need over 400 stacks of quartz and double drops would extremely help :pls:

**Comment by TypicalFernie** [comment]
"Double drops"

**Comment by MineHero43** [comment]
I’m retarded :(

**Comment by BowShot118** [comment]
:syn:

**Comment by MineHero43** [comment]
Anyway if double smelt is re-added, I think it should be done sooner than later. I know of some players who have either stopped mining completely or are saving their gold ore, in hopes that it will return and they can get the benefits..

**Comment by 32Gold** [comment]
What do you expect Minehero. This is EMC they’re not going to give you a timely and proper answer lol. People are going to screw themselves smelting ores now if double smelt comes back

**Comment by Synargle** [comment]
From what I told from Karl, it should have never been added in the first place. It was a fault within the config so it was backpedaled.

Karl's definitely seen this thread.

**Comment by sharkfynn1012** [comment]
Eugh, everything about this server is becoming less convenient. There are some people out there that would rather be able to get on and build, if you are going to disable double drops, fine. It is inconvenient but fine. Just keep it on for other things, quartz and what not, we are here to have fun, not spend forever busting our asses trying to gather resources. Not everyone is on around the clock grinding away.

**Comment by sharkfynn1012** [comment]
It is also important to remember that these tickets are echo chambers, these tickets are really innacurate ways to gauge what the player wants, the teleportation removal ticket was an example of that when I did a survey majority of people were against the idea, but on the issue channel most people supported it.

**Comment by KarlOfDuty** [comment]
I do indeed read every comment on the issue tracker. I am not convinced about the double smelt ability being added back in. I do feel like the double drops ability would be much better as it works on things like quartz as some have mentioned. There is no reason to make gathering building materials more grindy, only gold must be kept in check so town claiming and creating nations doesn't get too easy.

**Comment by FutureLemon** [comment]
I'd prefer if it was turned on, because I want to build but it takes twice as long that double smelt got turned off...

**Comment by MineHero43** [comment]
I mean we literally conducted a poll where over 100 people voted in favour of re enabling double smelt.

Double smelt didn’t make claiming “too easy” it made it more reasonable and manageable, without double smelt you’re just making it more grindy which has already been mentioned above.

If the majority players who actually have to grind for gold and spend hours of mining want double smelt turned back on, I don’t see why it shouldn’t be.

**Comment by BennyBurst** [comment]
What is the meaning of grinding up to lvl 1000 in mining and repair, if you cant salvage, and you cant doublesmelt.
I used 3 stacks of diamond blocks to get my repair up, so i can doublesmelt. The same day i hit 1000 smelting, it get disabled, with no warning, and no announcement.

Karlofduty told me its not a big update, so it doesnt need any announcement.
Not only is doubledrop on gold disabled, but all doubledrop in general is removed. No nerf, just completely removed.
The whole meaning of miningskill is gone. The meaning with smeltingskill is gone. The meaning with salvage for all items is gone, not just gold but all of it.
That means that the skill of fishing is basicly useless.

I had an issue with witherskellektons not spawning in nether, after the server reopened after the economy issue. Just pigzombies and magma were spawning.
I told karl about it, he told me they didnt do anything about it.  But later on, he found out it was disabled, but he re-enabled it.
I didnt notise any difference, so i told him, im not getting any witherskelly spawns, just pigzombie, and getting tons of gold.

He told me I wassnt suppose to get any gold from them, so he logged on, and disabled that aswell. But that either doesnt need an announcement.

This means, the only way of getting gold to expand your town 1 chunk, is to go and mine 16 ore of gold.
Or vote for 2 days. or have some luck with fishing, its like 0,0001 % chance of getting gold ingots from it.
Dont tell admins, cus they are gonna disable fishing aswell.

~Benny

**Comment by lucasw2011** [comment]
I think the staff need to stop inforcing the realistic game play I think people just want to play the game like on the last map where people could have vast empires and gold would double drop and double smelt 

I think if you guys don’t let up someone will make another spin off server and this time people will actually go. Classic could handle spin off servers because it was better than all of the competitors but this map and new style of running the server. I don’t think will hold up as easy. 

People keep demonstrating that they don’t want to play by the new style that you guys have implemented, most groups don’t want to work together look at eruope all those nations in one spot. THEY DONT WANNA WORK TOGETHER! lol

**Comment by Magenent** [comment]
Also people who have grinded repair to get double smelt have grinded for weeks in total across everyone and have had to spend massive amounts of iron and diamonds. I know for certain that I spent at least 2 stacks of diamonds to just grind my repair level and at least 4 hours, its taking away hours of grinding and resources themselves like iron and diamond we should at least be refunded if double smelt isn't brought back.

**Comment by 32Gold** [comment]
He didn’t address anything, he just said he’s not convinced to give the easiest answer.

It’s amazing how because Karl mentioned this in a donator chat weeks ago (either the donator chat on discord or early access in game), that justifies disabling double smelt when so many players utilize it and want it back. 

These tickets aren’t going to do anything, they don’t care how many people protest, since they have no competition. Eventually, if they keep giving half-assed answers for things everyone is asking about, and disregarding how the PLAYERS want to PLAY the game, there will be.

**Comment by Pengun78** [comment]
Be an epic gamer and bring it back

**Comment by Pengun78** [comment]
We need to rise and grind for the bread not the gold

**Comment by FutureLemon** [comment]
https://strawpoll.com/ky7zk5rf should say enough....

**Comment by TypicalFernie** [comment]
Karl you're saying that gold is too easy to get with double smelt, when in reality it isn't. Not only you have to grind for hours to get 100% double smelt, but finding gold, especially now, takes forever. The east coast is dry asf. All the caves are dry. There's mines in every y level. Im sure a lot of other places are like this too. I find a gold vein every 10 minutes with eff 5 AND haste 2 pots, just imagine without it. Also most veins are 1 or 2 gold. Your also claiming that nations are popping up really fast and double smelt is the reason why. But minehero, terra, and I didn't have the benefit of a high level double smelt when we made the nations. We also spent hours mining, time other people don't have. Nations were either created because of someone who spent hours or days mining gold or communities that gathered the gold together. "Double smelt is too OP" is not the reason.

**Comment by sharkfynn1012** [comment]
Gold is really not easy to come by, I can mine for hours and turn up very little. As is things are not rewarding, as is for many a player it feels as though since this release it has very much been the slow tightening of walls, like that Disney Land haunted house, where the walls slowly press in on you. It feels too restrictive, and everything such as this just pushes back someone’s project, means that those involved have to spend a few more hours, a few more days maybe grinding to get something built, or claim over something they have built. Over time gold will become harder and harder to find, and with 150ish players on nearly daily gold levels are already bound to go down quickly.

**Comment by KarlOfDuty** [comment]
Yes, I guess the boost of gold is likely to be from the many issues we have recently had with both the economy plugin and other gold related stuff such as the zombie pigman stuff.

**Comment by lucasw2011** [comment]
Lol this map has been a HUGE disappointment  from Announcing it so early that it prematurely killed emc classic to it not being ready at release then we find out that the game play isn’t the same with a claim cap and less gold and now rumor is that you guys aren’t going to even add the end. If the server was like this before I probably wouldn’t have donated to the server. Lol and when I state my complaints i’m Told to go play classic. But wait it’s broken. Every time you do a command you get kicked and all the textures are messed up. Anyway i’m Just really unhappy with how things are going lol

**Comment by Pengun78** [comment]
Double smelt

**Comment by MineHero43** [comment]
This github has become a place for players to express general disappointments about the server which the disability of double smelt is just one of many.

This GitHub has been open for almost a week and the fact that it still hasn’t been re-enabled or that we haven’t even gotten an update on the situation yet just shows how much the leadershipcare about our input and value our opinion.

Honestly I do find it quite saddening that Karl isn’t convinced when the vast majority of players want something so simple to be re-added, the fact that he doesn’t care about bad publicity and hate is the exact traits which a server manager should not have.

I hope the emc leadership including Karl stop this attitude of disregarding the opinon of players. Some players above have already said the extremes which may follow if they don’t.

**Comment by Arganog** [comment]
>This GitHub has been open for almost a week and the fact that it still hasn’t been re-enabled or that we haven’t even gotten an update on the situation yet just shows how much the leadership care about our input and value our opinion.

This issue has been open for 3 days. Karl responded to it 9 hours ago and is obviously reading all of the comments. The fact that this forum even exists indicates that they care about feedback and suggestions. Otherwise it would just be a Discord Announcement of changes that have been made, like in the past.

> Honestly I do find it quite saddening that Karl isn’t convinced when the vast majority of players want something so simple to be re-added

Doubling the amount of gold in the economy is not something simple, and of course the vast majority of players (myself included) want more gold, that's like saying "people want more money" - If the Admins feel that town claims and nations need to be more valuable, however, they will need to enact a policy that isn't popular with the majority. If the majority ruled this server then it would be an anarchy server.

**Comment by lucasw2011** [comment]
Lol or the majority leaves

**Comment by lucasw2011** [comment]
As i’ve Said i’ve Been loyal to emc but I didn’t donate money when it was emc classic just so that server could be killed for the social science experiment that the new server is becoming lol I mean I could just go make my own server or find a new one

**Comment by Arganog** [comment]
**IF** town claims and nations need to become more valuable, then I believe that raising towny prices would be more effective than disabling Double Smelt

However, a new player that joins automatically has zero percent double smelt... If towny prices are increased, then that certainly makes it more difficult for them to create their initial town. Having Double Smelt would mean more gold in the hands of established players and towns.

**Comment by Arganog** [comment]
I think these are the main three options that could result from this issue:

Option 1) Enable Double Smelt, Raise Towny Prices

Option 2) Enable Double Smelt, Leave Towny Prices the same

Option 3) Disable Double Smelt, Leave Towny Prices the same

What are the Pros and Cons of these potential options?

**Comment by MineHero43** [comment]
A return to the status quo before the disability of double smelt is all we’re asking for. Raising towny prices is never a good option, that will only make the issue worse and as you said it will have a negative effect for new players.

Obviously disabling double smelt and leaving prices the same isn’t practical either, I think enough arguments above support this claim.

However I do like what Fix suggested, re enable double smelt but nerf it so that a little extra grinding is needed to get that sweet 100%

**Comment by lemurbeard** [comment]
What if it gets capped to only 1.5x smelt at max level?

**Comment by Pengun78** [comment]
Thats easy talking if you have 100 % already

**Comment by MineHero43** [comment]
No it would mean even I have to grind more to regain 100%

**Comment by Pengun78** [comment]
karl please add it back gamer

**Comment by lemurbeard** [comment]
I meant that when smelting is 1000, instead of double smelt you get 1.5x smelt

**Comment by MineHero43** [comment]
That would screw over everyone who has grinded for the purpose of getting 2x smelt

**Comment by lemurbeard** [comment]
Would it though? 50% is still significantly better than 0%.

**Comment by MineHero43** [comment]
People need to realise that at the end of the day, it’s not about what the staff want, it’s about what the players want.

Think of emc as a business, we’re the costumers. The number one rule of a business is that the costumers are always right, their opinions matter the most.

We want 100% double smelt, it’s what we grinded for. Both 50% and 0% screw us all over one way or another.

**Comment by BowShot118** [comment]
> People need to realise that at the end of the day, it should not be about what the leadership want, it’s about what the players want.
> 
> Think of emc as a business, we’re the costumers. The number one rule of a business is that the costumers are always right, their opinions matter the most.
> 
> We want 100% double smelt, it’s what we grinded for. Both 50% and 0% screw us all over one way or another.

*KarlOfDuty Bans MineHero43 For "My Server, Not Yours"*

**Comment by sharkfynn1012** [comment]
This is also something to remember, as humans the space we are given is the space we will fill, in this case a big shiny new map, bam it is already quite packed, and in some areas there are already far less to no ores left. People who thought that making the map larger would solve overpopulation and map destruction were wrong, it happens. Irl if a highway is widened it generally does not take much time for traffic to once again clog it. A bigger map? Great, nice but in the end we will always end up back where we started. Raising the prices would just make those that grind longer and harder have the advantage, while casuals or just people who build on the side might have to put in too much time. Some days I really don't think I'm staying here for the server, and rather only for the community. If all of this is an issue, although it may be a bit late for this, we could have used a non gold based currency?

**Comment by FenZenyatta** [comment]
Re-enable double smelt or I throw 1 gold into lava.

**Comment by BowShot118** [comment]
> This is also something to remember, as humans the space we are given is the space we will fill, in this case a big shiny new map, bam it is already quite packed, and in some areas there are already far less to no ores left. People who thought that making the map larger would solve overpopulation and map destruction were wrong, it happens. Irl if a highway is widened it generally does not take much time for traffic to once again clog it. A bigger map? Great, nice but in the end we will always end up back where we started. Raising the prices would just make those that grind longer and harder have the advantage, while casuals or just people who build on the side might have to put in too much time. Some days I really don't think I'm staying here for the server, and rather only for the community. If all of this is an issue, although it may be a bit late for this, we could have used a non gold based currency?

👌 


> Re-enable double smelt or I throw 1 gold into lava.

Bad, I'll take it if you don't want it. Gotta supplement my income somehow, especially with a lack of double smelt.

**Comment by Pengun78** [comment]
there are so many good arguments just re-enable it already

**Comment by FenZenyatta** [comment]
Can we atleast get a statement about this? Fix talked about a possibility of it being re-enabled but in a nerfed form. Me and my friends are keeping on so many gold ores because we don't know if we should smelt it or wait for double-smelt again

**Comment by KarlOfDuty** [comment]
We have no had a scheduled maintenance since the economy issues so we have not looked into this issue yet.

**Comment by FutureLemon** [comment]
> We have not had a scheduled maintenance since the economy issues so we have not looked into this issue yet.

Then schedule one!

**Comment by KarlOfDuty** [comment]
We will work on the server when we have time for it, we have other stuff to do.

**Comment by KarlOfDuty** [comment]
Done.

**Comment by KarlOfDuty** [comment]
@Palestina0007 Behave yourself if you want to post here. This isn't the in-game chat.

**Comment by Palestina0007** [comment]
Karl, do you happen to be a tad bit sensitive to criticism?

**Comment by 32Gold** [comment]
This thread shouldn’t be closed. Obviously Karl didn’t read this, since the original poster MSatrokrm was talking about re-enabling double smelt for GOLD

**Comment by KarlOfDuty** [comment]
You have seen the rest of this thread, criticism is fine. Your behaviour was over the line though.

**Comment by MineHero43** [comment]
> I'm loosing the will to live on the server. Everything is just grind grind grind :/

![screen shot 2018-12-04 at 22 36 44](https://user-images.githubusercontent.com/44756360/49474510-28f5d000-f815-11e8-9ca1-183810ce5408.png)

**Comment by BowShot118** [comment]
Convient that they get all the donations then fuck up the server isn't it?

**Comment by SpookyScoops** [comment]
The server isn't fucked up because of double smelt/drop gold being disabled. There's a reason why they allow using the nation spawns of allied nations. 

You want to make gold? Then how about you get out of your mine shaft and start participating with the player base. Make shops and sell shit. It's not hard, you just have to stop being a cave troll and get out into the sunlight. I haven't mined for gold in weeks, and yet I still have gold for claims etc.

If anything, disabling double smelt/drop gold allows for more professions.
Want to be a farmer? Sell bulk food/wheat.
Want to be a rancher? Sell wool and leather.
Want to be a miner still? Sell me your emeralds. I need emeralds... please help.
You can also do jobs for people etc. etc. etc. 
There's more to minecraft than mining is what I'm trying to say.

**Comment by BowShot118** [comment]
And it is damn hard to make money just via trading.

**Comment by SpookyScoops** [comment]
guess you're just bad at it smh.

**Comment by BowShot118** [comment]
No i just can not compete with the stupidly low prices that players drop items down to. That is what kills trading. People with no sense of how to make Money

**Comment by BowShot118** [comment]
Bring Back the Ikea Monopoly, at least Arg knew what he was doing.
