### ISSUE TITLE
Disable end crystals

### ISSUE THREAD

**Issue by 1212ra** [EarthMC/Issue-Tracker#238]
**Is your feature request related to a problem? Please describe.**
Eh only that ppl are abusing em and I keep gettin dms about it.

**Describe the solution you'd like**
Disable end crystals or atleast nerf them like on emcc

**Additional context**
https://youtu.be/5ewwE3vAkzQ?t=256
Heres a link from a DM I got.

**Comment by Pengun78** [comment]
i think the gamer crystal should stay

**Comment by 1212ra** [comment]
I know they are a vanilla mechanic, they were nerfed pretty hard on emcc so I think its only fair we do the same on tn.

**Comment by AmirMorocco** [comment]
Dear EarthMC, I would love this server to be Bedrock Edition user friendly. Many users don’t have enough money to afford Java so they use Bedrock which is cheaper many players would be very happy to join your server without having to use a PC and play on it on their mobile and Xbox devices. 
Sincerely, Amir

**Comment by BowShot118** [comment]
I mean a new thread :facepalm:

**Comment by AmirMorocco** [comment]
Oh whoops!

**Comment by MSatrokrm** [comment]
> I know they are a vanilla mechanic, they were nerfed pretty hard on emcc so I think its only fair we do the same on tn.

Yeah, I don't think end crystals should totally be removed. Nerfing it is fair for everyone.

#NerfEndCrystals

**Comment by Magenent** [comment]
Karl I know you'll probably just not even bother to look, but for once could you please listen to what I'm saying and coming from my perspective. The way I see E-Crystals for the most part unless there is an easy kill, is to kill claim hiders. That was what I used them on classic and that is for the most part what I'm using them on Terra Nova. Since there is no war plugin someone can greif you, even if they get warned you still can't do anything about it since you can't toggle pvp in their claims so you goto their town and crystal them thats the main use for it. Once a proper war plugin gets implemented there will be no use for crystals and you could nerf them for all I care, but until then they are crucial in securing a balance so you can kill people who would hide in claims, also I guarentee if Qin found out about this first and got it mastered they would not be complaining. Also they are not that good, cause I'll DM you what it is but they aren't that good actually, they are very specialized and they can be countered easily so I don't see a point to nerf something that isn't that big of a deal, but then remove stuff that most of the community wants, and is good (double smelt) but that isn't the point of the arguement about double smelt the point is that you should keep crystals since they are only used in certain situations and they can in battle only be used in a very specialized role.

**Comment by KarlOfDuty** [comment]
From your dms and this it would seem like they can only be used to exploit towny protections, so I'm not really sure what case you are trying to make here.

**Comment by 32Gold** [comment]
I support disabling or nerfing crystals, they’re able to attack people in town claims which obviously isn’t ok

**Comment by IGNSlaid** [comment]
i support keeping the end crystals damage but disabling somehow its damage inside of claims
