### ISSUE TITLE
[Feature] Ability to individually lock doors

### ISSUE THREAD

**Issue by IGNSlaid** [EarthMC/Issue-Tracker#244]
I'm frustrated by how we cant make town claims limited in the Y layer and this makes apartments hard to get, but we can counter this with locks.

adding locks would be a nice mechanic, since we can toggle switch perms on and break perms off, which grants security in apartments, cuz you [with locks plugin/system on] will be the only one who can access your apartment

**Comment by MSatrokrm** [comment]
This would be awesome for towns with limited space, such as the towns in Panama core, or towns on small Islands.

**Comment by KarlOfDuty** [comment]
I'll try to add [connection-lost/LockettePro](https://github.com/connection-lost/LockettePro), but it will likely need to be updated to 1.13

**Comment by SushiRoller** [comment]
Today, almost 7 months later, it seems LockettePro is not going to be updated to 1.13 and later versions; even the <a href="https://www.spigotmc.org/resources/lockettepro-uuid-support-abandoned.20427"/>Spigot</a> page states the project is abandoned.

My recommendation would be either to find a replacement for LockettePro such as <a href="https://github.com/rutgerkok/BlockLocker" target="_blank"/>rutgerkok/BlockLocker</a>, or dig into the LockettePro patches made by other users such as <a href="https://github.com/NyaaCat/LockettePro"/>NyaaCat/LockettePro</a>.

Having the ability to lock doors/chests/other containers within towns is a very important feature that we must have since there are towns not big enough to give players a properly protected house or towns focused on using structures for practical purposes. Not even the most complex redstone circuit can stop players with 1000 ping mining their way through walls and sneaking into chests which are not theirs with the Towny permissions system.

Now, regarding worries stated by some players in another issue: BlockLocker (for example) uses a script that allows admins to switch the ability to place down locked chests in the wilderness for Towny, so that's not a problem. However, I would made it so that there's still a way to bypass the lock if you're mayor of a town; if players are up to steal someone's objects they'll do so regardless of their abilities, and we can't just have chests laying in a chunk permanently in case a player quits the server.

The last issue I'd take into consideration is bypassing the Towny switch permission for locked containers, so if the mayor of a town or the owner of a plot places down a door that only certain players can open (or everyone in a town), they'll be able to do so but not open other doors/chests within the same plot.

**Comment by KarlOfDuty** [comment]
We will not be adding another protection plugin as that will lower server performance further.

**Comment by SushiRoller** [comment]
Thanks for your hard work.
We're glad to see the best fitting plugins for an Earth based server have been chosen based in their practicality and not the server's performance, while those less useful clamoured for by our best players have been left aside for later on when the performance issues are fixed, hopefully soon.

Disappointing.
