### ISSUE TITLE
Standardizing punishments 

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#277]
*Thee who enters this thread be warned, hatred and toxicity rising from the depths of this thread*

I believe the server needs standardized punishments for offences such as toxicity. And **clear** guidelines on what classes as toxicity and not. In my opinion, staff have too much free reign over punishments and classifications within the rules. From reading chats, and partaking in rants, it is quite clear that multiple members of the playerbase are unhappy with the current situation to-do with rules and staff.

Just to classify: **This is Not a thread about changing rules in their basis, just standardizing punishments and giving staff clear guidelines for toxicity**

**Comment by 32Gold** [comment]
Agreed

**Comment by gabhinav06** [comment]
Agreed

**Comment by 1212ra** [comment]
The only problem is that literally every case is different, if we did have very clear guidelines I think most staff would agree thats a good thing. But since no case is like the other its very difficult to create a template that covers every possible situation.

**Comment by BowShot118** [comment]
I understand that with the case of toxicity it is hard to draw a clear line, but there needs to be some form of standardization with severity levels or something. It's just annoying with the lack of clear guidelines.

**Comment by 1212ra** [comment]
That would be ideal yes, problem is someone would have to create that standardization. And that would ofc take a very long time. For example when someone spams slurs vs when someone harasses a 15 year old boy. Or what about a 15 year old girl? Or what about a 18 year old boy? There are so many cases and so much to cover. I dont really have time or the patience to make a template that covers everything.

**Comment by ben-okay** [comment]
> The only problem is that literally every case is different, if we did have very clear guidelines I think most staff would agree thats a good thing. But since no case is like the other its very difficult to create a template that covers every possible situation.

I don't think anyone can deny that context is important, and that it is crucial, however, if there are certain standards, so that Staff can say '[Player] deserved X punishment because they did Y thing'. The Staff are Staff for a reason. I think with some guidelines to punishment, we should be able to trust them to do the right thing. If they mess up, people have other options to point to, like a lesser or greater punishment, as opposed to an all or nothing situation.

> That would be ideal yes, problem is someone would have to create that standardization. And that would ofc take a very long time. For example when someone spams slurs vs when someone harasses a 15 year old boy. Or what about a 15 year old girl? Or what about a 18 year old boy? There are so many cases and so much to cover. I dont really have time or the patience to make a template that covers everything.

Staff discretion <o/. Dab on 'em.

**Comment by BowShot118** [comment]
But many case? Like examples you have given, can be covered with similar terms. And the sooner something along these lines gets started the better. Groups like slurs, spamming and harassment can easily be dealt with in similar terms. And these are guidelines so when staff can drift slightly, but not jumping from an hour mute to 1 day.

**Comment by 4noah18** [comment]
I don't think it would be like you sit down for fifteen days making guidelines. I've done this shit before and I really enjoy making rules and shit despite me being a little rebellious edgy emo teen. Doesn't take that long if you go about it the right way. Incorporate the rules you already have and maybe a couple others, sit for an hour and think about other stuff that would make sense to add, and then just continue on as you go. What I mean by that is get the basics down, and then you just have to add more based on experiences that will come. You can't predict everything. Also for the love of fucking god, if the overall community makes it **_abundantly clear_** like we have before that we don't like a certain rule, please remove it.

**Comment by PoppyK** [comment]
I mainly stay out of general chat now because of the toxic nature of it.  Below are things I would include as coming under the guise of “toxicity”.  I have staffed a few servers and made rules for them, and I have found it best to be very clear in the rules as to what behavior you do not want to see.  Of course, all situations are different and are reviewed independently but most things I see in chat now come under these groups I have listed below. 
 
Harassment:
-          Bullying
-          Sexual abuse (unwanted sexual advances or obscene remarks)
-          Verbal abuse
-          Trolling
 
Vulgar Chat (Vulgar chat defined as anything offensive or crude.)  Any chat in global that talks about:
-          Body parts 
-          Sexual situations
-          Bathroom talk 
 
Hate Talk.    Any chat that talks negatively about:
-          Race
-          Gender
-          Religion
-          Rape, bodily harm 
 
Also, it was mentioned that it is hard making decisions on player cases. But I found it best to include a few staff for appeals.  It shouldn’t just fall on one staff member.  For instance, a staff member bans a player and that player appeals.  Two other staff should review the case but NOT the staff involved in the banning.  The original staff member who banned the player should be in communication with other staff about the “case”, but a final call should be made by another staff member.  That helps to keep things “fairer” in the players' eyes.  Also, it helps to show a more unified staff front. (And maybe this is how it is done at EMC, but was just showing how I resolved appeals.)

When attending a mixed group event in real life we don’t talk about most of these things above for fear of offending someone, but somehow with this thing called the internet people don’t seem to think their words matter.  But they do.  I’ve seen many players leave this server due to bullying and toxic behavior.  I think that most of us would agree we would like to see less toxicity in chat.

**Comment by FutureCW** [comment]
I have a few suggestions for rules that may need to be defined better as it seems they may be a bit hard to interpret.

1.3	Technical errors and server exploits.
Players are not allowed to take advantage of apparent server bugs or otherwise exploit technical oversights. Players found taking advantage bugs or technical oversights without notifying staff may be permanently banned. 

I believe this rule should also protect against the exploitation of the rules of the server, like mute/ban evasion, and racial slur bypasses.

The next rule is rule 2.1

2.1 TP killing.
TP killing is the act of tricking a player in to accepting your teleportation request with the purpose of killing them. Although frowned upon it is still allowed as it is up to each player whether or not to accept the teleportation request. Repeatedly doing it to everyone who joins however may be classed as toxicity.

I think that this rule should be made clear that trapping people in nether portals is against the rules. This also leads into the next rule about toxicity

2.4 Toxicity.
Toxicity is not allowed on this server. Toxicity in chat can be for instance using racial slurs, sexual harassment or severely explicit language. It can also be other non-chat actions which drive players away from the community, for instance luring newly joined players to your town so you can kill them or lock them in your town jail.

This rule definitely needs to be defined more than it is now. Racial slurs/bypasses, sexual harassment of players, repeatedly spawnkilling other players, and etc. I think it needs more 'instances' that it has on there.

The next rules are about griefing.

3.1	Destroying land around claims.
Players may not damage terrain around claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. Please note that mayors/kings are responsible for misconfigured town/nation permission settings. Examples of grief:
Cobble monsters - Mountain-like structures that are built using lava and water.
Lava/water curtains - Placing rows of lava/water in the sky to make a wall of falling lava.
TNT craters.
Mass spawning entities within or around a town (Chickens, Boats, etc.).

I think it also needs to include /resident settings in the misconfigured part of the rule. It also may need the example of destroying unclaimed builds near towns.

3.3	Claim blocking.
“Claim blocking” is referring to the act of deliberately placing outposts near a town in order to block its expansion. This is not allowed since town expansion is prioritized over outpost expansion. Placing outposts over abandoned towns is also considered claim blocking, these areas are supposed to be left for new mayors. Towns placed close to other towns are not subject to this rule as both parties have equal right to the land, unless one is claiming around the other.

Players reporting a claim block must have a sincere intention to expand in that direction and are expected to do so after blocking claim is removed. All claims which staff concludes to be blocking a town will be removed without any refund. Players found to be claim blocking more than once may be warned and denied the ability to place outposts all together.

This rule seems outdated due to the outposts part since they're disabled. I feel like the rule sort of contradicts itself as it says that players must have a sincere intention to expand, but it also says that towns placed close to other towns are not subject to the rule, which makes it contradictory.

3.5 Major terraforming.
In order to preserve the accurate geography of the map, major terraforming projects are not allowed. In general, if your edits of the landscape alter the Dynmap view of the natural landscape, they will be removed. Examples of this includes for instance draining large lakes/rivers, creating artificial islands which do not exist in real life, or covering the ocean with platforms.

I believe rule 3.5 should be edited to say editing the 2d version of the map, as it seems destroying entire mountains are allowed with permission from staff as long as they don't alter the 2d landscape. 

That is all i have to say for the current rules, also: Don't shit on staff that are doing nothing wrong besides being the closest staff member to talk to

**Comment by NigelFarage666** [comment]
I say we remove that dumb toxicity rule made by stupid milennial libtards.

**Comment by NeonKrby** [comment]
this should just be about removing john.

**Comment by Magenent** [comment]
Listen I get that toxicity can be a thing with some players, but it is a very rare occurrence where action should be taken, this is the internet "toxicity" is everywhere and people should expect to not see anything that triggers them, so it really shouldn't even be so clearly defined, and should only be used on people who are constantly toxic and actually cause many people to stop playing the server.

**Comment by Magenent** [comment]
> I mainly stay out of general chat now because of the toxic nature of it. Below are things I would include as coming under the guise of “toxicity”. I have staffed a few servers and made rules for them, and I have found it best to be very clear in the rules as to what behavior you do not want to see. Of course, all situations are different and are reviewed independently but most things I see in chat now come under these groups I have listed below.
> 
> Harassment:
> 
> * ```
>        Bullying
>   ```
> * ```
>        Sexual abuse (unwanted sexual advances or obscene remarks)
>   ```
> * ```
>        Verbal abuse
>   ```
> * ```
>        Trolling
>   ```
> 
> Vulgar Chat (Vulgar chat defined as anything offensive or crude.) Any chat in global that talks about:
> 
> * ```
>        Body parts 
>   ```
> * ```
>        Sexual situations
>   ```
> * ```
>        Bathroom talk 
>   ```
> 
> Hate Talk. Any chat that talks negatively about:
> 
> * ```
>        Race
>   ```
> * ```
>        Gender
>   ```
> * ```
>        Religion
>   ```
> * ```
>        Rape, bodily harm 
>   ```
> 
> Also, it was mentioned that it is hard making decisions on player cases. But I found it best to include a few staff for appeals. It shouldn’t just fall on one staff member. For instance, a staff member bans a player and that player appeals. Two other staff should review the case but NOT the staff involved in the banning. The original staff member who banned the player should be in communication with other staff about the “case”, but a final call should be made by another staff member. That helps to keep things “fairer” in the players' eyes. Also, it helps to show a more unified staff front. (And maybe this is how it is done at EMC, but was just showing how I resolved appeals.)
> 
> When attending a mixed group event in real life we don’t talk about most of these things above for fear of offending someone, but somehow with this thing called the internet people don’t seem to think their words matter. But they do. I’ve seen many players leave this server due to bullying and toxic behavior. I think that most of us would agree we would like to see less toxicity in chat.

Yeah no, most of the stuff would already be on the line between genuine "toxicity" which is already in quotations and just plain out censorship, this aint Hypixel so I don't even know why "bathroom talk" or "body parts" would even be considered? So you can't fucking say "poop" that is just crazy not to mention the fact that making jokes about races, religion and gender should be fine since they are just that, jokes plus you'd be able to make fun of all of them not like white and christian and male would be removed.

**Comment by Kyoris** [comment]
I mean since the server is not aimed at 10yos, so any sort of swearing or the sort would be fine as long as there aren't any harassment, ex. Insulting every little thing someone says for no reason for 30+ minutes.

**Comment by AidanMSad** [comment]
I joined the server after a break and these guys were messing around in trade chat so I said something smart assley and I got muted for 5 hours.

Not a warning, or anything just straight out 5 hours. You would think at least a warning or 30 mins mute if being extreme

**Comment by NigelFarage666** [comment]
What server is aimed for 10 year olds? I got minecraft when I was 11 and I became real player when I joined a server I wont name but it was towny on default anyways. 
10 year olds RARELY play on servers and if they do they usually just quit or do some shit 10 year olds shouldn't have access to internet anyways.

**Comment by 4noah18** [comment]
Don’t water down the fucking server. Anyone above twelve, which is most people, can handle some naughty words. And even if they are twelve, that or younger is the age when you’re supposed to be edgy and learn about swearing and stuff. As long as it’s not targeted harassment, don’t censor our speech.

**Comment by BowShot118** [comment]
This thread isn't about changing the rules, it is about setting out clear guidelines and Poppy was giving examples of what she has done in the past. This isn't based around changing any rules in a drastic manor despite my opinions.

**Comment by FutureCW** [comment]
> This thread isn't about changing the rules, it is about setting out clear guidelines and Poppy was giving examples of what she has done in the past. This isn't based around changing any rules in a drastic manor despite my opinions.

I think this thread is more for expanding the rules than it is drastically changing them. There's no rule that blocks mute/ban evasion either.

**Comment by KarlOfDuty** [comment]
As has been discussed above, there isn't really any way to standardise punishments as all cases are very different. We have general guidelines for different rules but the punishment depends on the individual case.
