### ISSUE TITLE
[Suggestion] Remove N spawn to other nations.

### ISSUE THREAD

**Issue by JasperSomething** [EarthMC/Issue-Tracker#328]
If we remove this then trade between nations will actually be a thing, ie Nation A struggles to make a certain good so they import in mass from Nation B and then sell it to their citizens. And there would be a market for transport services. Ice ways in the nether would become the way people move between large distances so as a result the nether might have to be thought about when you reset it.

**Comment by Kyoris** [comment]
I don't feel like trekking half the world just for some leather or cheap diamond or enchanting

**Comment by Kyoris** [comment]
And I'm pretty sure everyone else feels roughly the same

**Comment by BowShot118** [comment]
It would make the server virtually unplayable

**Comment by Zasdd** [comment]
I agree with Jasper. Railways and the like, travel in general really, has lost it's value. Especially in Europe, there are so many nations and everyone is allied to almost everyone else. You can just tp anywhere you want and it makes the world as a whole feel much much smaller.

**Comment by ScaryDragonn** [comment]
pls no

**Comment by Zasdd** [comment]
What do you mean you cannot do anything? The only downside is trading is harder, which puts more values on items, allows local economies to be different from global, and allows delivery industries etc.

**Comment by BowShot118** [comment]
It makes it impossible to go anywhere. As you said, trading is really hard. This cuts off a stream of income for players working towards nations. 
You cannot partake in events, such as the Olympics due to the incredible distance that many players have to travel.

It makes the game significantly harder, and railways will still be used commonly. But for towns in remote places, such as mine, it is difficult to interact with the community. 

What this does is punish players who chose to settle outside of Europe and North America, not add a new dynamic to the game.

**Comment by Pengun78** [comment]
On one side i support this but on the other side i dont.
As zassd said, travelling lost its value. If we remove this there would be alot of ice roads like there are highways in real. But i'd miss exploring as i wouldnt travel 8000 blocks just to see a town that interested me

**Comment by NeonKrby** [comment]
just dont its a bad fucking idea that would make the server worse.

**Comment by FutureCW** [comment]
If nation spawns were removed, it would have some positives and negatives.

Positives:
Promotes ice rails for fast transportation and normal rails for afk transportation
Nether will be put to good use with highways and such
Like you said, it would be more realistic with nations exporting goods to other nations, which would become its own economy.
More people will build up their own items instead of relying on others 

Negatives:
Europe and NA will be much more crowded
A lot of nations and towns will be isolated and unwanted
Towns not connected by some sort of transportation will be left out
Less exploration due to the time it takes to get from one place to another
Shopping nations outside of Europe and NA like Micronesia will be made useless, making players lose tons of revenue from their shops
Overall lower wealth because less people want to go to other towns to purchase items

**Comment by Ultil0l** [comment]
Other negative: you cant do /n spawn HolyRomanEmpire to get to the KSC and get owo time

**Comment by Kyoris** [comment]
nyet blyat

**Comment by NeonKrby** [comment]
oh my fucking god this is a terrible idea just drop it.

**Comment by WyWall** [comment]
Well a potentiaal solution is that a new type of plot could be created which would be a nation teleport for outsiders which would cost a large amount of gold, or we could make it so people can only tp to a nation if they have an embassy in said nation which would force certain nations and their capitals to be large enough to actually allow people to teleport to said embassy

**Comment by KarlOfDuty** [comment]
We do not think this would be beneficial to the server.

**Comment by NeonKrby** [comment]
praise be to karl
