### ISSUE TITLE
 (dealt with) [World] Villager Inventory Full

### ISSUE THREAD

**Issue by DarkReactor** [EarthMC/Issue-Tracker#341]
**Describe the issue**
This was the closest thing I could find to my issue. I dropped wheat on my Cleric which does not produce bread and is now stuck with a full inventory so they may not breed. I'd love if you could either clear the inv or kill the villager and replace it with a new one please.
**Coordinates**
X- 27244.621 Y-78 Z- 6107 coordinates.

**Screenshots**
Please add screenshots to help explain your problem. They can be of both the emc map and of how you want the terrain to look.
![inked2019-01-31_17 40 08_li](https://user-images.githubusercontent.com/47232587/52097354-9efd8580-257f-11e9-9326-103549e11729.jpg)

**Comment by AlexGamerYTT** [comment]
It would be nice if you can get the option to clear his inventory when it's full.

**Comment by johnyuki** [comment]
It will breed don't worry. I had the same issue.

I used to have my villagers with carrots growing, but then I switched over to Wheat. But, because their inventory was full of carrots, they didn't farm it. I just had to wait for them to use up all their carrots and they eventually started harvesting the wheat.
