### ISSUE TITLE
[BUG] pvp mcmmo Stats not leveling up

### ISSUE THREAD

**Issue by prokillerr** [EarthMC/Issue-Tracker#464]
Ive noticed the past 2-3 days the pvp Stats only dont increase at all. I checked each one with their respective cmds(/axes /unarmed /archery /swords) and not even the xp in between each level increase, not after hitting neither after killing mobs/players. It's a bit setback because New players have no chances of catching up to old ones in terms of pvp as the old ones can mostly butcher them with their already high Stats while the new players cant increase their own.

**Comment by Kyoris** [comment]
Eh mcmmo pvp abilities are disabled rn so it doesn't really matter... It would be nice to re-enable them that is

**Comment by KarlOfDuty** [comment]
Can anyone confirm they are having issues with mcmmo abilities not leveling up?

**Comment by unown006** [comment]
Yes I can I tested it and can confirm currently its disabled

**Comment by WhitPlayzYT** [comment]
My archery axes and sword skills still level up just not from pvp only pve

**Comment by prokillerr** [comment]
They never increased from pvp to begin with. In my case(and other's as well if not everyone on the server other than you whit) they stopped increasing all together, thus giving veterans who had more time to increase them an unfair advantage. Thankfully not many ppl have focused on them but the few Who did still got an advantage.

**Comment by Kyoris** [comment]
The abilities are disabled so it doesn't really matter

**Comment by unown006** [comment]
Some work some don't if they are they should be re-enabled because they're a pain in the @ss to grind out with server spawns and not getting exp off players

**Comment by Steadlington** [comment]
1. As previously stated, Mcmmo abilities do not work in PVP. 

2. Veteran players having an advantage over newer players comes naturally, as they have had longer to grind out said skills. This is not a problem, you can easily catch up if you're good. 

3. Previously you would have been able to grind Mcmmo levels via spawners as the stacking mechanic changed the mob so that it wasn't a recognised 'spawned mob', and therefore gave Mcmmo xp. 

4. You can still grind out Mcmmo combat levels via Pigmen in the nether (As we used to do before the stacking mechanic was even in the game), I personally had 250+ in swords before this was added. Pigmen give 3x the normal xp per kill (Works on xp per hearts taken from mobs) 
Reference: https://mcmmo.fandom.com/wiki/Experience_Points

5. There shouldn't be any Mcmmo xp drops from players as this is highly prone to abuse and will cause issues such as death spams in chat

**Comment by prokillerr** [comment]
To adress your points:
1:wdym dont work? Swords bleeding, unarmed's disarming and arrow pushing, axe's dmg etc all got disabled/bugged?
2:I never said vets having an edge is unfair, what I said is that being totally unable to reach/surpass them due leveling up being disabled is unfair. Its like starting a vanilla server and owner gives someone a sharpeness 1k sword, its Just an advantage not all players have. You should work on your reading skills bro cuz you obviously didnt get what I said.
3:so the reason we cant grind mcmmo from spawners is that the settings went back to default, meaning we can only grind from normal mobs?
4:ill actually try that to confirm wether its what I said on 3 or a glitch that stops us from grinding so I can update this thread with info
5:I dont have an opinion to this, both options are fine with me.

**Comment by Steadlington** [comment]
1. They are disabled as previously stated by other people on this thread. E.g. Kyoris comment earlier. 

2. You are able to reach/surpass them. I am one of these players with extremely high Mcmmo levels because I work at it and grind, you won't get everything by complaining. As these Mcmmo abilities are disabled, they are of no advantage to anyone who did the grind to begin with, making your point irrelevant. Furthermore, 'bro', let's not make this personal. 

3. You can only grind from normal mobs as spawners are disabled (Blaze spawners). 

4. There is no glitch or bug, you're trying to level with spawned mobs and pvp. Both of these grant no xp.

**Comment by prokillerr** [comment]
Im not trying to grind with pvp,I Just didnt know settings about mcmmo working on mob spawners was set to default(not working) cuz for a while it wasnt

**Comment by CloakedEagle** [comment]
By default, mcMMO doesn't give you XP on mobs spawning from a spawner. Maybe we should have been clear about it on the website. We'll try to add these little things on the website to make it clear for everyone in the future.

**Comment by Steadlington** [comment]
1. You misread my reply to begin with and continued to ask about things that were already answered by other players. Nothing was misread on my part, I have been consistent with my replies. You are still trying to persist with some sort of argument. 

2. Is it not the role of the staff to babysit players who won't do the research themselves, I added a wiki-link earlier for you to review in order to better understand the plugin 'Mcmmo'. 
Reference: https://mcmmo.fandom.com/wiki/McMMO_Wiki

**Comment by CloakedEagle** [comment]
I was replying to prokillerr, not to the issue itself.

**Comment by Steadlington** [comment]
No issue here. Ticket should be closed.

**Comment by prokillerr** [comment]
Stead, I already knew and said myself that by default spawners dont give xp but for some time they did in emc so when it got to default again I thought it was a glitch. Since eagle has said its on purpose then yes, this should be closed. Ill take your advice and grind from pigmen
