### ISSUE TITLE
Regarding the "Lobby"

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#472]
If you're going to have a lobby, have something to do in it that's more exciting than just standing around fondling our balls. What about a 1000x1000 tiny world that regens every 5 hours?
Something for us to do (other than a shitty parkour) would be real nice.

**Comment by xParadoxical69** [comment]
(copied from #473)
There are 3 parkours, but they are just awful and boooooring...

1000x1000 PVP world would be just beautiful. There could be pvp kits, that's everything needed. It would be awesome and much more interesting to play such a thing while waiting to join the Towny server!
Also players could go back from the Towny to pvp lobby with some command, if they would want to play it instead of Towny. Towny would be of course still the main server, pvp world should be still a lobby, but just 1000x1000 and with pvp.
