### ISSUE TITLE
Add meaningful assassinations by removing the death messages

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#497]
This is probably another controversial one, but remove death messages, as first of all it will help with realism. My personal reason for wanting this, is if you execute a perfect attack, where the target does not see you, the target will still know who did it. It's my opinion that if you're able to kill someone without being noticed, you should be able to avoid political backlash. If you see a foreign soldier, you would notify you national leaders, if you were killed by them. But if you execute the perfect attack with invis pots and everything catching someone of guard, you should not be put on public display, as the person you killed had exactly no idea who killed them. This also adds the option for countries to anonymously help in wars, by attacking targets without them noticing.

Also easy implementation with the following command:
/gamerule showDeathMessages false

**Comment by DorienB** [comment]
good small improvement

**Comment by Lemonlicious** [comment]
This would certainly spice things up and make war a little more realistic. +1

**Comment by Kyoris** [comment]
That would make things interesting to say the least, but I like it

**Comment by alekb1** [comment]
Okay apparently not that controversial, good to hear

**Comment by WhitPlayzYT** [comment]
I agree on this but I think messages from kills not from players should stay (aka just no player kill messages)

**Comment by KarlOfDuty** [comment]
I think removing the normal kill messages works too, prevents people from spamming with death messages.

**Comment by Pengun78** [comment]
no, change it to "playername was killed" instead of just nothing

**Comment by Pengun78** [comment]
But that it still doesnt show the player who kills them

**Comment by Ultil0l** [comment]
that seems epic, that way you can kill your citizens without people noticing!

**Comment by KarlOfDuty** [comment]
*China joins the game*

**Comment by watergod1234** [comment]
When I kill skilled players I like to take the screenshot of the death message but I never do anything with it anyways. This seems like a good suggestion.

**Comment by alekb1** [comment]
Karl actually replied to one of my suggestions :000000

**Comment by alekb1** [comment]
But seriously it’s easy to implement and I think it will be great for the server

**Comment by Aitonater** [comment]
On the one hand I like this because like what you said realism and it makes the server more fun. On the other hand I find it really fun when you have been creative when naming your weapons.

A problem with this is when you are attacked the anti-combat logging plugin tells you who has attacked you. So even if you are invisible and trying to assassinate someone unless you use tnt the person will know who attacked/killed them.

I don't think this will be doable but I think a nice compromise would be to hide the death messages if the person killed was using an invis pot/ sneaking/ not visible to dynamic map (I know probably not possible to make those exceptions) and to also just disabled the death messages when people suicide to prevent suicide spam.

I only say this because naming bows and swords and killing people with the quirky names is really fun. (e.g. my bow is called "a Trebuchet" so in chat it reads "Player was killed by Aitonater using a Trebuchet").

And again like I said the anti combat plugin always reveals who is attacking you anyway, so chances are as soon as you have killed the person they will have a salty rant at you in global regardless -thus you lose any anonymity gained from disabling death messages.

**Comment by Prismary** [comment]
To my knowledge, death messages have been entirely disabled for ages now, so I suppose this is solved.
