### ISSUE TITLE
Hostile mobs not spawning in dark areas

### ISSUE THREAD

**Issue by MSatrokrm** [EarthMC/Issue-Tracker#52]
I've literally been standing in my mob farm for about 15 minutes now and not a single mob has spawned...

plz  fix

**Comment by MSatrokrm** [comment]
It is not within claimed chunks. 
The cords are -13169 / 5 / -3664
Its saying that there's lighting even though there are no torches...
Its in the TN server.

![2018-10-28_06 10 52](https://user-images.githubusercontent.com/23727003/47618577-fff55900-da78-11e8-9a5d-d7e46566b832.png)
![2018-10-28_06 10 56](https://user-images.githubusercontent.com/23727003/47618578-fff55900-da78-11e8-8d6f-91d984c74341.png)
![2018-10-28_06 10 58](https://user-images.githubusercontent.com/23727003/47618579-008def80-da79-11e8-8ed8-b85a340df49f.png)
![2018-10-28_06 11 01](https://user-images.githubusercontent.com/23727003/47618580-008def80-da79-11e8-8120-3aace3044860.png)
![2018-10-28_06 11 05](https://user-images.githubusercontent.com/23727003/47618581-008def80-da79-11e8-993e-f80014b7536b.png)
![2018-10-28_06 11 14](https://user-images.githubusercontent.com/23727003/47618582-008def80-da79-11e8-83bf-54497b07e97d.png)
![2018-10-28_06 11 36](https://user-images.githubusercontent.com/23727003/47618583-01268600-da79-11e8-96d0-a9537f9e171d.png)
![2018-10-28_06 10 49](https://user-images.githubusercontent.com/23727003/47618584-01268600-da79-11e8-95ed-f2ab9d8a1b1c.png)

**Comment by MSatrokrm** [comment]
@Arganog @KarlOfDuty ^

**Comment by Arganog** [comment]
I went around and placed/removed torches to update the lighting, this seems to have resolved the lighting issue - this is likely a bug within 1.13, related to the random darkness that happens when mining.

Some of the "fake" lighting was coming from the water, so I had to place torches in the water to update it even.
![2018-10-28_22 28 22](https://user-images.githubusercontent.com/44342952/47627928-de3fb480-db00-11e8-9555-914c80195ce9.png)
