### ISSUE TITLE
Ideas for the new server.

### ISSUE THREAD

**Issue by watergod1234** [EarthMC/Issue-Tracker#531]
Yes! Thank you so much Fix and Karlofduty for listening to the community! Combat logging? Great! **War System**? Even better. This is a big step forward. Having two servers should make the time in the queue much shorter. 

However, there are some things with the execution that I would personally feel better if they were done another way. Of course, this is my opinion, I'm just listing my input and hoping it is heard.

**Firstly, factions:**
Although this does solve the issue of resolving conflicts through PVP, it hinders the whole point of the server. A geopolitical sandbox. Factions are just that, factions, they're too separated. Although you can make unofficial 'nations' through allies it just isn't the same. Nations being hubs for international trade will be demolished. Shops would be non-existent, you'd have to walk to them. And please don't try to fix this by adding TPA, just no. Many people agree with me on this according to the discussion I've seen on Reddit, discord servers, as well as other mediums.

Don't get me wrong, the functionality of war is great, it should just be executed differently. See my suggestion for how I think war should be implemented here: [https://github.com/EarthMC/Issue-Tracker/issues/444](url) 

**Secondly, standardization:**
The servers should be extremely similar if not completely identical to each other. If my suggestion of war days was implemented, it should be on both servers. Combat logging should also be on both servers. There are multiple reasonings for this: 

Firstly, the individual servers will, of course, have individual issues if they're different plugin-wise, but if they're similar then solutions could be implemented universally across both. This would make the workload on handling the servers significantly less. 

Secondly, is because I still want war and anti-combat logging on the main server. I've put literal days into it and it'd be a shame if I'd have to start again, along with many others, to experience these highly wanted features (which I've wanted on TN since I joined on its first day of release). 

**Voting:**
I don't know why this was changed it was perfectly fine before, though it's not really a big deal. I just think it should be reverted or nerfed. My boy Canuck got a trident from his first vote. 10 gold just always seemed like sufficient incentive to vote.

**Conclusion:**
The first two things would make the server absolutely perfect in my opinion. **Absolutely perfect**. I made this essay for this damn server because I care, and I'm concerned and excited for what's to come from this second server and to the network as a whole. Please, everyone, leave input to what you think about this below (especially you, yeah you, Fix and Karl).

**Comment by Skater2323** [comment]
I personally agree , Everyone on emc (not all but a majority) , have been wanting a system of a combat log plugin for the pvp side of earth mc . But I would just like to know why instead of putting it on Earth mc right of the bat but putting it in a beta factions server . Another thing is a war day concept or a war plugin system . I believe if one of these plugins was implemented into the server , it would bring the Earthmc community on there toes and have a reason to play the server .

**Comment by watergod1234** [comment]
I also posted this to the EMC reddit so more people could see it.

**Comment by Pengun78** [comment]
Ideas for the new server. #531

watergod1234 opened this issue 
about 1 hour ago 

Yes! Thank you so much Fix and Karlofduty for listening to the community! Combat logging? Great! War System? Even better. This is a big step forward. Having two servers should make the time in the queue much shorter.

**Comment by Magenent** [comment]
frankly if they are going to keep factions (which is a terrible decision btw(unless they announce that they will be brining towny war/proper politics)) they should at least add the combat logging plugin to towny since there isn't a downside and if its on factions clearly its not laggy or glitched

**Comment by Magenent** [comment]
Also yeah this is technically "earthmc" but its clear towny is the main server that everyone has spent all their time on, plus factions is pretty much the other side that towny is on right now, its just combat and war. Factions doesn't have as of an in depth political system as towny, plus the culture of factions is more raiding for the sake of raiding, I'm saying that we should bring some sort of war to towny instead of having it be either extreme lack of war or just war.

**Comment by FutureCW** [comment]
A huge issue about factions is definitely the inability to tp to major places. Most faction servers are played on maps that are less than like 40kx40k. Having an entire earth map would make raiding absolutely terrible for players as your whole raid squad would have to boat or run so damn far.

**Comment by KarlOfDuty** [comment]
Hello,

**1:**
For your first point, we wanted to make the new server a different experience to the old one as we could more easily accommodate players who would prefer something different from the current server, like using Factions instead of Towny which is one of the more common thing we get pinged about in Discord. Think of it sort of like how the paradox games look very similar and appeals to similar demographics but specialize in different areas. The Towny server may be likened with EU4 or CK2 while the Factions could be seen more of a HOI4 type thing, more specialized to war and a bit more simplified.

That being said, much of what we have put on the Factions server (except for Factions itself ofc) are things we are trying out and may come to the Towny server too. For instance the new voting system, combat log plugin and trade plugin.

We get that most of the regulars obviously prefer Towny as you are playing on a Towny server, but the Factions server may appeal to many of the new players who have no ties to the current one. This means there will hopefully be way fewer random new players filling up the queue to the Towny server when we open the Factions server.

**2:**
I have already touched on your second point but as the Factions server uses way less plugins than the Towny server it will likely be way more stable and have fewer bugs. Having two servers with the exact same setup doesn't mean they will have the same issues. Most of our problems only occur because very situational things happen, like a player using a specific command at a very specific time crating a contradiction in some database that the plugin developer hadn't anticipated for instance.

Regardless, this new server does not affect the Towny server in any way other than being a new kind of server to draw inspiration from by seeing what players like about it and being able to test plugins on something that isn't as fragile as the Towny server is.

**3:**
The voting system is definitely something we will be tweaking in the future both by editing rewards and by changing reward ratios. Right now it gives out slightly more gold than the Towny system on average and also a few items which can not be obtained on EarthMC normally. But again, it is a work in progress for now, but that's what the beta is for.

**Comment by NeonKrby** [comment]
;o a response

**Comment by watergod1234** [comment]
Thank you so much Karl for replying. You cleared up a lot of things. But for those who don’t wish to move over and prefer towny over factions, could there be something done about war for example what’s listed in #444? It’s definitely possible, it’s a good compromise, and very needed. Please just tell me straight out, yes or no? Please just consider it.

**Comment by KarlOfDuty** [comment]
I have answered that too in #532. It is something we are looking into.

**Comment by watergod1234** [comment]
Thanks so much for the blistering fast reply. I hope you consider war days.

**Comment by KarlOfDuty** [comment]
It is the most likely one to be used, yes.

**Comment by watergod1234** [comment]
HOLY SHIT I LOVE YOU RIGHT NOW. I know there’s not, and this is pushing my luck, but is there an ETA? Weeks? Months? Holy shit.

**Comment by KarlOfDuty** [comment]
No, I don't even know if it's going to be a thing at all, we will see.

**Comment by watergod1234** [comment]
Thank you so much. I will stop commenting here now.

**Comment by watergod1234** [comment]
If it doesn’t work in the future out just let me know why by commenting here.
