### ISSUE TITLE
[BUG] unable to deposit gold into bank

### ISSUE THREAD

**Issue by beepfromdiscord** [EarthMC/Issue-Tracker#545]
This bug was on the regular version of EarthMC.
the Issue is that i cannot deposit any gold into my town bank, despite being on the home plot, being mayor, and having gold on my person.
this is pretty clear to understand but how to reproduce:
1. type "/t deposit (number)
2. tells you "you do not have enough permissions for that command"
i expected the gold to go into my bank, which is irritating because my town isnt under full claim yet
please fix this asap
Thank you!

**Comment by ZestyPhallus** [comment]
Whenever you're having issues performing a command you'd otherwise be able to use, check to see if you're missing your [Nation:Town] prefix whenever you type in Global Chat.

If so, go into a nether portal.
No idea why it happens, all I know is when your nation prefix is missing, you might not have access to /res /t spawn or certain nation spawns, especially /t deposit

**Comment by WhitPlayzYT** [comment]
go into a nether portal or relog to fix it

**Comment by DasCodes** [comment]
**Duplicate** of #518.
