### ISSUE TITLE
Donator Only Servers

### ISSUE THREAD

**Issue by 32Lavenugly** [EarthMC/Issue-Tracker#576]
Many EarthMC veterans can agree that the server has gotten very boring.

Although the lag issue has gotten better, EMC has lost many features such as Blaze AI, /online, donator pluses, shop signs, but most importantly, mobs.
Combat logging has become a huge issue and is commonly growing, making PVP completely useless.
As old players leave, youtubers continue to make videos on EMC inviting new types of people. While that may be great for the server, it brings unwelcomed stress upon our mods.

EarthMC's original player base has either left the server, or have gotten bored of it. The remaining active veterans are donators who have lost most of the features they donated for.
If we donated to a server we enjoy and no longer have fun in it, why do we continue to support it?
Majority of the server is priority members and few donators now.

Instead of EMC donator days, why not an anarchy server for donators only?

A server to distract the veterans and to screw around on would be fun for mods as well so they can abuse us.
The server would clearly take no effort to make, downloading the Earth Map, and adding McMMO and a sethome plugin. This would offer donators a reason to come back. Starting over, but also raiding with no rules, Overall a new start but with a twist. There have been several versions of towny. All of them, you get your town, your gear, kill, and build. It's the same with the beta server, classic, and TN. Having a fresh start with no rules would bring a refreshing twist to the server.

**Comment by WhitPlayzYT** [comment]
would take too much time and money for another server

**Comment by DarkRush449** [comment]
It seems that their main focus is to make the server appear to to be awesome, due all the EMC staff favoring youtubers/media over the actual players, but keep it lacking in features so they don't have to due the actual work of maintaining a server.

**Comment by FutureCW** [comment]
I would like to have the key features back but not in this way. Donator only servers decrease town growth and many other key aspects of emc

**Comment by FutureLemon** [comment]
Donator only is just favouritism with extra steps.

**Comment by DasCodes** [comment]
Donors only mean it'll become solely P2W, which is never the plan. While donors already get huge priority over normal players, it would be really unfair to the normal players if new donors only server pops up.

Donors still have a `+` sign in front of their name and have access to `/online`. White shop plugin was taken down due to a duplication glitch, should be enabled in the next server maintenance.

We are still testing on how to improve server performance more, some features are automatically being disabled when the server is lagging to prevent more lag. But this does not mean they are permanent.

> due to most of the EMC staff favoring youtubers/media over the actual players

Everyone is treated equally, YouTuber(s) was given access to a few extra features because of the increasing amount of players targetting them and stream snipping, that is not fair to them either.

**Comment by Pengun78** [comment]
i have no + infront of my name or acces to /online and im a purple donor

**Comment by DarkRush449** [comment]
the plus was removed a long time ago from donars for some reason

**Comment by DasCodes** [comment]
They are temporarily gone because admins are redoing the ranks and staffs because of the new chat plugin.
