### ISSUE TITLE
[Feature] Distinctive rank for New donators

### ISSUE THREAD

**Issue by Ultil0l** [EarthMC/Issue-Tracker#603]
Please, Donator has been associated with veterancy, we could have a rank/channel for new donators so the older ones dont get forgotten for supporting the server since before the queue priority

**Comment by 32Benja** [comment]
Please do this

**Comment by BowShot118** [comment]
This is a great idea imo, a chat for people who donated because they enjoyed the server (mostly) instead of donating to get onto the server

**Comment by Ultil0l** [comment]
We want recognition! #donatorlivesmatter

**Comment by dakoko** [comment]
For a long long time the donor plus has signified knowledge which as helped us get the truth across to newer people with questions. Donor chat has become the last safehaven from monolinguals and nitwits, please don't take it from us. Make new donor's roles different!
#Donatorlivesmatter

**Comment by BowShot118** [comment]
^ This is actually so true. When I used to be out and about in General I was regularly dmed with people asking me questions because of my role. On one hand it shows that people don't trust the staff, and on the other it shows that people trust the longer term players and donators.

Keep them separate or risk loosing a large swath of trust in your donators by new players.

**Comment by shirazmatas** [comment]
Please attach more details on what these ranks would be called also.

**Comment by WhitPlayzYT** [comment]
Old donator = [Donator] New donator = +

**Comment by Ultil0l** [comment]
Putting this thread back on top to make staff notice

**Comment by KarlOfDuty** [comment]
I don't see a reason to add this gatekeeping to the server, and no matter where we would put the cutoff point everyone would ofc get mad because only they are the real veterans.
