### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JaVolimKatarinu** [EarthMC/Issue-Tracker#607]
Hello Staff team of EarthMC, I would like to ask a few questions regarding game mechanics on Towny server.

As we all know, lately there has been a lot of players constantly playing on Towny server which resulted in disabling several game mechanics. I believe that you all are working on the performance of the server behind the scenes, but it wouldn't hurt anybody to share some info on the progress of it. 

Recently cactus and sugar cane growth got disabled. Although, my sugar cane still grows just 1 block. **Is cactus growth same, just 1 block?** 

Tree feller has been disabled for a very long period. And the reason is that players used it to create lag machines. **Can we know something more about when it will return?** Because it is really slow to grind logs and woodcutting. Could there be some tweaking done to prevent creating huge lag, as lowering the amount of time tree feller lasts? Or at least enable it on some wood types. 

While mob spawning is "disabled" in Overworld, in Nether it works perfectly fine. And I have personally grinded a lot of gold swords from killing pigmans, even though they weren't supposed to drop gold swords. **Might be a bug if you forgot on it. My suggestion is to partially disable pigmans or to lower their spawn rates.** In exchange of that tps might rise a bit and allow animals and other mobs to spawn in overworld if possible. 

Dynmap hasn't updated for several weeks due to tps being very low for its time. **Can it be forcibly updated during maintenance or some other times, at least once a week?**

We all know that you have a lot on your plate with behind-the-scenes work and sometimes maintenance takes a few hours and after it finishes there is no changelog, nothing saying what was the reason of maintenance and what possibly got fixed. **Could you please try to announce if something impactful was resolved during maintenance?** Of course that you stay silent if some major bug was resolved that might still affect the server, **but some "non-fatal" things could be useful for some players.**

You recently increased the number of max residents in towns, and it is great that you did it. **Could you also increase the number of bonus claims from a nation?** It is not really required but would be nice to see that thing increase also. Our nation is currently having around 15 towns and we still get just 140 bonus claims. Not really sure how bonus claims are given with the number of towns, but maybe rearrange those numbers? Slightly increase the max, but give some bonus claims every 5 towns... Just an idea. 

I wish you all luck with further working on EMC, it is really fun to play on it. Some things are still missing, but we got used to it. Thank you for reading it, I hope we can all help with improvements to the server. :wink: 

Sincerely,
JaVolimKatarinu

**Comment by JaVolimKatarinu** [comment]
Also, I forgot, but this totally is weird for me and would like to know a bit more about why. 
**Why does it take several tries to destroy one block of obsidian and glowstone, even though that other blocks get destroyed from the first try?** For some reason, I need to destroy 2-3 blocks before that first block gets actually destroyed. And it is not the lag. I found this happening only on obsidians and glowstones.

**Comment by DarkRush449** [comment]
Sounds like block lag to me, especially when you mentioned obsidian.

**Comment by JaVolimKatarinu** [comment]
But why does it affect glowstone and obsidian and not affecting any other block?

**Comment by FutureLemon** [comment]
Cactus got disabled not sugarcane iirc. 
Tree feller being gone sucks and it would be epic to see it  on harmless trees like oak, birch and accacia.
Zombie pigmen tend to drop swords because the MCMMO salvage skill is disabled for gold armor & tools.
Dynmap does update frequently you just need to be in the area a lot in my experience.
They changed the player limit of a town to get more claims... Then why do you need more bonus claims just recruit. (Bonus claims work on the amount of people in a nation not towns)
About the blocks not breaking it's just blocklag nobody knows why slower blocks dont always insta break.

**Comment by JaVolimKatarinu** [comment]
My point is to not increase nation bonus claims, but "change" how it works. How much I have seen, there are few bonus levels, just. 10,40 and 140, if I'm not wrong. Maybe rearrange it to go like 10 for 5 and under towns, 60 for 10>x>5 towns, 110 for 15>x>10 towns, etc.. 

Can somebody from Staff give some answers, would like to see it as just confirmation that someone from Staff read it?

**Comment by FutureLemon** [comment]
> My point is to not increase nation bonus claims, but "change" how it works. How much I have seen, there are few bonus levels, just. 10,40 and 140, if I'm not wrong. Maybe rearrange it to go like 10 for 5 and under towns, 60 for 10>x>5 towns, 110 for 15>x>10 towns, etc..
> 
> Can somebody from Staff give some answers, would like to see it as just confirmation that someone from Staff read it?

Recently most staff are all fairly new players so I doubt they know detailed stuff like the scaling of NationBonus iirc it goes up by 10 starting from 10ofcourse.

**Comment by DasCodes** [comment]
While I already talked with Karl making a new channel to post changelogs for small little things, two weeks ago. However, I can not say there will be a channel for that. I do agree though, that it'll be a good idea to put small changes in a separate channel rather than putting in the announement channel.

Now about the nation bonus. Each resident gives you 8 bonus plot claims, so where you could only get 400 bonus claim from residents alone before, now you are able to get 200 more, 600 in total. That would be 740 claims. I find that reasonably big claim bonus for a town with 140 nation bonus and full residents.
