### ISSUE TITLE
[Feature] Spider-Eye Recipe Improved

### ISSUE THREAD

**Issue by XioanAskari** [EarthMC/Issue-Tracker#664]
**Is your feature request related to a problem? Please describe.**
Spider-Eyes are way too rare, Making it near impossible for the creation of debuff/negative potions

**Describe the solution you'd like**
A recipe for the spider-eyes that would be both a cheap yet expensive to craft.

Recipe Items:
8x Cobwebs
1x Eye of Ender

**Additional context**
Please find below a image of the recipe layout for the suggestion.

![Screenshot_2](https://user-images.githubusercontent.com/32355511/61750182-92265580-ad9c-11e9-88e4-f21b044cea9c.png)

(Please do not post "no" on its own to the idea if you dont have any feedback on the suggestion, ill just downvote the reply as it's useless trash talk.)

**Comment by WhitPlayzYT** [comment]
i think this recipe is too cheap tbh

**Comment by XioanAskari** [comment]
Do you think it needs more cobwebs or eyes? 8 eyes of ender like a spiders

**Comment by WhitPlayzYT** [comment]
That would be even cheaper

**Comment by XioanAskari** [comment]
Well spider eyes are meant to be common in a normal game so.

**Comment by ImperialFishy** [comment]
EMC is not a normal game by making this recipe so absurdly cheap you are removing all the value from one of the only valuable things left on the server

**Comment by XioanAskari** [comment]
Well I'm just saying it sucks since eyes are already rare as f

**Comment by SushiRoller** [comment]
Everyone whose only arguments are 'this is too cheap' or 'you're removing this item's rarity' should stay away from threads like these, you're not helpful. You think every recipe to be added must use the most expensive items, because you're selfish; if it was for you, every recipe would need gold blocks (let's waste everything we've got!).

'How could I be selfish, for not allowing players to get survival items that just happen not to be available thanks to server limitations?' is how you sound. Stop creating a false rarity that was never meant to be there, it's just what it is, a design flaw; if we can't have certain mob drops it's because there are design flaws that don't allow us to, such as the server being unable to spawn mobs when full.

Also, do you really think any of these recipes is cheap? Do you craft a double chest of prismarine bricks everyday? You sure do, you would say, but the reality is that if you focus only on one thing you can make stacks of only one item regardless o how expensive it is. Do you know what's actually cheap in this server? Blue ice; I don't see everyone complaining about it having to be 81 ice blocks for a blue ice block, which is how I think it must be, just like in vanilla, because not everything in vanilla is easy to get nor extremely hard to get. Getting elytra is easy, getting shulker shells is easy (limited, but easy), and let's not talk about some silly spider eyes. Why must it be any different here?

About the recipe suggested here, I think it may be a good idea, and the recipe is fine; however, the only thing that doesn't convince me is the crafting recipe itself, it personally sounds quite strange being able to craft a drop, it's like being able to craft rotten flesh.

My suggestion? Well, I'm surprised by how little advantage has been taken from plugins like McMMO, which can be easily customisable to give players items like this. We could've had other items like chorus fruit to be able to craft end rods normally like from way before if it was added as an excavation reward for players with over 950 excavation level (just an example). So I would take a look into that instead of using crafting recipes for mob drops.

**Comment by XioanAskari** [comment]
The recipie i was mainly suggesting that the "eye" is a core piece and the cobwebs are used to make it refer to the "dna"  guess of spiders? im not sure

Thanks for the feedback tho susihiroller, glad to see some people with big brain time.

**Comment by WhitPlayzYT** [comment]
I agree with sushi, it should be a custom mcMMO drop not a recipe tbh, and the reason I say the recipe is too cheap is because the server doesn't need people to be spam making invisibility, poison, slowness, weakness ect. potions

**Comment by WhitPlayzYT** [comment]
Cus those potions are more useful in EMD than vanilla

**Comment by SushiRoller** [comment]
You've said it yourself, those potions may be more useful here than in vanilla, because even though some of them work well for certain situations in a vanilla game, this server is also combat focused; however, I still don't see a reason to limit the ability to brew them. 

A potion that is already useful in vanilla is weakness, which you need in order to heal a zombie villager, and you need a fermented spider eye to brew it. Probably the most useful of all the potions you can make with spider eyes for this server is invisibility, but it already has got a limitation, which is the usage of a golden carrot.

As for potions that are useful for fighting with other players, well, if you think potions like poison and weakness are bad, I remind you there's worse that come with McMMO like potions of nausea, hunger, blindness and decay (Wither, aka mortal poison), and all of them are easy to brew once you reach the required level. So, if you, as a combat focused player, cannot deal with other players using vanilla potions, I would recommend you to play more 'pot PvP' and classic UHC games.

Lastly, you're forgetting the main reason why we can't get spider eyes right now, which is because the server is not able to spawn mobs in the overworld when full, it wasn't an intentional balance. If we could have mobs regardless of how full the server is, people would get spider eyes way more easily than this or than using any custom plugin, just as it happens when the server isn't full.

**Comment by DasCodes** [comment]
As mob spawning is enabled, this shouldn't be necessary anymore.
