### ISSUE TITLE
[Feature] An API endpoint to get data from towny

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#683]
It would be great to get an endpoint that programmers could access to get information about the nations, towns, and users on the server. There is no functional search feature to search for things like "towns that have no x people" ,"towns that have over x gold in their bank", "nations that have over x people total", and so on. Having an API that gives access to nation, town, and player data would allow people like myself to create applications to search through this data in a more effective manner.

**Comment by JaVolimKatarinu** [comment]
If you arent watching Towny devs, you would see that many of them are doing this as a hobby with managing a server too. So asking for a sorting API for your personal gain isn't going to get you what you want. 
But anyway, this isn't EMC issue, this is an issue for Towny. 

But I'm in a good mood, so I could point you somehow.
Towny plugin is connected to our economy plugin and you can easily search it up with /baltop. It will give you info about every town/nation that has any gold in their bank. But before you do that, know that most towns and nations, don't keep their gold in the bank. Because they give Councillor/Chancellor rank to somebody else, and somebody else is able to steal their gold. 

Nations that have xx people, xx towns are easily seen in /n list, where nations are sorted by the number of people in their nation.
And if you are interested in the area what each nation has officially claimed, then you can use EMCL bot for that. Even though that bot doesn't take data from Towny, but instead from DynMap, doesn't really make much difference. 
I don't see what more info sorted out you need. Actually, all data is quite available and you just need to do it yourself.

**Comment by johnyuki** [comment]
Was just suggesting it, chill. I know that they do it in their spare time, but this page is literally here for people to make suggestions, and this is just a suggestion. 

I mean, sorting the data from the database in to a downloadable json file isn't really difficult. It could be updated once or twice a day. Doesn't need to be anything fancy.

**Comment by ZestyPhallus** [comment]
JaVolim's chill, idk what you're going on about. 
I think you should code this yourself since you obviously know what you want.
If not, Volim's provided plenty of alternatives to achieve whatever it is you're up to.

**Comment by ZestyPhallus** [comment]
JaVolim's chill, idk what you're going on about. 
I think you should code this yourself since you obviously know what you want.
If not, Volim's provided plenty of alternatives to achieve whatever it is you're up to.

I don't think CFH or Karl can be fucked to drop what they're doing to appease one weirdo's ambition.

**Comment by johnyuki** [comment]
He came on a little strong is what I meant, when all I did was suggest something. 

And now you are coming on even stronger. Why are you insulting me for just making a suggestion lmao.

**Comment by Warriorrrr** [comment]
Zesty never said anything to insult you or anything offending, Javolim was trying to help you and never came on strong. You should appreciate it that people take time out of their day to help you, and it's very clear that you're trying to make an automated town fall chart so you can earn gold easier, from both this issue opened, and the one you opened before this one.

**Comment by johnyuki** [comment]
"Zesty never said anything to insult you" - He literally called me a weirdo for making a suggestion. Quite literally an insult. Also at what point did he try to "help" me? He said absolutely nothing that could even be construed as advice. He said that I should code it myself, and then called me a weirdo. Fantasstic help that is. 

Also, that is one of the many things I wanted to do. Having more flexibility with search parameters is the main thing. I most enjoy the economy aspect of the server, so having these flexible search parameters would be nice, which is why I suggested this idea.

**Comment by ZestyPhallus** [comment]
I didn’t directly call you a weirdo but if the shoe fits, help yourself. 

Considering what warrior said, having staff go through the trouble of setting up a town fall chart for you is ridiculous. 

At most, the practicality of this would be a death timer for towns and it seems to be primary function you’re going for. 

How else could this be useful? For what other reason would you want an endpoint to create an app that lets you search through town/nation/player data with ease?

EMCL bot works fine off dynmap.
/res /t /n commands are superb as well.

**Comment by johnyuki** [comment]
"I didn’t directly call you a weirdo but if the shoe fits, help yourself." - Man you literally said "to appease one weirdos ambition". You very directly referred to me as a weirdo. How the fuck can you even deny this lmao.

Also, I don't need to justify to you why it would be useful. I made a suggestion as I thought, as a programmer, it would be a fun thing to play around with. I could make some discord bots, leaderboards, etc. Lots of things. 

If you dislike that then that's fine, but I don't see any reason why you are opposing it as strongly as you are. If you dislike it then state why you dislike it, thumbs it down, and move on. This is a forum to make suggestions, regardless of how "useful" they are to the general population of the server.

**Comment by Sabatarge** [comment]
bruh moment

**Comment by KarlOfDuty** [comment]
Data can be gathered live from the dynmap's jason data.
