### ISSUE TITLE
[BUG] /f checkpoint randomly teleporting and not teleporting when command is run.

### ISSUE THREAD

**Issue by anotherplayerofEMC** [EarthMC/Issue-Tracker#688]
**Server**
Factions

**Describe the bug**
The /f checkpoint or /f checkp command is meant to teleport the player to the checkpoint (after 10 seconds). Most of the time you need to try many times to actually teleport. However, when playing the game randomly players are teleported to their faction checkpoint with no command or reason.

You do not need to have previously used /f checkpoint or /f checkp to be randomly teleported, as far as I know.

**To Reproduce**
Create or join a faction with a checkpoint set and just play the game. You will be teleported with no command or reason.

**Expected behavior**
To not be teleported.

**Screenshots**
N/A

**Additional context**
This is urgent as people are calling others hackers when this happens, and players are in combat.
Usually combat log prohibit teleportation, as it works if you try to use /f home or /f checkpoint or /f checkp in battle, it does not allow you to. Unfortunately the random teleportation to the faction checkpoint still does occur.

Also, when playing the game you are also radomly teleported and this makes it very nnoying and hard to get back to where you were, and like in my case if you are teleported over 4k blocks from where you were before...

Thank you for taking your time to read and understand this.

**Comment by CasperFactions** [comment]
and im gonna get banned for that
karlofduty

**Comment by AlphaiaCP** [comment]
NEW UPDATE: Also, similarly to saving /f home's coords, please save /f checkpoint or /f checkp's coords when the server restarts. This stops us from having to reset it again.

**Comment by AlphaiaCP** [comment]
Please update to https://www.spigotmc.org/resources/savagefactions-the-ultimate-factions-plugin-1-8-1-14-2-0-beta-released.52891/reviews?page=4

**Comment by KarlOfDuty** [comment]
As I told you in your support ticket, we are already using the latest version.

**Comment by docwhomc** [comment]
Because my faction doesn't have a checkpoint set (there server doesn't seem to want to let me set it even though I'm leader) I'm not sure if I'm experiencing the same issue or not, but I'm at least experiencing a similar random teleportation issue.

In one instance, I was randomly teleported just as I was about to claim territory from another faction who's power was below its number of claimed chunks.  In the time it took me to get back to the factions territory, someone else (who I'm guessing noticed me on the dynmap when I was trying to claim the chunks) swooped in and took several of the faction's chunks, including the one containing their main storeroom.  To add insult to injury, the faction that swooped in then unclaimed the chunks they had just taken, which I would have liked since they are not too far from my base.

**Comment by docwhomc** [comment]
That was the first time it happened to me; it has happened several times since.

**Comment by AlphaiaCP** [comment]
Karl I got banned by Shirazmatas because he is unfair and lied. Tell him and I would really like if you, a good mod decided and was fair to me. Thanks.

**Comment by KarlOfDuty** [comment]
Fixed.
