### ISSUE TITLE
Armor Stands Dieapearing

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#692]
**Server**
Factions

**Describe the bug**
Armor stands disappearing in claims.

**To Reproduce**
1. Place armor stand in world.
2. Wait.

**Expected behavior**
Armor stands should not disappear or despawn if not interacted with.

**Additional context**
The armor stands were inside a base.  The walls are still intact.  I am one of only two players in the faction (with requisite perms to remove the armor stands) that were online between when I last saw the armor stands and when I came back online to find them missing.

This has happened before, and I have no reason to believe that it was someone in the faction or an ally messing with us.

**Comment by JaVolimKatarinu** [comment]
Armor stands in Minecraft behave like entities, meaning they have attributes of a mob. This usually happens if some plugin starts to remove entities from a chunk where there is a lot of them, other words MobSpawner. 
My advice is to not place it in that spot since there is overload apparently. Try to place somewhere else, or don't place it at all.

**Comment by docwhomc** [comment]
Any idea what the threshold is on EMC factions?

**Comment by KarlOfDuty** [comment]
Fixed.
