### ISSUE TITLE
[Mechanic] Nation tax

### ISSUE THREAD

**Issue by ImperialFishy** [EarthMC/Issue-Tracker#696]
Today i checked /towny universe just to see there is a total of 226 nations on EMC. This is ridiculous. I then went on the map to see where all these nations are and most of them had one or two towns. I understand nations need time to grow but some of these nations had 1 person who has been the "nation owner" (which btw is a disgusting term) for a long time and i mean months but they only log on to keep it from falling. 

I suggest the reintroduction of nation taxes. This was 6g daily back at the start of TN and i believe this to be a reasonable amount. This will make people think twice about making or "buying" a nation as they need to factor in the running costs. I have asked some people what they think of this idea and the only people who have been opposed to this are people who "own" a nation on their own. 

I hope there will be some relevant discussions on this topic and that the staff will consider my request.

**Comment by Ukai-Oita** [comment]
I am extremely surprised this feature was removed. It seems essential. I think 6g might be a little high (3g would probably be fine), but some kind of daily extraction is absolutely necessary.

You get 10g per day from voting if you're active. You could theoretically maintain a nation by yourself if you wanted to. This is MORE than fair.

**Comment by FutureLemon** [comment]
+1

**Comment by DeadGlamour** [comment]
I dont really understand how it will be useful, like even if a nation falls, it wont remove the inactive towns

**Comment by ImperialFishy** [comment]
The point is to limit the amount of one town nations because nations should be a team effort not one guy thinking he is so cool cos he has a "gold" name. Also if you are concerned about the amount of towns i can propose a town tax but i didnt think its necessary because having towns fall after the 42 day timer is reasonable in my opinion. My suggestion is not aimed at towns at all please consider it in the context i have given.

**Comment by FutureCW** [comment]
226 nations and over 1900 towns are on EarthMC. 120 player count and 1900 towns...
Last time I checked, around 50% of those towns had 1 person in them. Towns are also a problem because a majority of the new players have the same idea of making their own town instead of joining one because it’s an earth map. They end up going inactive while getting the 64 gold because they’re bored, or stay as a 1 man town, but they only log on so it doesn’t fall

**Comment by CorruptedGreed** [comment]
I agree with the reimplementation of this mechanic. It would relieve the server of a lot of inactive nations.

Another possibility would be adding town taxes (probably at 1 gold). This would make sure people don't log in once a month for 2 minutes in order to keep towns up in locations that may be desired by other active players. In general this should open up lots of space for new towns/nations, making the server more appealable to others (i.e. someone quitting because an area they wanted to settle was occupied by a 1 person inactive town).

+1

**Comment by FutureLemon** [comment]
Oldfags unite! Newfags can't pay for nation upkeep (still ly newfags <3)

**Comment by Lagann311** [comment]
The meaning of nation has become completely worthless with so many existing today.. The nation prize has already increased months ago right? If I remember correctly Fix said he wanted it to be a „team effort“ to create a nation, but this change hasn‘t really affected the issue much. About every second day a new nation gets made but old ones disband much more rarely. Most of these nations only consist of 1-3 towns for the rest of their existence. This issue has been adressed already, so I‘m asking the staff team to do it once again regarding the seer extent of it today.
Please add nation taxes, it would improve the server a lot.

**Comment by T0rn4do** [comment]
If you add a nation tax, the creation price shouldn't be so expensive.
I think that 500g for a nation and a 4g or 3g daily tax would be fine.

**Comment by ThundorLord** [comment]
I agree, we definitely need a nation tax, but for town tax, maybe they could implement something that's means the King chooses what the town tax of their nation should be, and that amount will be taken from all town banks and put into the nation bank. Kinda like how ordinary taxes work, but from towns Bank to nation bank.

**Comment by w0265261** [comment]
WE need nation upkeep look at canada it's been nothing for the last 12 months

**Comment by KarlOfDuty** [comment]
Nation taxes don't really reduce the number of nations by any noticable amount unless they are very high, at that point they just cause issues instead though.
