### ISSUE TITLE
[Feature] /warp freesand

### ISSUE THREAD

**Issue by imabritishcow** [EarthMC/Issue-Tracker#699]
**Is your feature request related to a problem? Please describe.**
I keep getting killed for mining sand and its getting harder to find new spots. The towns in the sand areas also dont like people mining it.

**Describe the solution you'd like**
We need a way to get sand that doesnt grief the sand areas. I have seen /warp freesand on many servers and i think it would be good for EarthMC. A /warp freesand is a big area that is filled with sand that players can mine.

**Additional context**

**Comment by ZestyPhallus** [comment]
If you have an issue with getting sand, I recommend buying it.
If there was a /warp freesand, I would honestly consider that a /warp pvp and no one would get sand.

**Comment by imabritishcow** [comment]
There would be no pvp in the /warp

**Comment by ZestyPhallus** [comment]
How do you reckon they'd achieve that?
No pvp, but you can alter terrain yeah?

**Comment by imabritishcow** [comment]
They can, i used to be a server owner.

**Comment by ZestyPhallus** [comment]
Good for you little guy, must be a reason that's past-tense.

Your idea smells, if they disabled pvp, we can still find a way to kill you.
They wouldn't add a /warp freesand when an entire continent is full of it. 
Don't be a baby. Dig sand in wild with your blocks out like the rest of us.
Getting hunted while digging sand? Buy it.
Hotel? Trivago.

**Comment by riri2010** [comment]
I think there have been posts here in the past about adding a "Mining Dimension".
a mining dimension would solve a lot of issues.
1. no more sand grief or grief terrain grief of any kind (ideally)
2. second dimension can run on a different thread/cpu meaning more resources for the main server while players are in the sand dimension
3. A safer place to mine surface resources (assuming there would be no dynamap)

**Comment by riri2010** [comment]
I have seen posts here in the past about adding a "Mining Dimension"
the main benefits I can think of are:
1. way less sand/terrain grief (ideally)
2. A second dimension could run on a separate thread/cpu. this should free up resources for the main towny server
3. A safer place to mine surface resources. (assuming there would be no dynamap)

**Comment by ZestyPhallus** [comment]
1 is no longer an issue since Karl updated rules to allow mods to repair grief even if it's in wild, just to restore terrain integrity.

2 would open up a lot more possible issues like inventory getting cleared upon entering different worlds, or possible dupe bugs. _[ The cons outweigh the pro's when you have a 1:500 world with plenty of resources but people are just lazy. ]_

3 if we wanna make a separate world just to provide a safe space, I recommend playing creative.

**For legal reasons, EMC, I'm joking. Please don't make a creative server, we just want a functional anti-combat log plugin pls 10q.**

**Comment by imabritishcow** [comment]
ZestyPhallus some people dont like pvp

**Comment by ZestyPhallus** [comment]
Then fuckin' **GIT**

**Comment by riri2010** [comment]
so in response zesty
1. I know that Twitchy has been waiting a long time to get the sand grief repaired around the numidia capital
2. this is a good point. im not sure how the technical stuff would work. it might be difficult to implement aswell
3. I agree, pvp should be enabled. it would be no different than mining underground (hidden from dynamap.)

my main issue is with the sand grief. some places look terrible and the issue will keep repeating itself after a rollback.

**Comment by ZestyPhallus** [comment]
yeah, I know truemoo's also had an issue with that in Sudan.

I recommend locking up your nation spawn and only allowing allies to exit, or just closing it when you're offline.

**Comment by FutureLemon** [comment]
There are plenty of ways to not die from sand mining. I 100% agree with Volzeran all of you are just lazy snowflakes that can't handle looking at a dynmap that shows people comming.

**Comment by DeadGlamour** [comment]
Tbh sand griefing is a problem, I am from numidia and I keep killing those sand miners and get rollbacks but nothing helps, but since they are not going to add a sand warp (tbh if theyd make a new world for reasources why limiting it just for sand) just go far away from the towns and cities and mine there

**Comment by tomatochip** [comment]
Mine sand in Numidia, and we get rid of ya

Anyways, I don’t really see the need to add this. Yes, it would be convenient to have unlimited sand, but it would make things too easy and too complicated. The only reason that I yeet sand miners on a daily is because Numidia has been waiting for months with multiple tickets asking for large scale terraforming grief to be rolled back, and the damage keeps getting worse. It would be one thing if the miners had respect for the land (which is not exposing any stone or making huge sand craters), but we somehow need to enforce this in order to keep our nation’s land from being destroyed. 

Anyways, it would also be nice if the mods gave more warnings for terrain grief.

**Comment by Ra2orLeaf** [comment]
Just no /freesand

**Comment by Aitonater** [comment]
If you are going into the wilderness to gather ANY resources you must participate in the risk of dying that comes with. If you don't like pvp then you are doing it wrong. Use one days voting (10 gold) and see the fuck tonne of sand it can get you. 

As for the sand griefing in Africa, I think that should be a separate issue altogether that focuses more on the effectiveness of tickets and staff when fixing griefs. I dont think it's the same issue as wanting a warp and the first ever warp on EMC just to get... sand... not even the end or anything else... sand.

**Comment by CorruptedGreed** [comment]
There are already huge expanses of areas to mine sand at.

Adding a new "sandbox" region would draw away from the aspect that everything is created with the resources on the main world.

**Comment by DasCodes** [comment]
We'll not be enabling `/warp`s.
