### ISSUE TITLE
[Suggestion] Stop crippling vanilla

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#729]
**Is your feature request related to a problem? Please describe.**
In order to reduce lag, various aspects of vanilla have been nerfed on EMC such as mob spawning and breeding (throttled or disabled), hoppers (turned to stone), and (possibly, I haven't gotten confirmation that this one was intentional) mob spawners (turning to air).

**Describe the solution you'd like**
Find a way to address the lag without crippling major aspects of the game.

From what I've heard, it seems that some of the plugins are significant lag contributors.  Perhaps, consider scaling them back.   For instance, I'd be happy to trade the dynmap for being able to have mobs.

Maybe reduce server slots even more... even if it would move the towny queue from frying pan to the fire... unless the player base can be divided between more servers... maybe add a regular vanilla one (i.e. without towny and factions) or an additional towny server (since the addition of the factions server doesn't appear to have alleviated the towny queue issue as much as we all may have hoped).

At the very least, please try and find less destructive ways of reducing lag.  For example:
  * Instead of turning hoppers to stone, just make them stop collecting and ejecting items or slow the rate at which they do so.
  * Instead of setting the mobs per chunk limit, maxEntityCraming, etc. to absurdly small numbers (without prominently posting it somewhere), resulting in the accidental death of what few mobs are there to be found, have the anti-lag plugin turn off their AIs when TPS drops to low.

**Comment by LavishNick** [comment]
Agreed

**Comment by docwhomc** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/485#issuecomment-486479908

**Comment by docwhomc** [comment]
[Changes to the Dynmap](https://github.com/EarthMC/Issue-Tracker/issues/486)

**Select Quotes**

RangerMK01:
> 1. What possible ways could the dynmap be changed for better performance?
> 2. How much would these affect performance?
> 3. Would you be willing to carry through with these changes if a significant portion of the community voted in favor?

RangerMK01:
> Fix literally said himself that the two biggest consumers of processing power were the towny plugin and Dynmap.

Karl:
> We will not do either of these things, they will likely not affect performance by a noticeable amount.

**Comment by docwhomc** [comment]
[[BUG]/["FEATURE"] Hoppers turning to stone and ejecting their contents #720](#720)
[[BUG] / [''FEATURE''] Spawners turning into air #727](#727)

**Comment by FutureCW** [comment]
If you want a new towny plugin then suggest one

**Comment by docwhomc** [comment]
I'm not saying we need a new towny plugin... I've heard that fixing the ineficiencies in towny would require a total rewrite.  Though if there is a better optimized plugin with similar functionality out there, switching could be a potential solution.

**Comment by johnyuki** [comment]
Dynmap is definitely going to be a major contributor. There will almost certainly be a way to scale that back without getting rid of it. For example the main aspect of it is just seeing where towns and players are. We don't need the blocks to be updated every like 15 or 30 minutes or whatever it is. Block updates can be done once or twice a day or something. 

Another thing is pre-loading the world if it hasn't been done already. When I had a small server for friends, it was really laggy when people were exploring due to loading the new chunks. This lag was almost completely nullified by preloading the world using worldborder (which is already a plugin on the server). If the world hasn't already been preloaded, then I wouldn't be surprised if people exploring the world and loading new chunks is where 90% of the lag is coming from. 

Obviously we don't know what is causing the lag, we can only guess, but if plenty of other large faction servers can manage, then there is no reason why this server can't.

**Comment by JaVolimKatarinu** [comment]
If the world wasnt preloaded, then you would have empty chunks on dynmap..

**Comment by DasCodes** [comment]
The server is vanilla with some plugins like Towny, Essentials, Dynmap, mcMMO, etc. It's not like we have slowed the server performance intentionally, we do definitely want the server to run as smoothly as possible and as much as you want. Dynmap is one of the main features of EMC, we will not be removing it.

Mob spawning has been reduced to none to improve the server performance. Yes, reducing player slots is an option but that is a decision for admins to make. About the recent hopper and spawner issue, it was a plugin which was a bit aggressive on hoppers and spawners, but it should be fixed now.

If you really want the pure vanilla, that's not gonna happen on this server, as this server is Towny server. Mob spawning issue is something else which is related to performance issue.
