### ISSUE TITLE
AUTHORISATION NEEDED FOR 2 ACCOUNTS

### ISSUE THREAD

**Issue by SarahBu09** [EarthMC/Issue-Tracker#733]
Hello there,

We are two players in the same house and a friend of mine told me that you will think this is a break of the server rule : 1.4 Alternative accounts because of the same IP address.
SarahNairobi and Thronecore. 
Actually I'm playing with my 10 years old son.

Can you please give us an authorisation ?

Regards,
Sarah

**Comment by DasCodes** [comment]
It's fine to play on the same IP, we don't necessarily ban players just because they share an IP address. We only IP ban players with a hacked client and if we have reason to believe some banned player is playing on the same IP address. Also, this is not our support platform, please use our support discord sever for support related questions and stuff, which can be found on EMC's #info channel.

**Comment by SarahBu09** [comment]
Sorry for the wrong platform and thx for the answer

**Comment by DasCodes** [comment]
No problem.
