### ISSUE TITLE
[Feature] add chorus flower crafting recipe

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#746]
Right now there is no way to get chorus fruit, flowets or even purpur block, this can all be resolved by adding the chorus flower, you could farm it using the flower and endstone and then burn the chorus fruit and craft purpur blocks, here is how I suggest it to be crafted
![Screenshot_20190831-164858_Chrome](https://user-images.githubusercontent.com/53373440/64065424-2f836d80-cc16-11e9-88aa-4c3548d8c327.jpg)

**Comment by JaVolimKatarinu** [comment]
Beetroots can be farmed, but ender pearls and oxeye daisy are quite uncommon and a bit expensive then beetroots... 
I support this. ;)

**Comment by WhitPlayzYT** [comment]
+1

**Comment by EchoOcelot** [comment]
I support

**Comment by EchoOcelot** [comment]
I support this

**Comment by Highlander214** [comment]
+1

**Comment by Aitonater** [comment]
+1

**Comment by Cactusinapumpkin** [comment]
This recipe would be rendered useless because people would eventually just sell chorus flowers. 
one thing to worry about it large scale auto farms because you know people are gonna want to make a lot of purpur blocks like me, I would love the introduction of purpur blocks. You can get a lot of ender pearls from fishing and clerics too, The oxeye daisy is probably the rarest item unless you know a flower person that sells.

**Comment by DeadGlamour** [comment]
1. I am well aware of it becoming useless, but I just want to have access to purpur blocks, but if it really bothers you another option is changing the recipe to 1 ender pearl and 8 beetroot for 8 chorus fruit.
2. Flowers are easy to get, just bone meal land in flower forests (there are some in europe).

**Comment by Prismary** [comment]
As already mentioned, adding the recipe would be pointless, it's down to the question of whether chorus should be available on the server.
