### ISSUE TITLE
[Bug] Active towns disappearing

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#759]
**Server:** Towny

**Describe the bug**
Active towns' plots are being unclaimed.  The towns still exist but without claims.

**To Reproduce**
This is currently unclear.  One report received so far indicates that the disappearance of the towns coincided with a server reboot.

**Expected behavior**
For towns to not disappear, unless all players are kicked for 42 days of inactivity.

**Comment by Alexandre1868** [comment]
This bug happened as of 09/09/2019

This morning, at 03:18 AM PST, the server went down for a maintenance update regarding towny commands and the economy plug-in.

After the server went online again, the town, knows as Kristiansand, disappeared. The owner claims to not typing /t delete or any command similar or in the sorts that are able to delete the town. 

There are a total of 4 members in the town, and all 4 of them were active, as they were on the day before the restart, and got off for the night. 

This bug is very rare and has only happened to a couple of towns.

**Comment by FerraAvirail** [comment]
Complete same problem. Calafate (capital of Patagonia) just disappeared, I realised it when I did /t spawn and it said I was in wilderness. Another player (reptiluracs) used this exploit so he could steal stuff from town without problem. He killed me multiple times. Karl repaired some chunks of town, but not all sadly :(

**Comment by Myamdane** [comment]
The exact same thing happened to me. Nurnberg, a town of Eastern Germany had all of its claims erased. I believe it had 27 chunks of claimed area before the issue happened. 

Mayor: Jamesfrompolska (contact Myamdane#0224)
Nation: German Empire

**Comment by KarlOfDuty** [comment]
It is likely related to a new build of towny I tried out for a bit during that maintenance, if this has happened to anyone after that maintenance please contact me.
