### ISSUE TITLE
[BUG] Changing the town spawn

### ISSUE THREAD

**Issue by xtremedragonz** [EarthMC/Issue-Tracker#763]
I'm having issues changing the town spawn. A couple of weeks ago, a moved the spawn as I was altering the original spawn and it could cause issues if people try to spawn. When i tried to move it back later on, it told me it was too close to another town (which is fair enough as it was). So then i tried to move it to two other locations, one of which was on the edge of the town but no other towns are near this plot and the other is in the middle of the town, yet it still gives me the same message about being too close too another town. Not sure why this is happening.
![emc bug 1](https://user-images.githubusercontent.com/55329281/64912539-be20e000-d728-11e9-95a6-8fae3a4fccb6.jpg)

**Comment by JaVolimKatarinu** [comment]
Which town, can we take a look through dynmap?

**Comment by xtremedragonz** [comment]
Oban, North West of Britain

**Comment by JaVolimKatarinu** [comment]
Oh, Britain. Well, that might stay a problem for you, since almost the whole of Britain is claimed and everywhere is a town nearby.
![image](https://user-images.githubusercontent.com/41012732/64913445-a48b9280-d740-11e9-9939-b9a46b5569b8.png)
Try to place your spawn on those 2 places, looks to me like the most further point from any nearby town. 
If that doesn't work, try asking a mod to move it for you. Not sure as I'm not seeing the available command, but maybe their wiki is outdated.

**Comment by DasCodes** [comment]
How far was the spawn from another town claim? @xtremedragonz

**Comment by xtremedragonz** [comment]
The original spawn or the new spawns i wanted?

**Comment by DasCodes** [comment]
The one you wanted but couldn't.

**Comment by xtremedragonz** [comment]
To the left of where the shop is

**Comment by DasCodes** [comment]
Yeah, there is a limit that the spawn has to be away from another town claim. But I don't remember what's the number. I'll tag @KarlOfDuty if he remembers.

**Comment by xtremedragonz** [comment]
Thanks

**Comment by KarlOfDuty** [comment]
Yeah, that is nothing we can do anything about sadly.
