### ISSUE TITLE
 [Feature][Plugin][Mechanic] Mining needs to be fixed

### ISSUE THREAD

**Issue by Scorpionzzx** [EarthMC/Issue-Tracker#801]
**Is your feature request related to a problem? Please describe.**Haste 2 potions no longer work as they used to after the lag was fixed**

**Pure gold**- By pure gold, I am referring to gold produced from pure ways such as voting or mining. (Gold given by players or made from shops is gold already in circulation).

Why is this the lack of pure gold a problem? Because people use gold to make town claims or nations and the gold already in circulation will soon be eaten up by towns and nations. Before the lag was fixed and the server limit was increased you used to be able to mine with haste II potions and they would last super long (about 10 mins give or take) and you could make a lot of legit gold using this method. However, without the lag, the haste potions now last the normal amount of time. This reduces the amount of pure gold that can be obtained on the server with the exception of voting. Without this key lag mechanic, the server is now limited in the amount of pure gold you can obtain and reduces the amount of chunks towns can claim.  

Yes, this may mean fewer nations being made however, this also means that with less pure gold circulating we will have smaller towns. The only other way to get pure gold is from voting and that does not give you enough money to barely claim a couple of chunks of a town per week.

 This will also reduce the activity of players... **I ask you this 1 question**...If you can get the same amount of gold for voting as you do for mining for half an hour then why bother playing every day if you have to spend 30x as much time as you can for a simple vote? Why bother making a town if its gonna take 2 years of vote gold or constant mining every single day for months just to get a city like a town? Not to mention gold needed to buy a nation or the other items such as god tools and building materials.

**Describe the solution you'd like**
We need double drops and double smelt for gold turned back on at the very least... If it's possible maybe make haste potions last 15 mins as they used too. (Adding more vote gold is not a solution although it may help) Like I said in the above paragraphs vote gold is good however it does not promote activity or grinding.

**Additional context**
I did a mining run after the lag was fixed with about 30 haste potions and got about 70 gold. When the lag was still a think I could get about 100g per 18 potions (give or take). I got almost half the loot( including emeralds and diamonds) using twice as many haste potions.

**Comment by T0rn4do** [comment]
What you say is interesting but the economy on eath mc sont work like that lemme explain,
If you vote everyday, ok you ll need to wait a lot of time before getting a nation.
But if you vote and mine you ll get double gold (everyday i make around 20g)
Also if you need haste potions, just brew a carrot if you are lvl 125 in alchemy.
Then about shops,people can sell something like bricks (idk why bricks) so they sell it in their shop so other people can buy them it s like irl. 
So if you want to get more lag so you can make more "P U R E" gold then think about builders and other functionnalities wich wont work with lag, like brewing haste potions or having more players on earthmc, so résidents who are gonna spend gold etc etc so think about that before writing a text about how you can get more gold.

**Comment by WhitPlayzYT** [comment]
There's just no need for this, the server gold influx is fine the way it is

**Comment by johnyuki** [comment]
The economy is already trash enough as it is, we don't need to add in gold inflation to that. There is enough gold coming in to the game already as it is. With just 1 day of voting, and then mining diamonds, emeralds, and gold until you get another 6g (which only takes about 20 minutes max), you have enough to claim a chunk. That's plenty. 

With one day of voting gold you can get almost a full god armour set. With one day of voting you can get a full set of the important god tools (pickaxe, sword, spade). You can also buy most things on the server in one or two days of voting, there is simply no need to add more gold in to the game.

**Comment by Scorpionzzx** [comment]
> The economy is already trash enough as it is, we don't need to add in **gold inflation** to that. There is enough gold coming in to the game already as it is. With just 1 day of voting, and then **mining diamonds**, emeralds, and gold until you get another 6g (which only takes about 20 minutes max), you have enough to claim a chunk. That's plenty.
> 
> With one day of voting gold you can get almost a full god armour set. With one day of voting you can get a full set of the important god tools (pickaxe, sword, spade). You can also buy most things on the server in one or two days of voting, **there is simply no need to add more gold in to the game.**

How is gold inflation bad?  Not all shops will buy diamonds. and... We are not adding more golf to the server... This was a mechanic since the beginning of the game

**Comment by Scorpionzzx** [comment]
> There's just no need for this, the server gold influx is fine the way it is
 
This is a good point however, I feel that putting the economy aside... How are players going to grind for gold if it not even close to as effective as it was before? Shops and voting are very passive things but what if someone wants to put in the extra work and actually grind for their gold?

**Comment by Scorpionzzx** [comment]
> What you say is interesting but the economy on earthmc wont work like that lemme explain,
>** If you vote everyday, ok you ll need to wait a lot of time before getting a nation.
> But if you vote and mine you ll get double gold (everyday i make around 20g)
> Also if you need haste potions, just brew a carrot if you are lvl 125 in alchemy.**

Making 40g a day will still take about 1 year to get max town claims. And yes you can make haste potions with carrots at lvl 125 alchemy

> Then about shops,people can sell something like bricks (idk why bricks) so they sell it in their shop so other people can buy them it s like irl.

^I don't get this point???

> So if you want to get more lag so you can make more "P U R E" gold then think about builders and other functionnalities wich wont work with lag, like brewing haste potions or having more players on earthmc, so residents who are gonna spend gold etc etc so think about that before writing a text about how you can get more gold.

I never asked for the lag to be brought back...

**Comment by johnyuki** [comment]
> We are not adding more gold to the server... this was a mechanic for a very long time before the lag was fixed

You *are* adding gold to the server though. Currently 1 gold ore gets turned in to 1 gold ingot. By adding in double smelt, there is the possibility of 1 gold ore becoming 2 gold ingots. You also want double drops to work on gold ore too, so you have 1 gold ore turning in to 2 gold ore, and then 2 gold ore turning in to 4 gold ingots. So you're basically quadrupling the amount of gold that certain players can bring in to the game. I'm pretty sure there are already a handful of people that have 1000 mining and smelting for 100% double chance, and if that feature gets turned back on, people can very easily grind to get 1000. 

Currently the economy is shit. God armour and god tools are dirt cheap because of the amount of villagers in the game and everyone trying to undercut each other. By causing gold inflation you will eventually have people easily making 100+ gold per day as they wil only need to find 25 gold ores thanks to the aforementioned double smelt and double drops. 25 gold ores in a day is extemely doable, and with haste 2 pots can be done in 1-2 hours. That means that if someone spends their entire day mining - they can create a nation. This will mean that prices for towns and nations have to be increased to account for the inflation, and the prices of all the other items will go up as a result. It will make mining for gold ore way too strong of a money-maker, and just fuck the economy up more than it already is. 

The thing the economy needs the most is either price locks on certain items such as enchanted books and diamonds. Diamonds are starting to fall to as low as 64 per gold now and have been dropping in value for a long time as more and more of them come in to the game. There are very few sinks for these types of items and it causes them to lose value. By increasing the value of these items then your gold will become worth more, so that when you go mining you don't have to find a stack of diamonds to sell for just a single gold anymore, and when you get a villager you can actually sell the enchanted books for more than a few gold nuggets. 

Diamonds used to be like 12-16 per gold, and the top tier enchanted books like Mending, Sharp 5, Power 5, Unb 3, etc, used to go for a few gold each. By controlling the flow of *all* items that come in to the game and not just gold, the value of commodities such as logs, leaves, saplings, diamonds, emeralds, enchanted books, etc will all increase, allowing people to actually earn gold. 

By significantly increasing the amount of gold coming in to the game by enabling double drops and double smelt, then the price of everything goes tits up again, and will eventually leads to towns and nations having to cost more as more gold comes in to the game. 

10 free gold per day is already plenty, and mining for gold is one of the best money making methods still, even with haste 2 pots being shortened due to the lag being fixed.

**Comment by Scorpionzzx** [comment]
Yeah idk why we say we should ad both double smelt and double drops. I was thinking one or the other... whichever is less laggy. I did a mining run today with a full inventory of haste pots and got about 70 gold... when usually I could get 100g with only 18 potions... not to mentions a whole inventory... So I think double smelt should be added to add at least balance out what haste pots used to be like. As for this gold inflation thing... I'm just asking for mining to be as profitable as it used to be... not this insane 4x gold you are proposing. And also yes... 10 free gold per day is fine... I never argued that it wasn't??  But I do see your point of gold inflation being bad now... In any case, I appreciate your intelligent and informed feedback. I'm going to remove my bit about the economy as I see its a stupid point to make right now.

**Comment by johnyuki** [comment]
> I did a mining run today with a full inventory of haste pots and got about 70 gold... 

Are you on crack? How the hell are you moaning about getting SEVENTY GOLD from a single mining trip????? That's like 1 hour! 70g for 1 hour of mining. Nothing else gets close to that. How can you be so greedy to be suggesting that mining needs to earn MORE gold???? The haste pots before were broken because of the lag. Haste pots lasting like 8+ minutes was not normal, and I am happy they are back down to their regular 2 minutes or whatever it is now. It's greed like this that completely ruins the economy to begin with. You aren't even happy with a 70g/hour money making method lmao.

**Comment by Scorpionzzx** [comment]
Because I used to get twice as much as my guy. And I didn't time it but I'm pretty sure it was more than 1 hour(I also used super breaker in between every other 2 haste pots).

**Comment by Scorpionzzx** [comment]
also yes I am on crack

**Comment by johnyuki** [comment]
> 
> 
> Because I used to get twice as much as my guy. And I didn't time it but I'm pretty sure it was more than 1 hour(I also used super breaker in between every other 2 haste pots).

You used to get twice as much because of the lag made the haste pots last longer. Effectively a bug. Or at the very least it was an unintended consequence of the lag that couldn't be fixed until the lag was fixed. Now that the lag is fixed the pots are back to normal. 

Also if it was over an hour, it wasn't too much longer. At the absolute most you have 35 haste 2 pots in your inv, but more realistically it would be 30. 2 minute per pot brings that up to 60 minutes, and super breaker only lasts a few seconds so you can add like another 3 minutes to that total, bringing it up to 63 minutes. That assumes you work for 63 minutes without stopping too which you likely didn't do, so we can add another 10 minutes on for various things such as talking, collecting ores, etc. So 73 minutes total. Or roughly 1g per minute. Spend an entire day mining and you have like 500g lmao.

**Comment by KarlOfDuty** [comment]
The above comments speak for themselves.
