### ISSUE TITLE
[Feature] We NEED a war plugin

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#809]
I believe that we need a war plugin. This is a geopolitical server, which means that is war aswell. As it is there is no way to actually conquer territory, and I don't mean annex towns, but force towns into nations. The reason that this should be possible is that crowded areas, like britain a couple of months ago, east coast, china, australia etc. have so many rival nations that can't unite the area. In these cases there is just constantly war that can't be resolved, as people can stay in their claims and then fight in stupid underhanded scenarios.

What I would propose is some sort of system where nations can declare war on others which would toggle pvp in each others to each other, and have it like in the old war days where tnt would temporarily break non-item storage blocks. Then there could either be an official way of having loser towns be forced to join the winner nation with some sort of deal, or points. Or where it would be that you'd just declare peace with not having the plugin force certain towns into nations.

If even this is not possible, or for a temporary fix I propose 2 other solutions. One is war days in which pvp is toggled on everywhere for a day or a certain allotted amount of time. Second is where once you get into pvp you wouldn't be able to run back into claims. I would argue claim-running is comparable to combat logging as the thing thats bad about both of them is that since the player committing the offence knows that they would lose the fight, they effectively "leave" the fight that they would lose and bullshit the other player by leaving a fight that they got into, and then left.

**Comment by DeadGlamour** [comment]
Claim hiding isnt comparable to pvp log, more like getting on a boat and getting away

**Comment by Magenent** [comment]
> Claim hiding isnt comparable to pvp log, more like getting on a boat and getting away

Not really, because when you have a boat and your getting away you are running so much that you can't be hit, but if the guy chasing was fast enough or had enough time it would be possible to kill the guy boating away while in claim hiding you are avoiding dying in pvp by walking a few chunks.

**Comment by MineHero43** [comment]
Just make it a system where if you’re at war with a nation, pvp is enabled in all towns in the respective nations(only members of the warring nations will actually be able to pvp in the towns) if a town doesn’t like having pvp on as a result of the war, just leave the nation or pressure your leader to sue for peace.

Really that’s all that is necessary, a simple pvp based system. Not some complex one which involves taking over town chunks etc

**Comment by johnyuki** [comment]
> 
> 
> Just make it a system where if you’re at war with a nation, pvp is enabled in all towns in the respective nations(only members of the warring nations will actually be able to pvp in the towns) if a town doesn’t like having pvp on as a result of the war, just leave the nation or pressure your leader to sue for peace.
> 
> Really that’s all that is necessary, a simple pvp based system. Not some complex one which involves taking over town chunks etc

This doesn't solve bigger army diplomacy though. It's just going to be larger nations bullying smaller nations. Like, imagine Britain going around in a large 16-man group fucking up Europe. 

You also have to take in to account things like:
 - When can a nation declare war? You can't declare at any time because that would be unfair on nations who are all offline, or only have a single person online. 
 - Bigger nations can just bully small nations and be in eternal war with them until they are bullied in to paying their own ransom. 
 - It will just result in nations camping each other, patrolling the town and making it so that the other nation simply cannot play the game until they pay a ransom. 

A war plugin just isn't a good idea. What *is* needed is a better pvp plugin to stop people from claim hiding. Pvp logging was a massive issue for some time, but that got solved. Claim hiding can get solved too. It's important to note that the biggest issue people have is just claim hiding. We don't need a super in-depth war plugin that is going to completely overhaul the dynamic of the server in order to combat claim hiding.

**Comment by ImperialFishy** [comment]
The idea of a war plugin isnt to combat claimhiding. Its to help a geopolitical server be a geopolitical server and not just an earth canvas to build on although that is also an essential part of it. Just not all of it.

**Comment by MineHero43** [comment]
If a war plugin were to be added, it should be pvp based, as for how nations declare war there are many ways it can be done, both nations need to agree or you pay a sum of gold to declare it etc

However another option would be to combat claimhiding and for that I would suggest adding onto the current combat logging plugin. Make it so that if you are combat tagged and you run into claims, you are still able to be attacked. That’s my suggestion at least

**Comment by KarlOfDuty** [comment]
There are already more specific issues open on this topic.
