### ISSUE TITLE
[Moderation] It's silly to immediately IP-ban hackers with no chance of appeal.  A friend of mine was affected by an IP-ban when his brother, on a different account, was caught hacking.

### ISSUE THREAD

**Issue by Ali-Mansour** [EarthMC/Issue-Tracker#810]
**Is your feature request related to a problem? Please describe.**

A player in my nation, VoltsYT, was affected by an IP-ban when his brother hacked on a different account.  His brother's ign is SmellyRat.  I attempted to appeal VoltsYT's IP-ban, but was told that due to your policy, the IP-ban on his brother cannot be removed and replaced with a normal ban.  What this means is that a very active and innocent player, who spent hours on your server, can no longer enjoy the server because he was collaterally affected by his brother's actions.

What I found to be even stranger was that your moderators suggested that VoltsYT use a VPN to circumvent the IP-ban...which I assume means that your moderators frequently tell hackers how to get around your IP-bans lol.  If it was VoltsYT's brother that made the appeal, he would have been told how to get around your IP-ban and still playing while VoltsYT himself would still be affected by the ban...

**Describe the solution you'd like**

Please change your policy on IP-bans where it is at least appealable so that people dont get wrongly affected in situations like this.  The policy you have in place right now not only affects innocent people, but the way your moderators handle it makes it easy for those hackers to learna bout solutions around your IP-bans.

So please revert SmellyRat's IP-ban to an account ban, which would allow VoltsYT to continue playing.

Thank you

**Additional context**

I found DocW's conduct during this to be kind of insensitive.  I was really asking for a solution to the situation and was giving pretty snarky remarks when I'm really just trying to help my friend with a frustrating situation.  

![image](https://user-images.githubusercontent.com/9808301/67187014-2739ea00-f39e-11e9-8329-55fc38b01fc5.png)

**Comment by johnyuki** [comment]
IP bans are the dumbest thing ever. One of my old friends had 5 siblings - all of whom played minecraft together on similar/the same servers. Should one of them get IP banned for hacking, they would all get banned from that server. 

IP bans are hilariously ineffective also because if someone really wanted to keep playing on alts and stuff then they would just get a VPN. However, forcing innocent people to jump through hoops and get a VPN in order to play is totally unfair.

**Comment by Nalasleafheart** [comment]
Almost every hacker on the server has gotten a VPN to change their IP so IP bans don't do much. See: the current bot situation. I don't understand why you would ban a whole household if one member has hacked. I can see this being abused though with "Oh it was my brother not me!" so a way around it is if they can prove they're in fact siblings to the staff team, the other family members should be allowed to join the server. VPNs aren't cheap almost every good one requires a monthly payment so forcing someone to use one just because another family member has messed up is wrong.

**Comment by VoltsYT** [comment]
I think this response from DocW is not only very unprofessional, but I found it very offensive. If somebody is given the privilege to act as support, you support people, you don't put them down. When people ask questions, they want legitimate answers, not your fantasies. I just hope EMC thinks twice before hiring arrogant, unapologetic people to "help" people.

**Comment by shirazmatas** [comment]
Please move this issue to -> https://github.com/EarthMC/EarthMC.net/issues
where rules and punishments are discussed
