### ISSUE TITLE
Add LWC (doorlocks/chestlocks) plug-in

### ISSUE THREAD

**Issue by TheRealSomeoneBetter** [EarthMC/Issue-Tracker#841]
As a builder type and mayor of my own town who talks with other builder types and mayors the conversation always goes to something like “man I really wish I could make apartments in my town to be able to accommodate more people” or “I wish I didn’t have to give people an entire chunk for a house” or “I have a modern city with towers and wish I could have more than one person living in them” or “if there were doorlocks I would have a lot more freedom in terms of the cities I could make”

The solution I propose is the LWC plugin. It’s really easy to use and on its own doesn’t really do much but, considering the context of this server, it would make a huge difference in terms of building communities and having more active people. This would pretty much be exclusively because it would allow mayor to accommodate more people instead of having people made to be felt left out. 

If this were to be implemented I can not wait to see the things people creat off of this kind of freedom. Especially for cities like New York or Rennes where they have many towers that could be used as apartments. Or even embassy buildings that house several diplomat apartments instead of having to, again, give people entire chunks.

**Comment by TheRealSomeoneBetter** [comment]
Wow what an awesome idea! I sure do hope to be able to utilize this very simple plugin in the future😯

**Comment by TheRealSomeoneBetter** [comment]
Something else I thought of, with sign shops being down it would bring a morale boost to those in a slump to see the server moving in a positive direction to accommodate more freedom in terms of building towns and communities

**Comment by DeadGlamour** [comment]
1. Did you really reply to your own post?
2. Sadly staff have already said they cant do it due to performences.

**Comment by TheRealSomeoneBetter** [comment]
Lol yes I replied to my own post it was a joke (everyone can see that I did it) but how long ago did they decide that because things could be different now

**Comment by DeadGlamour** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/244
Here, old 1, while Id love to see your suggestion happen, I just dont think we will.

**Comment by TheRealSomeoneBetter** [comment]
Oh okay yeah I’m suggesting an entirely different plugin. It’s very small in what it actually does so it wouldn’t effect server performance either. 

But so then this is something you would like to see done. Why is this something, in your opinion, something that you think would be useful to you and/or the emc community as a whole

**Comment by DeadGlamour** [comment]
Personally I just like skycrappers, so it could be cool doing it.

**Comment by TheRealSomeoneBetter** [comment]
Yeah I feel you. I have always thought it was a shame that New York didn’t have a tool to allow them to do that

**Comment by Cactusinapumpkin** [comment]
KarlOfDuty commented on Jul 29
We will not be adding another protection plugin as that will lower server performance further.
--
Karl 21/09/2019
Sorry about that, took a bit longer than assumed as there were a few bugs that needed fixing. At least the server should have better performance now.

Fix 04/10/2019 (oct 4)
After many performance updates I'm happy to announce that EarthMC now supports 200 players without lag. The server runs twice as fast (TPS) with twice as many players compared to a month ago. To celebrate, we have a 50% mcmmo xp boost and double vote gold special this weekend. Come join us at EarthMC.net! Thank you for your support. @everyone

Fix23/10/2019
EarthMC is back online.
- We've made significant changes to the server infrastructure, this is what has been taking so much time. Main server runs on its own dedicated server for better performance and stability.
- Factions is back online.
- Town cap increased to 100 from 75.

The performance issues have been greatly reduced since this issue was brought up last time.

**Comment by KarlOfDuty** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check out LWC compatibility and performance](https://trello.com/c/K5KrBvPP/36-check-out-lwc-compatibility-and-performance)

**Comment by Cactusinapumpkin** [comment]
Card not found.
This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams.

**Comment by docwhomc** [comment]
Could be a nice addition to the server.

**Comment by TheRealSomeoneBetter** [comment]
Every time I talk about this with other people the conversation always goes to “yeah it’s a really cool idea but it’ll probably never happen” People would definitely appreciate this implementation

**Comment by Prismary** [comment]
Correctly configured this may still be worth a thought, it may however impact server performance significantly and would probably confuse players more than Towny itself already does. Considering Karl hasn't been keen on adding more protection plugins I'll close this for now.
