### ISSUE TITLE
[Suggestion] Reset EarthMC

### ISSUE THREAD

**Issue by kaixlz** [EarthMC/Issue-Tracker#866]
**Is your feature request related to a problem? Please describe.**
Earthmc is getting very boring. I know I haven't played long enough to even suggest such a thing, but in truth, it is. There's way too many towns and nations now, and starting a town just doesn't feel fun anymore. Much less expanding on one. 

**Describe the solution you'd like**
Reset EarthMC Towny. There are a lot of people who would like this, including myself. The thrill EarthMC had when I joined is just simply not there anymore. Prices are way down, and so is the value of gold, in a way. Some people sell 2 Mending for 6 nuggets. If that isn't deflation, I don't know what is. So reset. Give everybody a fresh start.

**Additional context**

**Comment by watergod1234** [comment]
No. It’s way too early for a reset and most people aren’t even asking for it yet. Only way to make EarthMC appealing to late game status is by adding a war plugin. God knows if or when that’ll ever come out.

**Comment by FutureLemon** [comment]
I have been on TN since it started and I'm not even close to being done. No-one has achieved the impossible yet and TN still needs much more work.

**Comment by johnyuki** [comment]
EMC will need resetting soon as more and more people make towns and expand existing towns. Europe is filling up, Australia is filling up, NA is filling up. The only real areas left are Siberia, Africa, and South America, but all of those areas are in less-than-desirable biomes. Africa especially is crap because everyone griefs peoples towns when collecting sand.

I think in about 6 months or so people will start to realise that a reset will be necessary very soon. However when it is reset I would like to see some gameplay balance changes made - namely a way to manage the economy better and stop rampant inflation from happening on commonly traded items.

**Comment by DeadGlamour** [comment]
No, even once Europe will be filled (a lot of time) people could still build in many other places, asia wont ever be entirely claimed, same for the americas and any other place which isnt europe, also the server is only a year old, and just as FutureLemon said, most people arent even close to finish what they wanted.

**Comment by johnyuki** [comment]
> 
> 
> No, even once Europe will be filled (a lot of time) people could still build in many other places, asia wont ever be entirely claimed, same for the americas and any other place which isnt europe, also the server is only a year old, and just as FutureLemon said, most people arent even close to finish what they wanted.

It's not about space for new towns though. It's space for existing towns too. Once Europe and NA get to the point where there are going to be very few places you can actually create a town (I think Europe is already at that point now), then players will be forced to set up in the new areas, and those will fill up fast. Very few people will want to set up in Africa regardless of how much space there is due to the aforementioned sand mining grief. 

So once the server gets to the point where its only the shit locations left, then people are going to have to seriously consider preparing for a reset regardless of how close to being "finished" they are. I personally am looking forward to the reset. When the map reset last time there were only like 100 regular players on at a time, and the server only capped out it's 125 player limit on the weekends, with weekday nights dropping as long as 50 players. The server is now at a point where the playerslots are filled almost 24/7, so I think that is a possible mandate for map reset. 

I think once the main server issues are sorted out, mob movement is back, villagers breed again, etc, then a map reset would be nice.

**Comment by MineHero43** [comment]
Personally, I wouldn’t mind a reset 👀

**Comment by alekb1** [comment]
Honestly I feel the same way as Minehero, and would just love for something to add new life to emc. most of the old players have gone inactive as emc is not really a challenge and there is a lot of limitations in the current format. Imo a reset or just a more challenging spinoff format would be sweet.

**Comment by VonApollo** [comment]
my thoughts exactly, TN is starting to get boring, a solution is stated in my post history which would be to make a completely new towny server like factions or classic

**Comment by Goosius1** [comment]
F.Y.I

I am currently working to add a new war system to the Towny plugin. It is called Siege-War and it is focused on supporting geo-political conflict, including town invasions and empire building.

Here is a link to the PR so that you can monitor its progress: https://github.com/TownyAdvanced/Towny/pull/3541

**Comment by DasCodes** [comment]
We don't have any plan on resetting soon.
