### ISSUE TITLE
[BUG] Doublechatting

### ISSUE THREAD

**Issue by ClonedCopier** [EarthMC/Issue-Tracker#874]
**Server**
Towny

**Describe the bug**
The user speaks in two channels at the same time, nation and global. This sometimes results in players saying things in global that they do not mean to. This is because the bug is that the user will be entered into two channels upon joining, meaning if they try to enter nation chat, the user will be told they're already in it. They'll also be in global

**To Reproduce**
1. Go to Towny
2. Enter nation chat (/nc or /ch j nation)
3. Leave
4. Rejoin
5. Speak

**Expected behavior**
I expected to speak in only global

**Screenshots**
![image](https://user-images.githubusercontent.com/43768304/71528606-a7089700-28ae-11ea-84d5-836081016440.png)

**Additional context**
The workaround is to join the trade channel and then global

**Comment by Cactusinapumpkin** [comment]
yes when you leave the game while in nation chat and log back in it will show that you are talking in nation and global. Usually I just /ch join nation and it works for me. I kinda like the bug and dont mind it that much because its easier to fix than the /n spawn or /t spawn bug where you have goto a nether portal or use /joinqueue towny.
