### ISSUE TITLE
[Suggestion] Custom Crafting for Heart of the Sea

### ISSUE THREAD

**Issue by NeonKrby** [EarthMC/Issue-Tracker#895]
**Is your feature request related to a problem? Please describe.**
In Minecraft 1.13 there is an item called ¨The Heart of the Sea.¨ Normally these objects are found within buried treasure chests that you would find on a vanilla map. Because of EarthMC´s implementation of a custom map obtaining these items is now impossible. 

**Describe the solution you'd like**
I would love for a custom crafting recipe as we have for other unobtainable items to be created. I do not mind what cost this would be but I would love to be able to craft Conduits and build underwater cities.

**Comment by NeonKrby** [comment]
weekly bump to top of #issues

**Comment by JaVolimKatarinu** [comment]
I would love this. And in my opinion, this seems like the main feature of 1.13. I believe that it could raise the beauty of cities and also decrease the number of claims on the land. Not big enough number, but who could actually know? Towns to create map arts on ocean and bases underneath. With really good builders, it might become points of interest because of "art" underneath the art.. ( Kinda deep sentence, but I can't do better. Please try to understand.)
Generally, Heart of Sea would increase underwater bases and kinda aquarium stuff will be created. I already saw 2 dolphins, so it could be fun. 
About crafting recipe, if we consider gold worth at the moment, it might seem impossible to create expensive enough recipe. I have read config for fishing and it is really easy to add it. My suggestion is to add it under Record ( 0.25 T8, 0.10 T7, 0.05 T6). Fishing farms are not working because of the Kraken.

**Comment by NeonKrby** [comment]
perhaps sponges could get readded to vote crates and then the recipe could be like 1 sponge and 8 diamond blocks or something

**Comment by NeonKrby** [comment]
I just don't want them to end up being locked behind crates as in order to make a sprawling underwater city you would require a lot of them

**Comment by Warriorrrr** [comment]
I think that either adding it as a custom crafting recipe or a reward from fishing would be good. I agree with Krby about them not getting locked behind vote crates as a reward. Maybe some sort of recipe with gold blocks/sea lanterns?

**Comment by NeonKrby** [comment]
bump

**Comment by Basically-Andrew** [comment]
Hearts of the seas should now appear with wandering traders. This issue can be closed.

**Comment by Prismary** [comment]
> Hearts of the seas should now appear with wandering traders. This issue can be closed.
