### ISSUE TITLE
Poking Holes in Hollowclaims

### ISSUE THREAD

**Issue by JudithSheindlin** [EarthMC/Issue-Tracker#902]
Creating a new town inside a pre-exsisting hollowclaim to purposely then report that town for claimblocking shouldn't be allowed. Hollowclaims are allowed as long as the town has the ability to claim up the hollow claim. I don't think its fair to poke holes in towns that are claiming up their hollowclaims lawfully. 

Also, I want to also bring up a double standard I noticed regarding new towns and claimblocking. When the exclusion headquarters was made next to fuze city, it was removed for claimblocking fuze city, the pre-exsisting town. I believe there was a similar situation in China when a new town was removed after it was created 10 chunks next to a pre-exsisting one. However, when a new town is made in a pre-exsisting hollowclaim and the preexsisting town gets reported, the pre-exsisting town is unclaimed instead of the new town. How that fair?

**Comment by alekb1** [comment]
First of all, i doubt that mods will remove the claim around a town if you have sufficient proof, secondly hollow claiming is virtually claimblocking as you are encircling a large area that you want to keep from others. In this case i believe both things are bad, and that you should not create towns inside of hollow claims. On the other hand, getting punished for hollow claiming is fine imo as you are abusing the system to claim a larger area than you actually have the resources to claim

**Comment by Judemeiser** [comment]
> First of all, i doubt that mods will remove the claim around a town if you have sufficient proof, secondly hollow claiming is virtually claimblocking as you are encircling a large area that you want to keep from others. In this case i believe both things are bad, and that you should not create towns inside of hollow claims. On the other hand, getting punished for hollow claiming is fine imo as you are abusing the system to claim a larger area than you actually have the resources to claim
Actually, the mods removed the claims around VladThyInhaler's town when someone poked a hole in it. Also, hollow claiming has already been decided to be allowed. We aren't talking wether or not hollowclaiming is allowed or not, I'm bringing up a new rule idea.

**Comment by JaVolimKatarinu** [comment]
As an EarthMC Moderator, hollow claiming is not allowed in situations where there are few nearby towns which all want the same area to be theirs, or in situations where you are taking much more land than you could possibly claim with current limits on max residents and max nation bonus. 
Being single town in some area where there isn't a lot of towns near you and if you are trying to claim the area around your town which is possible to claim and will be claimed in near future, I would say that such a thing is allowed. 

Mostly, issues with hollow claims happen in quite an "urban" area where there are multiple towns fighting for the same point of land and everyone wants the area for themself. Therefore, mayors of such towns go and hollow claim the area just to secure themselves. That is not allowed as everyone should have a fair chance of getting "their piece of cake". 
And with creating a town inside of hollow claim, I have to say that has been some new type of claim blocking issues we are currently experiencing. From what happened to me, is that one town got accidentally created inside of a hollow claim and the mayor wasn't aware of it because he didn't check /towny map.

**Comment by Cactusinapumpkin** [comment]
I do like cake..

**Comment by Judemeiser** [comment]
> As an EarthMC Moderator, hollow claiming is not allowed in situations where there are few nearby towns which all want the same area to be theirs, or in situations where you are taking much more land than you could possibly claim with current limits on max residents and max nation bonus.
> Being single town in some area where there isn't a lot of towns near you and if you are trying to claim the area around your town which is possible to claim and will be claimed in near future, I would say that such a thing is allowed.
> 
> Mostly, issues with hollow claims happen in quite an "urban" area where there are multiple towns fighting for the same point of land and everyone wants the area for themself. Therefore, mayors of such towns go and hollow claim the area just to secure themselves. That is not allowed as everyone should have a fair chance of getting "their piece of cake".
> And with creating a town inside of hollow claim, I have to say that has been some new type of claim blocking issues we are currently experiencing. From what happened to me, is that one town got accidentally created inside of a hollow claim and the mayor wasn't aware of it because he didn't check /towny map.

Again, as I mentioned previously to alekb1, I'm not talking about the legality of hollow claims, I'm talking about "poking holes" in legal hollow claims.

**Comment by KarlOfDuty** [comment]
This will be judged in the same way as claiming next to any claim arms is, regardless of if the claim arm is circular or not.
