### ISSUE TITLE
[Idea] No man's land

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#923]
So basically every hour or however long it needs to be, there's an area on the map where loot chests can be found. They'll contain probably resources like iron, gold diamonds, or maybe even unobtainables like shulker shells and totems. Not only is this a good way to satisfy people who want to PvP, it also enables players to get the unobtainables, which previously have only been obtained through build competitions. 
Players will fight over the loot as it's a small area and each chest has it's coordinates marked in chat for players to go to. I think this is just easier than trying to develop a war plugin and is also more fun than just fighting near claims where if anyone gets low on health, they can just run into a town.

**Comment by Lagann311** [comment]
I would love to have this event on the server. Fix said he also wanted to add a war plugin but he‘s hesitating because it is difficult to balance. So this might be the solution for both satisfying people who want more pvp and adding unobtainable items like chorus fruits etc..
But if this gets inplemented I think there should be announcements when it happens. Not necessarily the exact time but for example „between 8-9pm GMT“.
Maybe it‘s even possible to add a plugin that automates the announcement + chest spawning.

**Comment by docwhomc** [comment]
There is a war plugin now, which we are discussing potential use of.
