### ISSUE TITLE
[BUG] Redstone does not work

### ISSUE THREAD

**Issue by Nerd00110001** [EarthMC/Issue-Tracker#980]
**Server**
Towny

**Describe the bug**
Redstone lines will not update whenever it is un-powered/powered. Primarily it will not update to the un-powered state after it is powered once (i.e. if you power a redstone line then remove its power source it should un-power but the bug is that it will not and will remained powered when there is no power source).

**To Reproduce**
1. Make a redstone line
2. power it with a redstone torch
3. remove the redstone torch

**Expected behavior**
The redstone line will remain powered .

**Comment by QJWIN** [comment]
i think is just a result of after server shuttdown, sometime to reduce lag, after the admin fix problems, they need to turn off the game rules concerning redstone functionality. normaly that functionality is back soon after

You should check in a normal condition if your bug is persisting, if not you can close the ticket ^^

**Comment by Nerd00110001** [comment]
Ok, thanks, I have never been through an update like this before. My main reason for putting this here was just to let them know that redstone is not working properly as I don't know if they themselves make redstone machines so it may just slip by them. I know that they have more important things concerning the update so I don't mean to complain, I just don't want it to go under the radar when it comes to fixing things from the update.

**Comment by DasCodes** [comment]
1.15 is currently on WIP, so things will turn on/off until it's stabilized, to prevent lag.
